In [51]:
import os
import pandas as pd
import numpy as np
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu
from sklearn.metrics import silhouette_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, KNNImputer

In [27]:
# Pandas 출력 옵션 조정 - All
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [29]:
# Pandas 출력 옵션 조정 - Default
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [2]:
## Defines
# Data confirmmation :: Nan counts + Nan Ratios, Unique values
def analyse_dataframe(df):
    # NaN 개수, 비율 및 고유 값 개수 계산
    nan_counts = df.isnull().sum()
    nan_ratios = df.isnull().mean() * 100  # 백분율로 표시
    unique_values_count = df.nunique()

    # 결과 데이터 프레임 생성
    analysis_result = pd.DataFrame({
        'NaN Counts': nan_counts,
        'NaN Ratios (%)': nan_ratios,
        'Unique Values Count': unique_values_count
    })

    return analysis_result

# 지정된 칼럼의 NaN 값을 해당 칼럼의 평균값으로 대입
def fill_na_with_mean(df, columns, decimal_places=None):
    for column in columns:
        mean_value = df[column].mean()
        if decimal_places is not None:
            mean_value = round(mean_value, decimal_places)
        elif decimal_places is None and column in integer_columns:
            mean_value = int(round(mean_value))
        df[column] = df[column].fillna(mean_value)
    return df

In [3]:
# Configs
base = r'C:\Dev_AIWM\jupyter\KNN'
cbk = f'{base}\\1212_M02'
raw_path1 = f'{base}\\1212_M02\\dataset'
raw_path = f'{base}\\olds\\raw_data'
crt_path = f'{base}\\1212_M02\\creatures'

In [4]:
req_cols = [
'sex_sys_val', 'birthdt'    # 'birthdt_sys_val' 없음, 'birthdt'
, 'MAGE', 'GRAN', 'PARN', 'AMNI', 'METC', 'FETC', 'FETC2'
, 'MULG', 'BIR1', 'BIR2', 'BIR3', 'BIR4', 'PREP', 'DM', 'HTN', 'CHOR', 'PROM'
, 'STER', 'ATBYN'
, 'BIRD', 'BPIA', 'ADMD', 'GAGEW', 'GAGED'
, 'APGS1', 'APGUK1', 'APGS5', 'APGUK5', 'RESU'
, 'BWEI', 'BHEI', 'BHEIUK', 'BHEAD', 'BHEADUK', 'BTEM', 'BTEMUK', 'BBPH', 'BBPHUK'
, 'SIGN', 'BBBE', 'BBBEUK'
, 'BHTCUT', 'BHDCUT', 'ALS', 'MPH', 'PH'
, 'PHUDSTDT', 'SFT', 'SFTTHDT', 'SFTFUDT', 'SFTUH'
, 'SFTUM', 'SFTUN', 'STRDU'
, 'BIRDH', 'BIRDM'    # EFYDT 추가 (0319)
, 'STRDUOT', 'OXYT28', 'ARRE28', 'DATE36', 'DEATH36', 'OXYT36', 'ARRE36', 'BDP', 'IARVPPD'
, 'NIARVRPD', 'NIARVHFNC', 'AOXYUPPD'
, 'DATE362', 'DELM'    # , 'DTHDT1' 추가 (01/27)
, 'ACL', 'PDAD', 'PDATR', 'PDADDT', 'PDADDTH'
, 'LBP', 'NESE', 'INHG'
, 'PVL', 'IBIF', 'IBIFCMT', 'SEPS', 'BSFDT1'
, 'MENI', 'MENIDT'
, 'INVFPOD', 'NTET', 'NTETDT', 'NTETY', 'NTETDTY', 'NTETOY', 'IPERR', 'IPERRDT', 'IPERROY'
## ------------------ 02/27 Added lists ------------------------------>>
, 'PMIRNSG', 'PMIRNSGND', 'EFYN', 'EFYDT', 'DCD', 'FDCDT', 'BSF1', 'STDAY', 'EYTHTRAN'
## ------------------ 04/15 Added list ------------------------------>>
, 'DEATH'
## ------------------ 02/27 Delete lists ------------------------------>>
# , 'PHUD1', 'PHUD2', 'PHUD3', 'PHUD4', 'PHUD5', 'PHUD6', 'PHUDOT'
# , 'PADDR1', 'PADDR2', 'PDADTY', 'ACLDT'
# , 'LBPD1', 'LBPD2', 'LBPD3', 'LBPDOT'
# , 'BSFFS1', 'BSF2', 'BSFFS2', 'BSF3', 'BSFDT3', 'BSFFS3'
# , 'FSF1', 'FSFDT1', 'FSFFS1', 'FSF2', 'FSFDT2', 'FSFFS2'
# , 'STERP', 'RESUO', 'RESUP', 'RESUI', 'RESUH', 'RESUE', 'RESUC'
# , 'SFTUP', 'SFTUR', 'SFTTH'
# , 'STRDUT1', 'STRDUT2', 'STRDUD1', 'STRDUD2', 'STRDUD3', 'STRDUD4'
# , 'STERD1', 'STERD2', 'STERD4'
# , 'PROMN', 'PROMD', 'PROMH', 'PRHO', 'PRDH'
# , 'MCOU', 'FCOU'
]

# 모든 칼럼 이름을 소문자로 변환
cols = [col.lower() for col in req_cols]
knn_df = pd.read_csv(os.path.join(raw_path1, "KNN_origin.csv"), usecols = cols)
# knn_df = pd.read_excel(os.path.join(raw_path1, "KNN_origin.xlsx"), usecols = cols)
# knn_df = pd.read_excel(os.path.join(raw_path, "(KNN)DATA.xlsx"), usecols = cols)
knn_df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3760666957.py:42: DtypeWarning: Columns (59,60,98,113) have mixed types. Specify dtype option on import or set low_memory=False.
  knn_df = pd.read_csv(os.path.join(raw_path1, "KNN_origin.csv"), usecols = cols)

,sex_sys_val,birthdt,mulg,bir1,bir2,bir3,bir4,prep,dm,htn,...,iperrdt,pmirnsg,pmirnsgnd,efyn,efydt,eythtran,fdcdt,stday,dcd,death
0,1,2013-12-18,1,NaN,NaN,NaN,NaN,1,1,2,...,NaN,0.0,NaN,2,2013-12-28,1,2014-02-06,50,1,NaN
1,1,2013-11-15,1,NaN,NaN,NaN,NaN,1,1,1,...,NaN,2.0,NaN,2,2013-12-15,2,2014-02-03,80,1,NaN
2,1,2013-11-15,2,1.0,NaN,NaN,NaN,1,1,1,...,NaN,0.0,NaN,2,2013-11-29,2,2014-01-08,54,1,NaN
3,1,2013-11-15,2,NaN,2.0,NaN,NaN,1,1,1,...,NaN,0.0,NaN,1,NaN,2,2014-01-22,68,2,NaN
4,1,2013-11-11,1,NaN,NaN,NaN,NaN,1,1,1,...,NaN,1.0,NaN,2,2013-12-12,2,2014-02-13,94,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,1,NaN,NaN,NaN,NaN,1,1,1,...,NaN,0.0,NaN,2,2022-12-25,1,2023-02-09,73,2,NaN
20409,1,2022-12-27,1,NaN,NaN,NaN,NaN,1,1,1,...,NaN,2.0,NaN,2,2023-01-30,2,2023-03-29,92,1,NaN
20410,2,2022-12-01,1,NaN,NaN,NaN,NaN,2,1,1,...,NaN,0.0,NaN,2,2022-12-06,2,2023-01-14,44,1,NaN
20411,1,2022-11-30,2,NaN,2.0,NaN,NaN,2,2,1,...,NaN,0.0,NaN,2,2022-12-09,1,2023-01-02,33,1,NaN
20412,1,2022-11-30,2,1.0,NaN,NaN,NaN,2,2,1,...,NaN,0.0,NaN,2,2022-12-07,1,2023-01-02,33,1,NaN

In [5]:
analyse_dataframe(knn_df)

             NaN Counts  NaN Ratios (%)  Unique Values Count
sex_sys_val           0        0.000000                    3
birthdt               0        0.000000                 3593
mulg                  0        0.000000                    4
bir1              17067       83.608485                    1
bir2              16421       80.443835                    1
...                 ...             ...                  ...
eythtran              0        0.000000                    2
fdcdt                 0        0.000000                 3633
stday                 0        0.000000                  313
dcd                   0        0.000000                    4
death             17815       87.272816                    6

[106 rows x 3 columns]

In [6]:
for column in knn_df.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {knn_df[column].dtype}")
    print(f"유니크한 값:")
    print(knn_df[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: mulg
데이터 타입: int64
유니크한 값:
[1 2 3 4]
----------------------------------------
칼럼 이름: bir1
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: bir2
데이터 타입: float64
유니크한 값:
[nan  2.]
----------------------------------------
칼럼 이름: bir3
데이터 타입: float64
유니크한 값:
[nan  3.]
----------------------------------------
칼럼 이름: bir4
데이터 타입: float64
유니크한 값:
[nan  4.]
----------------------------------------
칼럼 이름: prep
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: dm
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: htn
데이터 타입: int64
유니크한 값:
[2 1 3]
----------------------------------------
칼럼 이름: chor
데이터 타입: int64
유니크한 값:
[3 2 1]
----------------------------------------
칼럼 이름: prom
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: ster
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: delm
데이터 타입: int64
유니크한 값:
[2 1]
----------------------------------------
칼럼 이름: atbyn
데이터 타입: float64
유니크한 값:
[nan  2.  1.  3.]
----------------------------------------
칼럼 이름: amni
데이터 타입: int64
유니크한 값:
[1 2 4 3]
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: birdh
데이터 타입: float64
유니크한 값:
[20. 22. 15. 14.  1. 16. 21. 13. 10.  4.  9.  2.  8. 11. 12. nan  3. 19.
 18. 23. 17.  6.  7.  5.  0.]
----------------------------------------
칼럼 이름: birdm
데이터 타입: float64
유니크한 값:
[29. 30. 22. 23. 39. 32. 12. 14. 57. 20. 51. 55. 48. 18. 19. 40.  7. 27.
 24. 26.  0. 59. 45. nan  6. 54. 16. 38.  1. 33. 15.  9. 10. 53. 34. 17.
 37. 49. 43. 31. 35.  5.  4. 56. 13. 36. 58.  2.  8. 42. 52. 46. 50. 21.
 44. 41. 47. 28.  3. 25. 11.]
----------------------------------------
칼럼 이름: bpia
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: gagew
데이터 타입: int64
유니크한 값:
[30 26 29 27 33 32 31 28 34 35 25 23 24 22 36 21 37 38]
----------------------------------------
칼럼 이름: gaged
데이터 타입: int64
유니크한 값:
[4 0 2 5 3 1 6]
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.  5.  6.  3.  7.  1.  9.  8.  2. nan  0. 10.]
----------------------------------------
칼럼 이름: apguk1
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.  6.  7.  8.  4.  9.  1.  3. 10.  2. nan  0.]
----------------------------------------
칼럼 이름: apguk5
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: resu
데이터 타입: int64
유니크한 값:
[2 1 3]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470  390
 1015  860  865 1130 1090  920 1260 1190 1220 1320  980  660  600 1270
  940 1080 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840
  850 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120
 1020  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970
 1150 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047
 1312  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408
 1484 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010
 1286 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855
 1325  955  995  645  650  830  580  570  430  540  820  875  460  490
  520 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495
  380  816  846  932 1165 1375  805  533  420  705  775  915  849  615
  885 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285
  575  585  735 1295  935 1335  925  633 1113  776 1352 1048  893  755
  953  819 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657
  717  736 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879
 1486  458 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934
 1363  964  337 1066 1407  598 1028 1235  652  966  675  794  814  592
 1398 1036 1446 1496 1294 1024 1435  795  789  535  815  703 1415  832
  300 1305  330 1482  410 1454 1345 1095 1145  655  878  545 1395  450
  310  905  495  825 1005  671 1409 1441  595 1045  853  945 1334  833
 1075 1115 1275 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035
 1249 1093  405 1041  574  493 1229  709 1344  831  894  567  416 1062
 1122 1392 1026 1234  565 1049 1327  857  658 1012 1181  812 1246  842
 1136  649  974  618 1388 1198  943  902  340  975  665 1175 1155 1298
  701  639 1167 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762
 1277 1412 1418 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288
  754  501  494 1215 1123 1465  350  635  433  555  985 1105 1055  685
 1471  695 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202
 1456  654  949  972  764  739 1153  673 1272  917  753 1071  554  613
 1309  698  989  454  636 1059  558  772  506  696 1148  863 1201 1149
 1052 1492  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724
 1112  360 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314
 1046 1056 1469  434  991  672 1042 1265  702  914  475  715 1266 1116
  898  579 1368 1282  903  844  544  499 1332 1349  504  913  492  817
 1203  752  856  909  787  757  318  758  959 1213  566 1462  662  798
  977 1019 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328
  918  307 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227
  749  557 1068  674  485  551  605 1481  534  761  968  956  912 1428
  901  346  663  549  513 1419  907 1377  896  602  682  877  586  937
 1318  848  723 1089  948  996  926 1172  552 1373 1474  634 1177  854
  711 1258  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531
  328 1162 1158 1007 1447 1347 1111  503  568 1178  889  793  887  978
  818  923 1034 1021 1022  376 1004 1204  332 1443 1416 1316 1077 1171
  609  465 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593
 1139 1044  524  984  392 1051  641  345  569  799  963 1381 1236 1351
 1479 1208  617  837 1431  921  365  604 1323  612  983 1161 1078  796
 1001  546 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257
 1346 1379  619  806  788  938  572 1063  688  556  827 1114 1331  811
  882 1103  873  642 1324  668  497  608  564  421  647  973  588 1424
 1497  338  737 1144  684 1039 1493  677  713  824 1159 1038  601  621
  741  998 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783
 1073 1281  986 1088  325 1477  981  957  942  876  581  866  656 1292
  733 1287  692  452  469  631 1321  884  355 1214  625 1301  523  859
 1117 1173 1251  809 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500
 1650 1980 1920 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468
  872 1510 1880 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909
  742  944 1926 1545 1873 1718  539 1579  666  525  916 1273 1054 1850
 1820 1800 1567 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960
 1530 1600 1625 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900
 1710 1590 1930 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835
  928  447  374  999  559  429  532  502 1756 1990 1940 2000 1945 1765
 1506 1586 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564
  939 1391 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: metc
데이터 타입: object
유니크한 값:
[nan '대만' '북한' '러시아' '이집트' '인도' '모로코' '키르키즈스' '우즈베키스' '리비아' '시리아' '인도네시아'
 '남아프리카공화국' '우즈벡키스탄' '라오스' '우간다' '우즈베키스탄' '방글라데시' '키르키르스탄' '스리랑카' '모름'
 '키르기즈스탄' '가봉' '파키스탄' '아이티' '콩고' '네팔' '우크라이나' '말레이시아' '러시아(우즈베키스탄)'
 '키르기스스탄' '탈북' '알바니아' '카자흐스탄' '캐나다' '브룬디' '니카라과' '터키' '브라질' '타지키스탄' '싱가포르'
 '미얀마' 'Ireland' '영국']
----------------------------------------
칼럼 이름: fetc
데이터 타입: object
유니크한 값:
[nan '모름' '러시아' '이집트' '인도' '나이지리아' '태국' '우즈베키스' '리비아' '필리핀' '베트남' '시리아'
 '인도네시아' '남아프리카공화국' '정보 없음' '우간다' '몽골' '뉴질랜드' '방글라데시' '스리랑카' '키르기즈스탄' '가봉'
 '아버지가 정확히 누구인지 모름' '아이티' '캄보디아' '콩고' '부-미상' '캄보디아인' '말레이시아' '우즈베키스탄'
 '러시아(우즈베키스탄)' '키르기스스탄' '카자흐스탄' '캐나다' '에티오피아' '네팔' '북한' '외국인 - 모름'
 '우즈벡키스탄' '브룬디' '모름: 미혼모' '파키스탄' '알수없음' '정보없음' '정보 공개 거부' '대만' '코스타리카'
 '홍콩' '부 관계부정함 ' 'unmarried state 로 산모 정보 제공 거부'
 'unmarried state 로 아버지에 대한 정보 제공 거부']
----------------------------------------
칼럼 이름: fetc2
데이터 타입: float64
유니크한 값:
[ nan 169. 170. 237. 186. 161.  21.  81.  77. 212. 210. 207.  67. 123.
  36.  70.  43. 227. 188.   1.  18.]
----------------------------------------
칼럼 이름: bhtcut
데이터 타입: object
유니크한 값:
[nan '97' '50' '10' '90' '3' '97초과']
----------------------------------------
칼럼 이름: bhdcut
데이터 타입: object
유니크한 값:
[nan '90' '10' '50' '3' '97' '97초과']
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.  34.3 36.  42.  38.5 32.  40.5 34.  38.  41.  35.5 35.  29.5 40.
 31.  41.5 37.  36.5 39.5 30.  24.5 33.  30.5 36.2 33.5 25.5  nan 38.8
 37.8 34.7 37.1 27.  34.5 39.2 42.5 35.2 35.6 40.7 37.5 28.6 43.  28.
 29.  26.  31.5 32.5 31.8 43.5 37.2 28.5 27.5 38.4 36.3 35.1 40.8 33.6
 32.7 45.  23.  25.  32.8 39.3 32.3 41.2 44.  38.2 36.4 28.2 36.8 34.2
 39.4 41.3 33.7 35.8 31.4 48.  30.8 42.2 41.4 37.6 38.3 29.7 33.8 30.4
 36.6 46.  37.3 41.7 22.  42.8 40.3 38.1 31.2 25.7 24.  38.7 23.5 41.1
 34.8 39.8 27.8 32.1 35.3 31.7 40.2 30.2 37.7 40.6 26.5 45.5 34.4 28.8
 39.7 44.5 46.5 44.3 47.  35.4 42.3 27.1 33.2 22.2 30.6 34.6 47.7 37.4
 26.1 33.3 31.9 41.8 36.1 31.3 40.9 30.3 34.1 38.6 19.5 20.  29.2 32.4
 28.3 27.2 29.3 40.4 36.7 37.9 27.3 35.7 44.8 39.6 32.6 32.2 41.9 33.4
 42.6 38.9 25.3 34.9 29.4 49.  42.4 43.6 21.  32.9 39.9 29.8 21.5 33.9
 36.9 31.6 29.9 30.7 41.6 24.2 29.1 22.5 20.3 43.2 39.1 33.1 23.3 42.9
 42.7 26.6 42.1 40.1 43.8]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.  23.  28.5 26.5 29.5 28.3 24.5 30.  25.  29.  24.  27.5 30.5 27.
 25.5 26.  31.  23.5 36.  22.5 32.  22.  21.  19.  21.5 22.3 25.7 20.5
  nan 27.3 29.1 23.3 28.4 25.6 29.2 25.4 22.6 25.3 28.2 26.8 27.2 20.
 27.4 30.3 24.2 23.2 20.9 29.3 18.5 24.7 25.8 23.9 26.1 24.8 22.2 21.3
 23.1 24.3 31.5 20.7 26.2 19.5 23.6 21.6 27.7 26.6 27.6 26.4 34.2 31.3
 22.8 20.2 35.5 28.8 25.2 29.4 19.8 27.8 26.3 23.8 21.8 23.7 28.6 29.7
 28.7 26.7 28.1 30.2 24.6 20.3 23.4 27.1 24.4 33.5 22.7 27.9 21.4 29.8
 24.1 20.6 19.7 28.9 32.5 22.9 21.7 24.9 29.9 25.1 18.  33.  21.2 20.8
 22.4 25.9 17.5 38.  21.9 30.4 18.7 30.1 34.  31.2 20.1 26.9 29.6 19.3
 19.4 18.3 17.  30.7 20.4 19.9 32.7 19.2 19.6 22.1 18.6 21.1 34.5 16.
 30.6 35.  14.5 31.6 32.6 37.2 18.8 30.8]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4 36.5 36.6 37.  35.6 36.8 36.7 36.2 34.7 35.3 36.1 36.  36.3 35.4
 35.9 35.7 35.  35.5 38.   nan 35.8 34.8 35.2 35.1 34.5 34.6 37.1 34.
 36.9 37.6 33.  37.2 33.8 34.3 34.4 37.4 37.5 34.9 34.2 34.1 33.4 37.3
 33.5 33.1 33.6 33.2 32.7 33.7 33.9 32.3 37.9 37.8 37.7 32.1 38.2 33.3
 32.4 32.5 32.6 32.9 32.2 38.4 31.9 38.1 32.  38.8 32.8 31.3 38.3 38.7
 38.5 38.6 31. ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35 7.28 7.42 7.49 7.36 7.3  7.21 7.1  7.44 7.31 7.46 7.33 7.24 7.18
 7.4  7.48 7.29 7.53 7.34 7.23 7.25 7.2  7.06 7.02 7.04 7.11  nan 7.41
 7.43 7.26 7.32 7.39 7.19 7.27 7.09 7.13 6.82 6.98 7.16 7.38 6.88 7.08
 7.22 6.97 7.45 7.37 7.17 7.05 7.52 7.14 7.01 7.5  7.07 7.47 7.03 7.15
 6.9  6.99 7.12 7.57 6.7  6.64 6.8  6.85 7.   6.87 7.55 6.74 7.51 6.66
 6.89 6.96 6.86 6.84 6.95 7.58 7.54 6.92 6.76 6.5  6.54 6.91 6.93 6.71
 6.94 6.77 7.65 6.83 7.59 6.75 6.81 7.56 7.72 6.65 6.56 6.63 7.63 6.57
 6.67 6.55 7.68 6.73 7.69 7.6  6.79 7.66 6.68 6.69 7.62 6.17 6.61 6.51
 6.78 6.59 6.72]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: sign
데이터 타입: float64
유니크한 값:
[ 2.  1. nan]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ 5.3  1.7  1.5  3.9  2.3  5.4  9.2  6.8  1.   3.5  1.8  4.4  2.1  7.2
 10.   0.2  1.3  1.2  1.6  4.9  3.7  3.3  4.6  4.3  7.5 11.4 12.6  2.
  5.2  0.1 13.   9.1  nan  6.7  2.8  2.9 15.2  4.7  3.   3.6  5.1  4.2
  8.   0.8  5.9  3.8  4.1  6.2 10.1  9.8  6.   6.1  3.1  5.7  7.1 13.1
  9.   1.1 11.8  8.2  3.2 12.1 21.4  9.7 10.6 20.  15.6  9.5 11.5  6.4
  4.5 17.   4.   5.   8.1  5.6 17.4  4.8 10.2  2.5  7.3  2.4 12.9  5.5
  8.8 12.4 10.7  9.3  8.4 10.3  3.4  7.7  1.9  7.  16.   0.  19.  15.
 18.  11.   0.6 11.9  2.7  2.6  0.4  2.2  9.9  6.9  6.3  0.7 14.  12.
  0.5  5.8 14.3  8.7 12.7 10.5 11.7  0.3  6.6  7.4 11.3 13.6  6.5  8.3
  1.4 14.1  0.9 18.3  8.6  7.8 15.9  9.6 18.7 13.5 13.4  8.9 11.6 14.9
 19.1 15.7  7.9 10.8 23.  19.3 12.2  8.5 14.7 10.4 13.8 10.9 26.  16.6
 12.3  9.4 13.2  7.6 16.7 17.5 24.  11.1 15.3 20.5 17.2 17.8 20.8 16.3
 15.5 13.7 18.9 19.4 16.5 16.4 16.1 12.8 15.8 17.1 23.4 14.4 19.9 22.
 21.  13.3 20.3 21.2 11.2 16.8 17.3 21.1 15.1 21.7 21.5 20.2 14.5 22.9
 12.5 13.9 14.6 18.8 25.5 20.1 17.7 14.2 24.1 25.  21.6 19.2 17.9 21.8
 18.2 14.8 17.6 25.1 15.4 22.2 19.5 24.8 23.6 18.4 22.5 16.2 23.9 24.2
 25.2 20.6 20.9 21.3 19.8 22.6 16.9 27.  18.1 26.4 24.9 19.7 29.  24.5
 28.  22.8 24.6 26.9 18.6 22.3 20.4 20.7]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[nan  1.]
----------------------------------------
칼럼 이름: als
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: mph
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: ph
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: phudstdt
데이터 타입: object
유니크한 값:
[nan '2013-09-14' '2013-09-06' ... '2023-01-07' '2022-01-17' '2022-04-23']
----------------------------------------
칼럼 이름: sft
데이터 타입: int64
유니크한 값:
[2 1]
----------------------------------------
칼럼 이름: sftfudt
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-12-20' '2022-07-09'
 '2022-03-09']
----------------------------------------
칼럼 이름: sftuh
데이터 타입: float64
유니크한 값:
[21. 22. 15. 19. 18.  1. 16. 14. 11. nan  9.  2. 23.  8. 13. 20. 10.  4.
  6. 12.  0. 17.  7.  3.  5.]
----------------------------------------
칼럼 이름: sftum
데이터 타입: float64
유니크한 값:
[30. 56. 45. 20. 15. 48. 32. 10.  0. nan 40. 36. 34. 35. 55. 53.  5.  3.
 47. 21. 50. 25.  6. 18. 26. 17.  4. 12.  8.  1. 51. 37. 23. 54. 33. 44.
 49. 46. 31. 27. 16.  9.  7. 57. 58. 13. 19. 14. 42. 29. 59. 41. 24. 43.
 11. 38. 52. 22. 39. 28.  2.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[ 2.  1. nan  3.  4.  5.  6.  7.  9.]
----------------------------------------
칼럼 이름: sftthdt
데이터 타입: object
유니크한 값:
[nan 'gavage tube 통해 투여함.' 'neb']
----------------------------------------
칼럼 이름: strdu
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: strduot
데이터 타입: object
유니크한 값:
[nan 'pulmicort' 'betamethasone' 'pulmican' 'budesonide'
 'ventolin,pulmicort' 'methylprednisolone' 'methysol' 'Budesonide' 'PRD-s'
 'bedesonide' 'budesonide,ipratropium' 'budecort' 'budesonide nebulizer'
 'ventolin' 'budesonide  흡입 치료' 'methyl prednisolone' 'solondo' 'curosurf']
----------------------------------------
칼럼 이름: oxyt28
데이터 타입: int64
유니크한 값:
[1 3 2 4]
----------------------------------------
칼럼 이름: arre28
데이터 타입: float64
유니크한 값:
[ 0.  6.  7. nan]
----------------------------------------
칼럼 이름: oxyt36
데이터 타입: float64
유니크한 값:
[ 1.  2.  3. nan]
----------------------------------------
칼럼 이름: arre36
데이터 타입: float64
유니크한 값:
[ 0.  6.  7. nan]
----------------------------------------
칼럼 이름: date362
데이터 타입: object
유니크한 값:
[nan '2021-12-21' '2022-01-03' '2022-01-06' '2022-01-26' '2022-01-14'
 '2022-01-29' '2021-12-13' '2021-12-24' '2021-04-30' '2021-07-06'
 '2022-01-20' '2021-05-29' '2021-06-06' '2021-07-07' '2022-01-09'
 '2022-01-11' '2021-12-31' '2021-12-09' '2021-12-14' '2021-12-20'
 '2022-01-12' '2021-12-28' '2022-01-27' '2022-02-15' '2022-01-31'
 '2022-02-05' '2022-01-17' '2021-01-10' '2021-02-10' '2021-06-17'
 '2021-06-16' '2021-05-31' '2021-06-02' '2021-08-25' '2021-08-10'
 '2021-07-23' '2021-10-02' '2021-09-27' '2021-10-25' '2021-11-17'
 '2021-11-22' '2022-02-01' '2021-11-25' '2022-01-28' '2021-12-08'
 '2022-02-04' '2021-11-29' '2021-12-29' '2021-12-17' '2022-02-09'
 '2022-03-08' '2022-02-16' '2022-02-18' '2022-02-11' '2022-03-19'
 '2021-06-30' '2021-12-07' '2021-12-25' '2021-11-28' '2021-11-12'
 '2022-02-26' '2022-01-13' '2022-01-18' '2022-02-12' '2022/03/22'
 '2022-02-19' '2022-02-23' '2021-05-05' '2021-04-05' '2021-03-24'
 '2021-05-12' '2021-07-08' '2021-06-05' '2021-07-31' '2021-08-07'
 '2021-08-21' '2021-10-08' '2021-12-02' '2021-09-17' '2021-07-04'
 '2021-10-22' '2021-11-02' '2022-01-07' '2021-11-15' '2022-02-08'
 '2021-09-03' '2021-11-13' '2021-12-05' '2022-01-04' '2021-04-21'
 '2021-06-12' '2021-06-27' '2021-07-30' '2021-09-10' '2021-10-12'
 '2021-10-23' '2022-02-17' '2021-05-14' '2021-03-14' '2021-03-20'
 '2021-03-27' '2021-04-17' '2021-03-31' '2021-06-13' '2021-06-26'
 '2021-07-09' '2021-08-20' '2021-08-03' '2021-10-06' '2021-09-15'
 '2021-09-11' '2022-02-22' '2022-01-21' '2022-02-06' '2021-12-27'
 '2022-01-19' '2021-12-10' '2021-12-01' '2022-01-24' '2022-02-03'
 '2021-12-18' '2021-12-11' '2021-12-23' '2022-02-24' '2022-01-15'
 '2022-03-07' '2021-09-06' '2021-11-04' '2022-03-23' '2022-03-12'
 '2022-06-11' '2022-07-06' '2022-07-30' '2022-08-02' '2022-09-28'
 '2022-11-11' '2022-11-26' '2022-11-22' '2022-12-21' '2023-01-28'
 '2023-02-08' '2023-02-06' '2023-01-21' '2023-01-07' '2022-03-28'
 '2022-04-01' '2022-03-30' '2022-04-15' '2022-05-30' '2022-05-25'
 '2022-07-10' '2022-06-20' '2022-05-26' '2022-06-14' '2022-08-05'
 '2022-06-21' '2022-07-02' '2022-06-28' '2022-07-29' '2022-08-15'
 '2022-08-23' '2022-09-03' '2022-09-11' '2022-11-08' '2022-11-17'
 '2022-11-25' '2022-12-07' '2023-02-05' '2022-12-26' '2023-01-31'
 '2023-01-15' '2022-03-16' '2022-04-21' '2022-04-30' '2022-04-26'
 '2022-06-29' '2022-09-06' '2022-10-04' '2022-10-09' '2022-11-23'
 '2022-12-06' '2023-01-09' '2022-03-13' '2022-03-01' '2022-04-11'
 '2022-05-15' '2022-07-05' '2022-06-06' '2022-07-13' '2022-07-18'
 '2022-09-01' '2022-09-12' '2022-08-25' '2022-07-31' '2022-08-04'
 '2022-08-18' '2022-09-10' '2022-09-27' '2022-11-05' '2022-10-29'
 '2022-12-22' '2022-10-13' '2022-12-31' '2022-12-12' '2023-01-16'
 '2023-02-07' '2023-01-20' '2023-01-11' '2023-02-17' '2023-01-29'
 '2023-01-14' '2022-03-02' '2022-03-03' '2022-02-25' '2022-03-22'
 '2022-04-03' '2022-04-04' '2022-03-31' '2022-03-24' '2022-05-05'
 '2022-03-29' '2022-04-18' '2022-04-24' '2022-05-02' '2022-04-06'
 '2022-06-02' '2022-06-19' '2022-05-16' '2022-06-22' '2022-06-17'
 '2022-07-20' '2022-07-11' '2022-06-16' '2022-07-23' '2022-08-16'
 '2022-07-28' '2022-07-25' '2022-09-18' '2022-08-22' '2022-10-06'
 '2022-10-15' '2022-11-02' '2022-10-02' '2022-09-25' '2022-09-16'
 '2022-11-06' '2022-10-26' '2022-10-22' '2022-12-08' '2022-11-27'
 '2023-01-06' '2023-01-19' '2023-01-13' '2023-03-17' '2022-01-23'
 '2022-03-14' '2022-05-06' '2022-06-01' '2022-06-26' '2022-09-15'

In [7]:
## nan / 0 Findings

In [8]:
dfc = knn_df

summary = []

for col in dfc.columns:
    dtype = dfc[col].dtype
    total = len(dfc)
    nan_count = dfc[col].isna().sum()
    nan_ratio = nan_count / total * 100
    zero_count = (dfc[col] == 0).sum() if np.issubdtype(dtype, np.number) else np.nan
    zero_ratio = (zero_count / total * 100) if np.issubdtype(dtype, np.number) else np.nan

    summary.append({
        'column': col,
        'dtype': dtype,
        'nan_count': nan_count,
        'nan_ratio(%)': round(nan_ratio, 2),
        'zero_count': zero_count,
        'zero_ratio(%)': round(zero_ratio, 2) if not pd.isna(zero_ratio) else np.nan
    })

df_summary = pd.DataFrame(summary)
df_summary.to_csv(os.path.join(crt_path, "cols_summary_4Rev.csv"), index=True)
df_summary

          column    dtype  nan_count  nan_ratio(%)  zero_count  zero_ratio(%)
0    sex_sys_val    int64          0          0.00         0.0           0.00
1        birthdt   object          0          0.00         NaN            NaN
2           mulg    int64          0          0.00         0.0           0.00
3           bir1  float64      17067         83.61         0.0           0.00
4           bir2  float64      16421         80.44         0.0           0.00
..           ...      ...        ...           ...         ...            ...
101     eythtran    int64          0          0.00         0.0           0.00
102        fdcdt   object          0          0.00         NaN            NaN
103        stday    int64          0          0.00       254.0           1.24
104          dcd    int64          0          0.00         0.0           0.00
105        death  float64      17815         87.27         0.0           0.00

[106 rows x 6 columns]

In [9]:
knn_df['niarvhfnc']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
20408    0.0
20409    5.0
20410    9.0
20411    0.0
20412    0.0
Name: niarvhfnc, Length: 20413, dtype: float64

In [10]:
## Imputations

In [11]:
# # 1. 평균값으로 대체할 칼럼들
# mean_cols = ['apgs1', 'apgs5', 'btem', 'bbph', 'bhead', 'bhei']
# knn_df[mean_cols] = knn_df[mean_cols].fillna(knn_df[mean_cols].mean())

# 2. 0으로 대체할 칼럼들
zero_cols = ['ntetoy', 'arre36', 'death36', 'bir1', 'bir2'
             , 'bir3', 'bir4', 'niarvhfnc'
             , 'arre28', 'btemuk'
             , 'bbphuk', 'bbbeuk', 'bheaduk', 'bheiuk'
             , 'sftun', 'pdad'
## ------------------ 02/27 Delete lists ------------------------------>>
#             'strdut1', 'strdut2', 'pdadty', 'paddr1', 'paddr2'
#              , 'sterp', 'strdud1', 'strdud2', 'strdud3', 'strdud4'
#              , 'bsf1', 'bsffs1', 'bsf2', 'bsffs2', 'bsf3', 'bsffs3'
#              , 'lbpd1', 'lbpd2', 'lbpd3', 'fsf1', 'fsffs1', 'fsf2', 'fsffs2'
#              , 'resuc', 'resue', 'resui', 'resuo', 'resuh', 'resup'
#              , 'phud1', 'phud2', 'phud3', 'phud4', 'phud5', 'phud6'
#              , 'sftup', 'sftur', 'sftth'
#              , 'sterd2', 'sterd1', 'sterd4', 'menifs'
#              , 'promh', 'promn', 'prdh'
            ]
knn_df[zero_cols] = knn_df[zero_cols].fillna(0)

# 3. 시간 및 날짜 포맷 관련 처리할 칼럼들
date_cols = ['birthdt', 'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt', 'pdaddt', 'iperrdt'
             , 'bsfdt1', 'fdcdt', 'efydt', 'phudstdt'
## ------------------ 02/27 Delete lists ------------------------------>>
#              , 'acldt', 'bsfdt3', 'fsfdt1', 'fsfdt2', 'promd
            ]
for col in date_cols:
    knn_df[col] = pd.to_datetime(knn_df[col], errors='coerce').dt.date

knn_df['pdaddth'] = knn_df['pdaddth'].apply(
    lambda x: f"{int(x):02}:00" if not pd.isna(x) else None
)


# # 4. prho 처리: 시간 형식으로 변환 및 결측값 NaT 처리
# knn_df['prho'] = knn_df['prho'].apply(
#     lambda x: f"{int(x):02}:00" if not pd.isna(x) else None
# )

# 5. 그 외 값 대입
knn_df['ntety'].fillna(1, inplace=True)
knn_df['oxyt36'].fillna(1, inplace=True)
knn_df['iperroy'].fillna(1, inplace=True)
knn_df['atbyn'].fillna(3, inplace=True)

# 6. sign과 bbbe 처리: {sign}+{bbbe} 생성 후 sign 삭제
knn_df['sign'] = knn_df['sign'].replace({1: '+', 2: '-'})
knn_df['bbbe'] = knn_df['sign'].astype(str) + knn_df['bbbe'].astype(str)
knn_df['bbbe'] = pd.to_numeric(knn_df['bbbe'], errors='coerce')
knn_df['bbbe'].fillna(knn_df['bbbe'].mean(), inplace=True)

# birdm, birdh -> birtm 생성
before_birdm_birdh = len(knn_df)
knn_df.dropna(subset=['birdh', 'birdm'], inplace=True)
after_birdm_birdh = len(knn_df)
print(f"Removed {before_birdm_birdh - after_birdm_birdh} individuals due to missing 'birdh' or 'birdm'.")
knn_df['birdh'] = knn_df['birdh'].astype(int)
knn_df['birdm'] = knn_df['birdm'].astype(int)
knn_df['birtm'] = pd.to_datetime(knn_df['birdh'].astype(str) + ':' + knn_df['birdm'].astype(str), format='%H:%M', errors='coerce')
knn_df['birtm'] = knn_df['birtm'].dt.strftime('%H:%M')

# 'lbpdot', 'phudot'
# 7. 삭제할 칼럼들
drop_cols = ['apguk1', 'apguk5', 'fetc2', 'fetc', 'strduot', 'metc', 'ibifcmt'
             , 'bhdcut', 'bhtcut', 'phudstdt', 'sftum', 'sftuh', 'sftfudt'
             , 'sftthdt', 'birdm', 'birdh', 'sign'
             # , 'lbpdot', 'phudot'
            ]
# knn_df.drop(columns=drop_cols, inplace=True)

# 보조적 산소/유량 투여기간 : 결즉인원 제거
if 'aoxyuppd' in knn_df.columns:
    before_aoxyuppd = len(knn_df)
    knn_df.dropna(subset=['aoxyuppd'], inplace=True)
    after_aoxyuppd = len(knn_df)
    print(f"Removed {before_aoxyuppd - after_aoxyuppd} individuals due to missing 'aoxyuppd'.")

# sex_sys_val
count_sex_val_3 = knn_df['sex_sys_val'].value_counts().get(3, 0) if 'sex_sys_val' in knn_df.columns else "Column 'sex_sys_val' does not exist"
print("n of sex_sys_val Unknown :", count_sex_val_3)
knn_df = knn_df[knn_df['sex_sys_val'] != 3] if 'sex_sys_val' in knn_df.columns else knn_df
print(knn_df[['sex_sys_val']])

# 결과 확인
knn_df.info()

Removed 52 individuals due to missing 'birdh' or 'birdm'.
Removed 1 individuals due to missing 'aoxyuppd'.
n of sex_sys_val Unknown : 8
       sex_sys_val
0                1
1                1
2                1
3                1
4                1
...            ...
20408            1
20409            1
20410            2
20411            1
20412            1

[20352 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 20352 entries, 0 to 20412
Columns: 107 entries, sex_sys_val to birtm
dtypes: float64(38), int32(2), int64(42), object(25)
memory usage: 16.6+ MB

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\344628415.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['ntety'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\344628415.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['oxyt36'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\344628415.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['iperroy'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\344628415.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['atbyn'].fillna(3, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\344628415.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['bbbe'].fillna(knn_df['bbbe'].mean(), inplace=True)

In [11]:
'''# 2. 0으로 대체할 칼럼들
zero_cols = ['ntetoy', 'arre36', 'death36', 'bir1', 'bir2'
             , 'bir3', 'bir4', 'niarvhfnc'
             , 'arre28', 'btemuk'
             , 'bbphuk', 'bbbeuk', 'bheaduk', 'bheiuk'
             , 'sftun', 'pdad'
## ------------------ 02/27 Delete lists ------------------------------>>
#             'strdut1', 'strdut2', 'pdadty', 'paddr1', 'paddr2'
#              , 'sterp', 'strdud1', 'strdud2', 'strdud3', 'strdud4'
#              , 'bsf1', 'bsffs1', 'bsf2', 'bsffs2', 'bsf3', 'bsffs3'
#              , 'lbpd1', 'lbpd2', 'lbpd3', 'fsf1', 'fsffs1', 'fsf2', 'fsffs2'
#              , 'resuc', 'resue', 'resui', 'resuo', 'resuh', 'resup'
#              , 'phud1', 'phud2', 'phud3', 'phud4', 'phud5', 'phud6'
#              , 'sftup', 'sftur', 'sftth'
#              , 'sterd2', 'sterd1', 'sterd4', 'menifs'
#              , 'promh', 'promn', 'prdh'
            ]
knn_df[zero_cols] = knn_df[zero_cols].fillna(0)

# 3. 시간 및 날짜 포맷 관련 처리할 칼럼들
date_cols = ['birthdt', 'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt', 'pdaddt', 'iperrdt'
             , 'bsfdt1', 'fdcdt', 'efydt', 'phudstdt'
## ------------------ 02/27 Delete lists ------------------------------>>
#              , 'acldt', 'bsfdt3', 'fsfdt1', 'fsfdt2', 'promd
            ]
for col in date_cols:
    knn_df[col] = pd.to_datetime(knn_df[col], errors='coerce').dt.date

knn_df['pdaddth'] = knn_df['pdaddth'].apply(
    lambda x: f"{int(x):02}:00" if not pd.isna(x) else None
)


# # 4. prho 처리: 시간 형식으로 변환 및 결측값 NaT 처리
# knn_df['prho'] = knn_df['prho'].apply(
#     lambda x: f"{int(x):02}:00" if not pd.isna(x) else None
# )

# 5. 그 외 값 대입
knn_df['ntety'].fillna(1, inplace=True)
knn_df['oxyt36'].fillna(1, inplace=True)
knn_df['iperroy'].fillna(1, inplace=True)
knn_df['atbyn'].fillna(3, inplace=True)

# 6. sign과 bbbe 처리: {sign}+{bbbe} 생성 후 sign 삭제
knn_df['sign'] = knn_df['sign'].replace({1: '+', 2: '-'})
knn_df['bbbe'] = knn_df['sign'].astype(str) + knn_df['bbbe'].astype(str)
knn_df['bbbe'] = pd.to_numeric(knn_df['bbbe'], errors='coerce')
knn_df['bbbe'].fillna(knn_df['bbbe'].mean(), inplace=True)

# birdm, birdh -> birtm 생성
before_birdm_birdh = len(knn_df)
knn_df.dropna(subset=['birdh', 'birdm'], inplace=True)
after_birdm_birdh = len(knn_df)
print(f"Removed {before_birdm_birdh - after_birdm_birdh} individuals due to missing 'birdh' or 'birdm'.")
knn_df['birdh'] = knn_df['birdh'].astype(int)
knn_df['birdm'] = knn_df['birdm'].astype(int)
knn_df['birtm'] = pd.to_datetime(knn_df['birdh'].astype(str) + ':' + knn_df['birdm'].astype(str), format='%H:%M', errors='coerce')
knn_df['birtm'] = knn_df['birtm'].dt.strftime('%H:%M')

# 'lbpdot', 'phudot'
# 7. 삭제할 칼럼들
drop_cols = ['apguk1', 'apguk5', 'fetc2', 'fetc', 'strduot', 'metc', 'ibifcmt'
             , 'bhdcut', 'bhtcut', 'phudstdt', 'sftum', 'sftuh', 'sftfudt'
             , 'sftthdt', 'birdm', 'birdh', 'sign'
             # , 'lbpdot', 'phudot'
            ]
# knn_df.drop(columns=drop_cols, inplace=True)

# 보조적 산소/유량 투여기간 : 결즉인원 제거
if 'aoxyuppd' in knn_df.columns:
    before_aoxyuppd = len(knn_df)
    knn_df.dropna(subset=['aoxyuppd'], inplace=True)
    after_aoxyuppd = len(knn_df)
    print(f"Removed {before_aoxyuppd - after_aoxyuppd} individuals due to missing 'aoxyuppd'.")

# sex_sys_val
count_sex_val_3 = knn_df['sex_sys_val'].value_counts().get(3, 0) if 'sex_sys_val' in knn_df.columns else "Column 'sex_sys_val' does not exist"
print("n of sex_sys_val Unknown :", count_sex_val_3)
knn_df = knn_df[knn_df['sex_sys_val'] != 3] if 'sex_sys_val' in knn_df.columns else knn_df
print(knn_df[['sex_sys_val']])

# 결과 확인
knn_df.info()'''

Removed 52 individuals due to missing 'birdh' or 'birdm'.
Removed 1 individuals due to missing 'aoxyuppd'.
n of sex_sys_val Unknown : 8
       sex_sys_val
0                1
1                1
2                1
3                1
4                1
...            ...
20408            1
20409            1
20410            2
20411            1
20412            1

[20352 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 20352 entries, 0 to 20412
Columns: 107 entries, sex_sys_val to birtm
dtypes: float64(38), int32(2), int64(42), object(25)
memory usage: 16.6+ MB

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30640\2061347014.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['ntety'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30640\2061347014.py:45: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['oxyt36'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30640\2061347014.py:46: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['iperroy'].fillna(1, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30640\2061347014.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['atbyn'].fillna(3, inplace=True)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30640\2061347014.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  knn_df['bbbe'].fillna(knn_df['bbbe'].mean(), inplace=True)

'# 2. 0으로 대체할 칼럼들\nzero_cols = [\'ntetoy\', \'arre36\', \'death36\', \'bir1\', \'bir2\'\n             , \'bir3\', \'bir4\', \'niarvhfnc\'\n             , \'arre28\', \'btemuk\'\n             , \'bbphuk\', \'bbbeuk\', \'bheaduk\', \'bheiuk\'\n             , \'sftun\', \'pdad\'\n## ------------------ 02/27 Delete lists ------------------------------>>\n#             \'strdut1\', \'strdut2\', \'pdadty\', \'paddr1\', \'paddr2\'\n#              , \'sterp\', \'strdud1\', \'strdud2\', \'strdud3\', \'strdud4\'\n#              , \'bsf1\', \'bsffs1\', \'bsf2\', \'bsffs2\', \'bsf3\', \'bsffs3\'\n#              , \'lbpd1\', \'lbpd2\', \'lbpd3\', \'fsf1\', \'fsffs1\', \'fsf2\', \'fsffs2\'\n#              , \'resuc\', \'resue\', \'resui\', \'resuo\', \'resuh\', \'resup\'\n#              , \'phud1\', \'phud2\', \'phud3\', \'phud4\', \'phud5\', \'phud6\'\n#              , \'sftup\', \'sftur\', \'sftth\'\n#              , \'sterd2\', \'sterd1\', \'sterd4\', \'menifs\'\n#              , \'promh\', \'promn\', \'prdh\'\n            ]\nknn_df[zero_cols] = knn_df[zero_cols].fillna(0)\n\n# 3. 시간 및 날짜 포맷 관련 처리할 칼럼들\ndate_cols = [\'birthdt\', \'ntetdt\', \'ntetdty\', \'date362\', \'date36\', \'menidt\', \'pdaddt\', \'iperrdt\'\n             , \'bsfdt1\', \'fdcdt\', \'efydt\', \'phudstdt\'\n## ------------------ 02/27 Delete lists ------------------------------>>\n#              , \'acldt\', \'bsfdt3\', \'fsfdt1\', \'fsfdt2\', \'promd\n            ]\nfor col in date_cols:\n    knn_df[col] = pd.to_datetime(knn_df[col], errors=\'coerce\').dt.date\n\nknn_df[\'pdaddth\'] = knn_df[\'pdaddth\'].apply(\n    lambda x: f"{int(x):02}:00" if not pd.isna(x) else None\n)\n\n\n# # 4. prho 처리: 시간 형식으로 변환 및 결측값 NaT 처리\n# knn_df[\'prho\'] = knn_df[\'prho\'].apply(\n#     lambda x: f"{int(x):02}:00" if not pd.isna(x) else None\n# )\n\n# 5. 그 외 값 대입\nknn_df[\'ntety\'].fillna(1, inplace=True)\nknn_df[\'oxyt36\'].fillna(1, inplace=True)\nknn_df[\'iperroy\'].fillna(1, inplace=True)\nknn_df[\'atbyn\'].fillna(3, inplace=True)\n\n# 6. sign과 bbbe 처리: {sign}+{bbbe} 생성 후 sign 삭제\nknn_df[\'sign\'] = knn_df[\'sign\'].replace({1: \'+\', 2: \'-\'})\nknn_df[\'bbbe\'] = knn_df[\'sign\'].astype(str) + knn_df[\'bbbe\'].astype(str)\nknn_df[\'bbbe\'] = pd.to_numeric(knn_df[\'bbbe\'], errors=\'coerce\')\nknn_df[\'bbbe\'].fillna(knn_df[\'bbbe\'].mean(), inplace=True)\n\n# birdm, birdh -> birtm 생성\nbefore_birdm_birdh = len(knn_df)\nknn_df.dropna(subset=[\'birdh\', \'birdm\'], inplace=True)\nafter_birdm_birdh = len(knn_df)\nprint(f"Removed {before_birdm_birdh - after_birdm_birdh} individuals due to missing \'birdh\' or \'birdm\'.")\nknn_df[\'birdh\'] = knn_df[\'birdh\'].astype(int)\nknn_df[\'birdm\'] = knn_df[\'birdm\'].astype(int)\nknn_df[\'birtm\'] = pd.to_datetime(knn_df[\'birdh\'].astype(str) + \':\' + knn_df[\'birdm\'].astype(str), format=\'%H:%M\', errors=\'coerce\')\nknn_df[\'birtm\'] = knn_df[\'birtm\'].dt.strftime(\'%H:%M\')\n\n# \'lbpdot\', \'phudot\'\n# 7. 삭제할 칼럼들\ndrop_cols = [\'apguk1\', \'apguk5\', \'fetc2\', \'fetc\', \'strduot\', \'metc\', \'ibifcmt\'\n             , \'bhdcut\', \'bhtcut\', \'phudstdt\', \'sftum\', \'sftuh\', \'sftfudt\'\n             , \'sftthdt\', \'birdm\', \'birdh\', \'sign\'\n             # , \'lbpdot\', \'phudot\'\n            ]\n# knn_df.drop(columns=drop_cols, inplace=True)\n\n# 보조적 산소/유량 투여기간 : 결즉인원 제거\nif \'aoxyuppd\' in knn_df.columns:\n    before_aoxyuppd = len(knn_df)\n    knn_df.dropna(subset=[\'aoxyuppd\'], inplace=True)\n    after_aoxyuppd = len(knn_df)\n    print(f"Removed {before_aoxyuppd - after_aoxyuppd} individuals due to missing \'aoxyuppd\'.")\n\n# sex_sys_val\ncount_sex_val_3 = knn_df[\'sex_sys_val\'].value_counts().get(3, 0) if \'sex_sys_val\' in knn_df.columns else "Column \'sex_sys_val\' does not exist"\nprint("n of sex_sys_val Unknown :", count_sex_val_3)\nknn_df = knn_df[knn_df[\'sex_sys_val\'] != 3] if \'sex_sys_val\' in knn_df.columns else knn_df\nprint(knn_df[[\'sex_sys_val\']])\n\n# 결과 확인\nknn_df.info()'

In [12]:
# 칼럼 'acl' 처리 --> 3개 칼럼에 대해 확인해서 진행 : 총 5개 칼럼 제작
knn_df['pda_non-treatment'] = ((knn_df['pdad'].isin([1, 0])) &
                                (knn_df['acl'].isin([1, np.nan])) &
                                (knn_df['pdatr'].isin([14, 15]))).astype(int)
knn_df['pda_med-only'] = ((knn_df['pdad'] == 2) &
                          (knn_df['acl'] == 1)).astype(int)
knn_df['pda_op-only'] = ((knn_df['pdad'] == 1) &
                         (knn_df['acl'] == 2)).astype(int)
knn_df['pda_med+op'] = ((knn_df['pdad'] == 2) &
                        (knn_df['acl'] == 2)).astype(int)
knn_df['pda_unknown'] = ((knn_df['pdatr'].isin([12, 13, 16])) &
                         (knn_df['acl'].isin([3, np.nan]))).astype(int)

# 각 칼럼별 1의 개수 출력
counts = knn_df[['pda_non-treatment', 'pda_med-only', 'pda_op-only', 'pda_med+op', 'pda_unknown']
               ].sum()
print(counts)
knn_df[['pda_non-treatment', 'pda_med-only', 'pda_op-only', 'pda_med+op', 'pda_unknown']]

knn_df['PDA_TRD'] = ((knn_df['pda_med-only'] == 1) | 
                      (knn_df['pda_op-only'] == 1) | 
                      (knn_df['pda_med+op'] == 1)
                    ).astype(int)

# 'PDA_TRD'와 'pda_unknown' 출력
print(knn_df[['PDA_TRD', 'pda_unknown']])
counts = knn_df[['PDA_TRD', 'pda_unknown']].sum()
print(counts)

pda_non-treatment    13052
pda_med-only          4758
pda_op-only            567
pda_med+op            1385
pda_unknown            584
dtype: int64
       PDA_TRD  pda_unknown
0            1            0
1            0            0
2            0            0
3            1            0
4            1            0
...        ...          ...
20408        1            0
20409        1            0
20410        0            0
20411        0            0
20412        0            0

[20352 rows x 2 columns]
PDA_TRD        6710
pda_unknown     584
dtype: int64

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['pda_non-treatment'] = ((knn_df['pdad'].isin([1, 0])) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['pda_med-only'] = ((knn_df['pdad'] == 2) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['pda_op-only'] = ((knn_df['pdad'] == 1) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['pda_med+op'] = ((knn_df['pdad'] == 2) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['pda_unknown'] = ((knn_df['pdatr'].isin([12, 13, 16])) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2013537768.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['PDA_TRD'] = ((knn_df['pda_med-only'] == 1) |

In [15]:
# # .dt accessor를 다시 쓰기 전에 datetime 형식으로 재변환
# date_cols_for_dt = [
#     'birthdt', 'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt',
#     'pdaddt', 'iperrdt', 'bsfdt1', 'fdcdt', 'efydt', 'phudstdt'
# ]
# for col in date_cols_for_dt:
#     if col in knn_df.columns:
#         knn_df[col] = pd.to_datetime(knn_df[col], errors='coerce')

# .dt accessor를 다시 쓰기 전에 datetime 형식으로 재변환 + 비교 출력
date_cols_for_dt = [
    'birthdt', 'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt',
    'pdaddt', 'iperrdt', 'bsfdt1', 'fdcdt', 'efydt', 'phudstdt'
]

comparison_results = {}

for col in date_cols_for_dt:
    if col not in knn_df.columns:
        continue

    before = knn_df[col].copy()
    after = pd.to_datetime(knn_df[col], errors='coerce')

    # 실제 적용
    knn_df[col] = after

    cmp_df = pd.DataFrame({
        'before': before,
        'after': after
    })

    before_as_dt = pd.to_datetime(before, errors='coerce')
    same_or_both_missing = before_as_dt.eq(after) | (before_as_dt.isna() & after.isna())
    n_diff = (~same_or_both_missing).sum()

    comparison_results[col] = {
        'before_dtype': before.dtype,
        'after_dtype': knn_df[col].dtype,
        'n_diff': int(n_diff),
        'diff_rows': cmp_df.loc[~same_or_both_missing, ['before', 'after']]
    }

    print(f"\n[{col}]")
    print(f"before dtype: {before.dtype}")
    print(f"after  dtype: {knn_df[col].dtype}")
    print(f"n different rows: {n_diff}")

    if n_diff > 0:
        print(cmp_df.loc[~same_or_both_missing, ['before', 'after']].head(20))
    else:
        print("All values are identical (or both missing).")

[birthdt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[ntetdt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[ntetdty]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[date362]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[date36]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[menidt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[pdaddt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[iperrdt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[bsfdt1]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[fdcdt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[efydt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

[phudstdt]
before dtype: object
after  dtype: datetime64[ns]
n different rows: 0
All values are identical (or both missing).

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\4179043236.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col] = after

In [16]:
# PPHN
knn_df['PPHN'] = ((knn_df['phudstdt'] - knn_df['birthdt']).dt.days <= 7).astype(int)
print(knn_df[['phudstdt', 'birthdt', 'PPHN']])


# PDA_7d_NTET
knn_df['PDA_7d_NTET'] = ((knn_df['PDA_TRD'] == 1) &
                          (knn_df['ntet'] == 2) &
                          ((knn_df['ntetdt'] - knn_df['pdaddt']).dt.days.between(0, 7))).astype(int)
# PDA_7d_IPERR
knn_df['PDA_7d_IPERR'] = ((knn_df['PDA_TRD'] == 1) &
                           (knn_df['iperr'].isin([2, 3, 4])) &
                           ((knn_df['iperrdt'] - knn_df['pdaddt']).dt.days.between(0, 7))).astype(int)# 7d_PDA
knn_df['7d_PDA'] = ((knn_df['PDA_7d_NTET'] == 1) | 
                     (knn_df['PDA_7d_IPERR'] == 1)).astype(int)
print(knn_df[['7d_PDA', 'PDA_7d_NTET', 'PDA_7d_IPERR']])

# SEPS_bef_IPERRorNTET : SEPS_bef_NTET OR SEPS_bef_IPERR
knn_df['PDA_7d_IPERRorNTET'] = (knn_df['PDA_7d_NTET'] | knn_df['PDA_7d_IPERR']
                               ).astype(int)
print(knn_df[['PDA_7d_IPERRorNTET']])


# death_label (Decease Label) & death_dt(Decease date)
knn_df['death_label'] = (knn_df['dcd'] == 3).astype(int)
knn_df['death_dt'] = knn_df['fdcdt'].where(knn_df['dcd'] == 3, pd.NaT)


# SEPS_bef_NTET : (ntet == 2 & bsf1 == 1) && bsfdt1 < ntetdt
knn_df['SEPS_bef_NTET'] = ((knn_df['ntet'] == 2) & 
                            (knn_df['bsf1'] == 1) & 
                            (knn_df['bsfdt1'] < knn_df['ntetdt'])).astype(int)
# SEPS_aft_NTET : (ntet == 2 & bsf1 == 1) && bsfdt1 > ntetdt
knn_df['SEPS_aft_NTET'] = ((knn_df['ntet'] == 2) & 
                            (knn_df['bsf1'] == 1) & 
                            (knn_df['bsfdt1'] > knn_df['ntetdt'])).astype(int)
# SEPS_bef_IPERR : (iperr == 2|3|4 & bsf1 == 1) && bsfdt1 < iperrdt
knn_df['SEPS_bef_IPERR'] = ((knn_df['iperr'].isin([2, 3, 4])) & 
                             (knn_df['bsf1'] == 1) & 
                             (knn_df['bsfdt1'] < knn_df['iperrdt'])).astype(int)
# SEPS_aft_IPERR : (iperr == 2|3|4 & bsf1 == 1) && bsfdt1 > iperrdt
knn_df['SEPS_aft_IPERR'] = ((knn_df['iperr'].isin([2, 3, 4])) & 
                             (knn_df['bsf1'] == 1) & 
                             (knn_df['bsfdt1'] > knn_df['iperrdt'])).astype(int)
print(knn_df[['SEPS_bef_NTET', 'SEPS_aft_NTET', 'SEPS_bef_IPERR', 'SEPS_aft_IPERR']])

# SEPS_bef_IPERRorNTET : SEPS_bef_NTET OR SEPS_bef_IPERR
knn_df['SEPS_bef_IPERRorNTET'] = (knn_df['SEPS_bef_NTET'] |
                                  knn_df['SEPS_bef_IPERR']).astype(int)
# SEPS_aft_IPERRorNTET : SEPS_aft_NTET OR SEPS_aft_IPERR
knn_df['SEPS_aft_IPERRorNTET'] = (knn_df['SEPS_aft_NTET'] |
                                  knn_df['SEPS_aft_IPERR']).astype(int)
print(knn_df[['SEPS_bef_IPERRorNTET', 'SEPS_aft_IPERRorNTET']])


# stday : week/day 형식 값 변환
knn_df['stday'] = knn_df['stday']
# NTET_day : (in ntet == 2)
knn_df['NTET_day'] = np.where(
    (knn_df['ntet'] == 2) & ((knn_df['ntetdt'] - knn_df['birthdt']).dt.days >= 0),
    (knn_df['ntetdt'] - knn_df['birthdt']).dt.days, np.nan)
# IPERR_day : (in iperr == 2|3|4)
knn_df['IPERR_day'] = np.where(
    (knn_df['iperr'].isin([2, 3, 4])) & ((knn_df['iperrdt'] - knn_df['birthdt']).dt.days >= 0),
    (knn_df['iperrdt'] - knn_df['birthdt']).dt.days, np.nan)
# EFYN_day : (in efyn == 2)
knn_df['EFYN_day'] = np.where(
    (knn_df['efyn'] == 2) & ((knn_df['efydt'] - knn_df['birthdt']).dt.days >= 0),
    (knn_df['efydt'] - knn_df['birthdt']).dt.days, np.nan)
# EFYN_day : NaN -> mean
efyn_na_count = knn_df['EFYN_day'].isna().sum()
efyn_total = len(knn_df)
efyn_na_ratio = (efyn_na_count / efyn_total) * 100
print(f"n of NaN -> Mean in EFYN_day: {efyn_na_count}")
print(f"{efyn_na_count} {efyn_na_ratio:.2f}% / {efyn_total}")
# knn_df['EFYN_day'] = knn_df['EFYN_day'].fillna(knn_df['EFYN_day'].mean())



# knn_df[['NTET_day', 'IPERR_day', 'EFYN_day']] = knn_df[['NTET_day'
#                                                         , 'IPERR_day'
#                                                         , 'EFYN_day']].fillna(0)
print(knn_df[['stday', 'NTET_day', 'IPERR_day', 'EFYN_day']])



# # stday : week/day 형식 값 변환
# knn_df['stday'] = knn_df['stday'] / 7
# # NTET_day : (in ntet == 2)
# knn_df['NTET_day'] = np.where(
#     (knn_df['ntet'] == 2) & ((knn_df['ntetdt'] - knn_df['birthdt']).dt.days >= 0),
#     (knn_df['ntetdt'] - knn_df['birthdt']).dt.days / 7, np.nan)
# # IPERR_day : (in iperr == 2|3|4)
# knn_df['IPERR_day'] = np.where(
#     (knn_df['iperr'].isin([2, 3, 4])) & ((knn_df['iperrdt'] - knn_df['birthdt']).dt.days >= 0),
#     (knn_df['iperrdt'] - knn_df['birthdt']).dt.days / 7, np.nan)
# # EFYN_day : (in efyn == 2)
# knn_df['EFYN_day'] = np.where(
#     (knn_df['efyn'] == 2) & ((knn_df['efydt'] - knn_df['birthdt']).dt.days >= 0),
#     (knn_df['efydt'] - knn_df['birthdt']).dt.days / 7, np.nan)

# knn_df[['NTET_day', 'IPERR_day', 'EFYN_day']] = knn_df[['NTET_day'
#                                                         , 'IPERR_day'
#                                                         , 'EFYN_day']].fillna(0)
# print(knn_df[['stday', 'NTET_day', 'IPERR_day', 'EFYN_day']])

# 불필요한 칼럼 삭제
knn_df.drop(columns=['acl', 'pdatr', 'pdad', 'pda_med-only', 'pda_op-only', 'pda_med+op'
                     , 'dcd', 'fdcdt', 'bsf1', 'bsfdt1'
                    ] + list(drop_cols)
            , inplace=True
           )

      phudstdt    birthdt  PPHN
0          NaT 2013-12-18     0
1          NaT 2013-11-15     0
2          NaT 2013-11-15     0
3          NaT 2013-11-15     0
4          NaT 2013-11-11     0
...        ...        ...   ...
20408      NaT 2022-11-28     0
20409      NaT 2022-12-27     0
20410      NaT 2022-12-01     0
20411      NaT 2022-11-30     0
20412      NaT 2022-11-30     0

[20352 rows x 3 columns]
       7d_PDA  PDA_7d_NTET  PDA_7d_IPERR
0           0            0             0
1           0            0             0
2           0            0             0
3           0            0             0
4           0            0             0
...       ...          ...           ...
20408       0            0             0
20409       0            0             0
20410       0            0             0
20411       0            0             0
20412       0            0             0

[20352 rows x 3 columns]
       PDA_7d_IPERRorNTET
0                       0
1                       0
2                       0
3                       0
4                       0
...                   ...
20408                   0
20409                   0
20410                   0
20411                   0
20412                   0

[20352 rows x 1 columns]
       SEPS_bef_NTET  SEPS_aft_NTET  SEPS_bef_IPERR  SEPS_aft_IPERR
0                  0              0               0               0
1                  0              0               0               0
2                  0              0               0               0
3                  0              0               0               0
4                  0              0               0               0
...              ...            ...             ...             ...
20408              0              0               0               0
20409              0              0               0               0
20410              0              0               0               0
20411              0              0               0               0
20412              0              0               0               0

[20352 rows x 4 columns]
       SEPS_bef_IPERRorNTET  SEPS_aft_IPERRorNTET
0                         0                     0
1                         0                     0
2                         0                     0
3                         0                     0
4                         0                     0
...                     ...                   ...
20408                     0                     0
20409                     0                     0
20410                     0                     0
20411                     0                     0
20412                     0                     0

[20352 rows x 2 columns]
n of NaN -> Mean in EFYN_day: 2527
2527 12.42% / 20352
       stday  NTET_day  IPERR_day  EFYN_day
0         50       NaN        NaN      10.0
1         80       NaN        NaN      30.0
2         54       NaN        NaN      14.0
3         68       NaN        NaN       NaN
4         94       NaN        NaN      31.0
...      ...       ...        ...       ...
20408     73       NaN        NaN      27.0
20409     92       NaN        NaN      34.0
20410     44       NaN        NaN       5.0
20411     33       NaN        NaN       9.0
20412     33       NaN        NaN       7.0

[20352 rows x 4 columns]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['PPHN'] = ((knn_df['phudstdt'] - knn_df['birthdt']).dt.days <= 7).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['PDA_7d_NTET'] = ((knn_df['PDA_TRD'] == 1) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['PDA_7d_IPERR'] = ((knn_df['PDA_TRD'] == 1) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['7d_PDA'] = ((knn_df['PDA_7d_NTET'] == 1) |
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['PDA_7d_IPERRorNTET'] = (knn_df['PDA_7d_NTET'] | knn_df['PDA_7d_IPERR']
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['death_label'] = (knn_df['dcd'] == 3).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['death_dt'] = knn_df['fdcdt'].where(knn_df['dcd'] == 3, pd.NaT)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_bef_NTET'] = ((knn_df['ntet'] == 2) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_aft_NTET'] = ((knn_df['ntet'] == 2) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_bef_IPERR'] = ((knn_df['iperr'].isin([2, 3, 4])) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_aft_IPERR'] = ((knn_df['iperr'].isin([2, 3, 4])) &
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_bef_IPERRorNTET'] = (knn_df['SEPS_bef_NTET'] |
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['SEPS_aft_IPERRorNTET'] = (knn_df['SEPS_aft_NTET'] |
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['stday'] = knn_df['stday']
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['NTET_day'] = np.where(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['IPERR_day'] = np.where(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df['EFYN_day'] = np.where(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\1302268995.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df.drop(columns=['acl', 'pdatr', 'pdad', 'pda_med-only', 'pda_op-only', 'pda_med+op'

In [17]:
# '사망 원인' 칼럼 -> Binary column
death_mapping = {
    1: 'CR',
    2: 'NL',
    3: 'Inf',
    4: 'GI',
    5: 'CA',
    6: 'Otr'
}
new_columns = []
for code, abbrev in death_mapping.items():
    col_name = f'death_{abbrev}'
    knn_df[col_name] = (knn_df['death'] == code).astype(int)
    new_columns.append(col_name)
print("Created binary cols:")
for col in new_columns:
    print(f"\nCreated col_name: {col}")
    print(knn_df[col].value_counts(dropna=False))
    print("-" * 40)

knn_df.drop(columns='death', inplace=True)

Created binary cols:

Created col_name: death_CR
death_CR
0    19146
1     1206
Name: count, dtype: int64
----------------------------------------

Created col_name: death_NL
death_NL
0    20113
1      239
Name: count, dtype: int64
----------------------------------------

Created col_name: death_Inf
death_Inf
0    19934
1      418
Name: count, dtype: int64
----------------------------------------

Created col_name: death_GI
death_GI
0    20052
1      300
Name: count, dtype: int64
----------------------------------------

Created col_name: death_CA
death_CA
0    20258
1       94
Name: count, dtype: int64
----------------------------------------

Created col_name: death_Otr
death_Otr
0    20018
1      334
Name: count, dtype: int64
----------------------------------------

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df[col_name] = (knn_df['death'] == code).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\3740312812.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_df.drop(columns='death', inplace=True)

In [19]:
analyse_dataframe(knn_df)

                      NaN Counts  NaN Ratios (%)  Unique Values Count
sex_sys_val                    0        0.000000                    2
birthdt                        0        0.000000                 3591
mulg                           0        0.000000                    4
bir1                           0        0.000000                    2
bir2                           0        0.000000                    2
bir3                           0        0.000000                    2
bir4                           0        0.000000                    2
prep                           0        0.000000                    2
dm                             0        0.000000                    3
htn                            0        0.000000                    3
chor                           0        0.000000                    3
prom                           0        0.000000                    3
ster                           0        0.000000                    3
delm                           0        0.000000                    2
atbyn                          0        0.000000                    3
amni                           0        0.000000                    4
bird                           0        0.000000                 3591
bpia                           0        0.000000                    3
admd                           0        0.000000                 3592
gagew                          0        0.000000                   18
gaged                          0        0.000000                    7
apgs1                        121        0.594536                   11
apgs5                        117        0.574882                   11
resu                           0        0.000000                    3
bwei                           0        0.000000                  902
mage                           0        0.000000                   40
gran                           0        0.000000                   16
parn                           0        0.000000                   10
bhei                        1137        5.586675                  186
bheiuk                         0        0.000000                    2
bhead                       1230        6.043632                  147
bheaduk                        0        0.000000                    2
btem                         631        3.100432                   72
btemuk                         0        0.000000                    2
bbph                        4597       22.587461                  114
bbphuk                         0        0.000000                    2
bbbe                           0        0.000000                  327
bbbeuk                         0        0.000000                    2
als                            0        0.000000                    2
mph                            0        0.000000                    2
ph                             0        0.000000                    2
sft                            0        0.000000                    2
sftun                          0        0.000000                    9
strdu                          0        0.000000                    2
oxyt28                         0        0.000000                    4
arre28                         0        0.000000                    3
oxyt36                         0        0.000000                    3
arre36                         0        0.000000                    3
date362                    18196       89.406447                  503
date36                      5024       24.685535                 3205
death36                        0        0.000000                    2
bdp                            0        0.000000                    5
iarvppd                        0        0.000000                  225
niarvrpd                       0        0.000000                  167
aoxyuppd                       0        0.000000                  113
niarvhfnc                      0        0.000000                  111
pdaddt                     14194       69.742531                 2800
pdaddth                    14655       72.007665                   25
lbp                            0        0.000000                    2
nese                           0        0.000000                    2
inhg                           0        0.000000                    6
pvl                            0        0.000000                    3
ibif                           0        0.000000                    2
seps                           0        0.000000                    3
meni                           0        0.000000                    2
menidt                     20253       99.513561                   98
invfpod                        0        0.000000                  222
ntet                           0        0.000000                    3
ntetdt                     19385       95.248624                  802
ntety                          0        0.000000                    4
ntetoy                         0        0.000000                    4
ntetdty                    19837       97.469536                  473
iperr                          0        0.000000                    4
iperroy                        0        0.000000                    4
iperrdt                    19995       98.245873                  326
pmirnsg                     2901       14.254127                    6
pmirnsgnd                  17451       85.745873                    1
efyn                           0        0.000000                    3
efydt                       2527       12.416470                 3615
eythtran                       0        0.000000                    2
stday                          0        0.000000                  313
birtm                          0        0.000000                 1439
pda_non-treatment              0        0.000000                    2
pda_unknown                    0        0.000000                    2
PDA_TRD                        0        0.000000                    2
PPHN                           0        0.000000                    2
PDA_7d_NTET                    0        0.000000                    2
PDA_7d_IPERR                   0        0.000000                    2
7d_PDA                         0        0.000000                    2
PDA_7d_IPERRorNTET             0        0.000000                    2
death_label                    0        0.000000                    2
death_dt                   17761       87.269064                 1790
SEPS_bef_NTET                  0        0.000000                    2
SEPS_aft_NTET                  0        0.000000                    2
SEPS_bef_IPERR                 0        0.000000                    2
SEPS_aft_IPERR                 0        0.000000                    2
SEPS_bef_IPERRorNTET           0        0.000000                    2
SEPS_aft_IPERRorNTET           0        0.000000                    2
NTET_day                   19385       95.248624                   79
IPERR_day                  19997       98.255700                   55
EFYN_day                    2527       12.416470                  169
death_CR                       0        0.000000                    2
death_NL                       0        0.000000                    2
death_Inf                      0        0.000000                    2
death_GI                       0        0.000000                    2
death_CA                       0        0.000000                    2
death_Otr                      0        0.000000                    2

In [21]:
knn_df

,sex_sys_val,birthdt,mulg,bir1,bir2,bir3,bir4,prep,dm,htn,...,SEPS_aft_IPERRorNTET,NTET_day,IPERR_day,EFYN_day,death_CR,death_NL,death_Inf,death_GI,death_CA,death_Otr
0,1,2013-12-18,1,0.0,0.0,0.0,0.0,1,1,2,...,0,NaN,NaN,10.0,0,0,0,0,0,0
1,1,2013-11-15,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,30.0,0,0,0,0,0,0
2,1,2013-11-15,2,1.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,14.0,0,0,0,0,0,0
3,1,2013-11-15,2,0.0,2.0,0.0,0.0,1,1,1,...,0,NaN,NaN,NaN,0,0,0,0,0,0
4,1,2013-11-11,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,31.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,27.0,0,0,0,0,0,0
20409,1,2022-12-27,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,34.0,0,0,0,0,0,0
20410,2,2022-12-01,1,0.0,0.0,0.0,0.0,2,1,1,...,0,NaN,NaN,5.0,0,0,0,0,0,0
20411,1,2022-11-30,2,0.0,2.0,0.0,0.0,2,2,1,...,0,NaN,NaN,9.0,0,0,0,0,0,0
20412,1,2022-11-30,2,1.0,0.0,0.0,0.0,2,2,1,...,0,NaN,NaN,7.0,0,0,0,0,0,0

In [22]:
for column in knn_df.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {knn_df[column].dtype}")
    print(f"유니크한 값:")
    print(knn_df[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
['2013-12-18 00:00:00', '2013-11-15 00:00:00', '2013-11-11 00:00:00',
 '2013-10-24 00:00:00', '2013-09-11 00:00:00', '2013-10-08 00:00:00',
 '2013-09-15 00:00:00', '2013-10-07 00:00:00', '2013-09-25 00:00:00',
 '2013-10-04 00:00:00',
 ...
 '2022-08-29 00:00:00', '2022-03-21 00:00:00', '2022-01-27 00:00:00',
 '2022-05-02 00:00:00', '2022-02-23 00:00:00', '2022-11-13 00:00:00',
 '2022-12-06 00:00:00', '2022-05-05 00:00:00', '2022-07-09 00:00:00',
 '2022-06-19 00:00:00']
Length: 3591, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: mulg
데이터 타입: int64
유니크한 값:
[1 2 3 4]
----------------------------------------
칼럼 이름: bir1
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bir2
데이터 타입: float64
유니크한 값:
[0. 2.]
----------------------------------------
칼럼 이름: bir3
데이터 타입: float64
유니크한 값:
[0. 3.]
----------------------------------------
칼럼 이름: bir4
데이터 타입: float64
유니크한 값:
[0. 4.]
----------------------------------------
칼럼 이름: prep
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: dm
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: htn
데이터 타입: int64
유니크한 값:
[2 1 3]
----------------------------------------
칼럼 이름: chor
데이터 타입: int64
유니크한 값:
[3 2 1]
----------------------------------------
칼럼 이름: prom
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: ster
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: delm
데이터 타입: int64
유니크한 값:
[2 1]
----------------------------------------
칼럼 이름: atbyn
데이터 타입: float64
유니크한 값:
[3. 2. 1.]
----------------------------------------
칼럼 이름: amni
데이터 타입: int64
유니크한 값:
[1 2 4 3]
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: bpia
데이터 타입: int64
유니크한 값:
[1 2 3]
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: gagew
데이터 타입: int64
유니크한 값:
[30 26 29 27 33 32 31 28 34 35 25 23 24 22 36 21 37 38]
----------------------------------------
칼럼 이름: gaged
데이터 타입: int64
유니크한 값:
[4 0 2 5 3 1 6]
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.  5.  6.  3.  7.  1.  9.  8.  2. nan  0. 10.]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.  6.  7.  8.  4.  9.  1.  3. 10.  2. nan  0.]
----------------------------------------
칼럼 이름: resu
데이터 타입: int64
유니크한 값:
[2 1 3]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.  34.3 36.  42.  38.5 32.  40.5 34.  38.  41.  35.5 35.  29.5 40.
 31.  41.5 37.  36.5 39.5 30.  24.5 33.  30.5 36.2 33.5 25.5  nan 38.8
 37.8 34.7 37.1 27.  34.5 39.2 42.5 35.2 35.6 40.7 37.5 28.6 43.  28.
 29.  26.  31.5 32.5 31.8 43.5 37.2 28.5 27.5 38.4 36.3 35.1 40.8 33.6
 32.7 45.  23.  32.8 39.3 32.3 41.2 44.  25.  38.2 36.4 28.2 36.8 34.2
 39.4 41.3 33.7 35.8 31.4 48.  30.8 42.2 41.4 37.6 38.3 29.7 33.8 30.4
 36.6 46.  37.3 41.7 22.  42.8 40.3 38.1 31.2 25.7 24.  38.7 23.5 41.1
 34.8 39.8 27.8 32.1 35.3 31.7 40.2 30.2 37.7 40.6 26.5 45.5 34.4 28.8
 39.7 44.5 46.5 44.3 47.  35.4 42.3 27.1 33.2 22.2 30.6 34.6 47.7 37.4
 26.1 33.3 31.9 41.8 36.1 31.3 40.9 30.3 34.1 38.6 19.5 20.  29.2 32.4
 28.3 27.2 29.3 40.4 36.7 37.9 27.3 35.7 44.8 39.6 32.6 32.2 41.9 33.4
 42.6 38.9 25.3 34.9 29.4 49.  42.4 43.6 21.  32.9 39.9 29.8 21.5 33.9
 36.9 31.6 29.9 30.7 41.6 24.2 29.1 22.5 20.3 43.2 39.1 33.1 23.3 42.9
 42.7 26.6 42.1 40.1 43.8]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.  23.  28.5 26.5 29.5 28.3 24.5 30.  25.  29.  24.  27.5 30.5 27.
 25.5 31.  23.5 36.  22.5 32.  22.  21.  26.  19.  21.5 22.3 25.7 20.5
  nan 27.3 29.1 23.3 28.4 25.6 29.2 25.4 22.6 25.3 28.2 26.8 27.2 20.
 27.4 30.3 24.2 23.2 20.9 29.3 18.5 24.7 25.8 23.9 26.1 24.8 22.2 21.3
 23.1 24.3 31.5 20.7 26.2 19.5 23.6 21.6 27.7 26.6 27.6 26.4 34.2 31.3
 22.8 20.2 35.5 28.8 25.2 29.4 19.8 27.8 26.3 23.8 21.8 23.7 28.6 29.7
 28.7 26.7 28.1 30.2 24.6 20.3 23.4 27.1 24.4 33.5 22.7 27.9 21.4 29.8
 24.1 20.6 19.7 28.9 32.5 22.9 21.7 24.9 29.9 25.1 18.  33.  21.2 20.8
 22.4 25.9 17.5 38.  21.9 30.4 18.7 30.1 34.  31.2 20.1 26.9 29.6 19.3
 19.4 18.3 17.  30.7 20.4 19.9 32.7 19.2 19.6 22.1 18.6 21.1 34.5 16.
 30.6 35.  14.5 31.6 32.6 37.2 18.8 30.8]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4 36.5 36.6 37.  35.6 36.8 36.7 36.2 34.7 35.3 36.1 36.  36.3 35.4
 35.9 35.7 35.  35.5 38.   nan 35.8 34.8 35.2 35.1 34.5 37.1 34.  36.9
 37.6 33.  37.2 33.8 34.3 34.4 37.4 37.5 34.9 34.6 34.2 34.1 33.4 37.3
 33.5 33.1 33.6 33.2 32.7 33.7 33.9 32.3 37.9 37.8 37.7 32.1 38.2 33.3
 32.4 32.5 32.6 32.9 32.2 38.4 31.9 38.1 32.  38.8 32.8 31.3 38.3 38.7
 38.5 38.6 31. ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35 7.28 7.42 7.49 7.36 7.3  7.21 7.1  7.44 7.31 7.46 7.33 7.24 7.18
 7.4  7.48 7.29 7.53 7.34 7.23 7.25 7.2  7.06 7.02 7.04 7.11 7.41 7.43
  nan 7.26 7.32 7.39 7.19 7.27 7.09 7.13 6.82 6.98 7.16 7.38 6.88 7.08
 7.22 6.97 7.45 7.37 7.17 7.05 7.52 7.14 7.01 7.5  7.07 7.47 7.03 7.15
 6.9  6.99 7.12 7.57 6.7  6.64 6.8  7.   6.87 7.55 6.74 7.51 6.66 6.89
 6.96 6.86 6.84 6.95 7.54 6.92 6.76 6.5  7.58 6.54 6.91 6.93 6.71 6.94
 6.77 7.65 6.83 7.59 6.75 6.85 6.81 7.56 7.72 6.65 6.56 6.63 7.63 6.57
 6.67 6.55 7.68 6.73 7.69 7.6  6.79 7.66 6.68 6.69 7.62 6.17 6.61 6.51
 6.78 6.59 6.72]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: als
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: mph
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: ph
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: sft
데이터 타입: int64
유니크한 값:
[2 1]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: strdu
데이터 타입: int64
유니크한 값:
[1 2]
----------------------------------------
칼럼 이름: oxyt28
데이터 타입: int64
유니크한 값:
[1 3 2 4]
----------------------------------------
칼럼 이름: arre28
데이터 타입: float64
유니크한 값:
[0. 6. 7.]
----------------------------------------
칼럼 이름: oxyt36
데이터 타입: float64
유니크한 값:
[1. 2. 3.]
----------------------------------------
칼럼 이름: arre36
데이터 타입: float64
유니크한 값:
[0. 6. 7.]
----------------------------------------
칼럼 이름: date362
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
[                'NaT', '2021-12-21 00:00:00', '2022-01-03 00:00:00',
 '2022-01-06 00:00:00', '2022-01-26 00:00:00', '2022-01-14 00:00:00',
 '2022-01-29 00:00:00', '2021-12-13 00:00:00', '2021-12-24 00:00:00',
 '2021-04-30 00:00:00',
 ...
 '2022-03-15 00:00:00', '2022-09-21 00:00:00', '2022-11-15 00:00:00',
 '2023-02-11 00:00:00', '2023-02-23 00:00:00', '2023-02-20 00:00:00',
 '2023-03-04 00:00:00', '2022-09-30 00:00:00', '2023-02-01 00:00:00',
 '2022-09-26 00:00:00']
Length: 504, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: date36
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
['2014-01-25 00:00:00', '2014-01-24 00:00:00', '2014-01-01 00:00:00',
 '2014-01-11 00:00:00', '2013-11-10 00:00:00', '2013-10-09 00:00:00',
 '2013-12-15 00:00:00', '2013-10-15 00:00:00', '2013-11-15 00:00:00',
 '2013-11-17 00:00:00',
 ...
 '2021-11-15 00:00:00', '2021-04-12 00:00:00', '2021-05-12 00:00:00',
 '2021-08-11 00:00:00', '2022-01-04 00:00:00', '2021-12-03 00:00:00',
 '2021-11-22 00:00:00', '2022-01-22 00:00:00', '2021-09-05 00:00:00',
 '2022-10-12 00:00:00']
Length: 3206, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: death36
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bdp
데이터 타입: int64
유니크한 값:
[1 3 2 4 5]
----------------------------------------
칼럼 이름: iarvppd
데이터 타입: int64
유니크한 값:
[ 11  45   4  13  10   2  78  38  15  41  68   1   0  50  58   3   5   6
  12  47  25  76 119  73   7  33  39  19  48  24  37  21  65   8  16  36
  90   9  54 120  53  35  27  59  18  43  62  22  77  44  26 220  30  29
  55  14 110  51  23  64  34 115  61  40  81  17  52  46  71  42  28  87
  32 111 134  95  20  66 109 351  70  60  72  93  86  31  74  56  82 215
  69  85 103 124 127 145  63 102 141 113 100 172  88 147  57 105 142  80
  49  96  79 229 114  67 354  89 138 247 150  75 365 148 143  99  97 154
  84 107  92 175 187 106 133 101 108 235 228 112 122 139 166 204 155  98
 104 121 299 144  91 310 324 221 218 131 165 261 240 159 285 222 162 183
 130 132 126 213 193 210 205 326 158 314 136 225 342  83  94 196 177 156
 137 160 168 152 226 153 198 280 163 178 149 190 151 118 135 184 169 289
 232 290 334 246 117 252 359 116 358 363 179 123 216 125 214 173 180 181
 167 315 347 248 146 192 161 186 291]
----------------------------------------
칼럼 이름: niarvrpd
데이터 타입: int64
유니크한 값:
[  2  21   9   5  19   4   1   6   7  12   0  14  10   3  18  16   8  24
  15  20  26  50  34  28  56  22  32  36  13  27  40  45  38  30  29  39
  11  31  17 100  33  90  23  53  37  94  66  25  98  42  63  65  48  58
 202  59  35  47  41  52  57  49  44  51  54  43  69  62  78  81  46  71
  88  60  68  67  83 103  64  55  61 111  74  72  80  79  89 249 117  95
  70  77  97  87  93 160  92 104 167  73  84  82  75  76  99 127 298  86
 118 131 302 154 151 145 115 112 192 101 212 134 128 133 124 125  91 139
 105 181 132  85 114 140 143 123 164 102 108 144 183 107 186 182 120  96
 153 207 225 136 155 169 180 159 116 106 113 141 162 137 135 109 110 147
 146 264 126 122 165]
----------------------------------------
칼럼 이름: aoxyuppd
데이터 타입: float64
유니크한 값:
[  5.  10.   8.   4.   7.  14.   6.  12.  16.  21.  24.   3.  35.  19.
  11.   9.  13.  25.  15.  54.  20.   0.   2.   1.  40.  17.  18.  28.
  31.  32.  48.  42.  29.  36.  26.  52.  37.  23.  34.  22.  41.  49.
  58.  45.  61.  27.  33.  39.  30.  96.  56.  50.  43.  57.  51.  90.
  63.  55.  70.  38.  46.  53.  65.  94.  76.  59.  66.  72.  75.  71.
  44.  78.  47.  81. 204. 109. 146.  64.  74. 101.  77.  73.  62.  80.
  60.  69.  88.  67. 135.  86.  68.  87.  79. 110. 132. 103.  92. 158.
  93. 178.  89.  84. 119.  95. 113.  83. 111. 118. 129. 133. 104. 102.
  85.]
----------------------------------------
칼럼 이름: niarvhfnc
데이터 타입: float64
유니크한 값:

In [23]:
knn_df.to_csv(os.path.join(crt_path, "knn_prep01_M07-Rev.csv"), encoding='utf-8-sig')

In [24]:
dfc = knn_df.copy()

In [25]:
dfc

,sex_sys_val,birthdt,mulg,bir1,bir2,bir3,bir4,prep,dm,htn,...,SEPS_aft_IPERRorNTET,NTET_day,IPERR_day,EFYN_day,death_CR,death_NL,death_Inf,death_GI,death_CA,death_Otr
0,1,2013-12-18,1,0.0,0.0,0.0,0.0,1,1,2,...,0,NaN,NaN,10.0,0,0,0,0,0,0
1,1,2013-11-15,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,30.0,0,0,0,0,0,0
2,1,2013-11-15,2,1.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,14.0,0,0,0,0,0,0
3,1,2013-11-15,2,0.0,2.0,0.0,0.0,1,1,1,...,0,NaN,NaN,NaN,0,0,0,0,0,0
4,1,2013-11-11,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,31.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,27.0,0,0,0,0,0,0
20409,1,2022-12-27,1,0.0,0.0,0.0,0.0,1,1,1,...,0,NaN,NaN,34.0,0,0,0,0,0,0
20410,2,2022-12-01,1,0.0,0.0,0.0,0.0,2,1,1,...,0,NaN,NaN,5.0,0,0,0,0,0,0
20411,1,2022-11-30,2,0.0,2.0,0.0,0.0,2,2,1,...,0,NaN,NaN,9.0,0,0,0,0,0,0
20412,1,2022-11-30,2,1.0,0.0,0.0,0.0,2,2,1,...,0,NaN,NaN,7.0,0,0,0,0,0,0

In [26]:
## 값 수정
dfc['sex_sys_val'] = dfc['sex_sys_val'].replace({2: 0})
dfc['bir2'] = dfc['bir2'].replace({2: 1})
dfc['bir3'] = dfc['bir3'].replace({3: 1})
dfc['bir4'] = dfc['bir4'].replace({4: 1})
# dfc['sterd2'] = dfc['sterd2'].replace({2: 1})
# dfc['sterd4'] = dfc['sterd4'].replace({4: 1})
# dfc['phud2'] = dfc['phud2'].replace({2: 1})
# dfc['phud3'] = dfc['phud3'].replace({3: 1})
# dfc['phud4'] = dfc['phud4'].replace({4: 1})
# dfc['phud5'] = dfc['phud5'].replace({5: 1})
# dfc['phud6'] = dfc['phud6'].replace({6: 1})
# dfc['strdut2'] = dfc['strdut2'].replace({2: 1})
# dfc['strdud2'] = dfc['strdud2'].replace({2: 1})
# dfc['strdud3'] = dfc['strdud3'].replace({3: 1})
# dfc['strdud4'] = dfc['strdud4'].replace({4: 1})
# dfc['paddr2'] = dfc['paddr2'].replace({2: 1})
# dfc['lbpd2'] = dfc['lbpd2'].replace({2: 1})
# dfc['lbpd3'] = dfc['lbpd3'].replace({3: 1})


# mcou, fcou 정확한 값이 아님
# dfc['mcou'] = dfc['mcou'].replace({1: "ROK"
#                                    , 2: "Vietnam"
#                                    , 3: "China"
#                                    , 4: "Philippines"
#                                    , 5: "Japan"
#                                    , 6: "Cambodia"
#                                    , 7: "USA"
#                                    , 8: "Thailand"
#                                    , 9: "Mongolia"
#                                    , 10: "Etc"})


## Unknown을 포함하는 칼럼 Binary화
columns_to_process = ['ph'
#                      , 'sterp', 'resuo', 'resup', 'resui', 'resuh', 'resue', 'resuc', 'rds'
#                      , 'strdut2', 'lbp'
                     ]
for col in columns_to_process:
    if col in dfc.columns:
        dfc[col] = dfc[col].replace({1: 0, 2: 1, 3: 'Unknown'})
        # 값 1에 대한 Binary 컬럼 생성
        dfc[f'{col}_1'] = (dfc[col] == 1).astype(int)
        # 값 'Unknown'에 대해 확인 후 Binary 컬럼 생성
        if 'Unknown' in dfc[col].values:
            dfc[f'{col}_Unknown'] = (dfc[col] == 'Unknown').astype(int)
        else:
            print(f"Value 'Unknown' not found in column '{col}'. Skipping creation of {col}_Unknown.")
        dfc.drop(columns=[col], inplace=True)


# 0 & 1 or+ 3 (Unknown) Binarise
columns_to_process = ['lbp', 'chor', 'ster', 'atbyn', 'resu', 'als', 'mph', 'sft', 'strdu'
                      , 'nese', 'ibif', 'meni', 'prom', 'ntet', 'eythtran'
                     ]
for col in columns_to_process:
    if col in dfc.columns:
        dfc[col] = dfc[col].replace({1: 0, 2: 1})
        has_3 = 3 in dfc[col].values
        dfc[f'{col}_1'] = (dfc[col] == 1).astype(int)
        dfc[f'{col}_0'] = (dfc[col] == 0).astype(int)
        if has_3:
            dfc[f'{col}_Unknown'] = (dfc[col] == 3).astype(int)
            print(f"Value '3' found in column '{col}'. Created '{col}_Unknown' column.")

        dfc.drop(columns=[col], inplace=True)


## cols for Binarise
# dfc['promn'] = dfc['promn'].replace({0: np.nan})
# dfc['sftup'] = dfc['sftup'].replace({0: np.nan})
# dfc['sftur'] = dfc['sftur'].replace({0: np.nan})
# dfc['sftth'] = dfc['sftth'].replace({0: np.nan})
# dfc['pdad'] = dfc['pdad'].replace({0: np.nan})
# dfc['pdadty'] = dfc['pdadty'].replace({0: np.nan})
# dfc['bsffs1'] = dfc['bsffs1'].replace({0: np.nan})
# dfc['bsffs2'] = dfc['bsffs2'].replace({0: np.nan})
# dfc['bsffs3'] = dfc['bsffs3'].replace({0: np.nan})
# dfc['fsffs1'] = dfc['fsffs1'].replace({0: np.nan})
# dfc['fsffs2'] = dfc['fsffs2'].replace({0: np.nan})
# dfc['menifs'] = dfc['menifs'].replace({0: np.nan})
dfc['ntetoy'] = dfc['ntetoy'].replace({0: np.nan})


# 'pmirnsg'
dfc['pmirnsg_0'] = dfc['pmirnsg'].isin([0]).astype(int)
dfc['pmirnsg_1+'] = dfc['pmirnsg'].isin([1, 2, 3, 4, 5]).astype(int)
print(dfc[['pmirnsg', 'pmirnsg_0', 'pmirnsg_1+']])
dfc.drop('pmirnsg', axis=1, inplace=True)

# 'pmirnsgnd'
dfc['pmirnsgnd'] = dfc.get('pmirnsgnd', 0).fillna(0).astype(int)

# 'efyn'
dfc['efyn_1'] = dfc['efyn'].isin([2]).astype(int)
print(dfc[['efyn', 'efyn_1']])
dfc.drop('efyn', axis=1, inplace=True)
dfc.rename(columns={'efyn_1': 'efyn'}, inplace=True)


## 'inhg'
dfc['inhg_0'] = dfc['inhg'].isin([1]).astype(int)
dfc['inhg_1'] = dfc['inhg'].isin([2, 3, 4, 5]).astype(int)
dfc['inhg_2+'] = dfc['inhg'].isin([3, 4, 5]).astype(int)
dfc['inhg_3+'] = dfc['inhg'].isin([4, 5]).astype(int)

dfc['ivh_0'] = dfc['inhg'].isin([1]).astype(int)
dfc['ivh_1'] = dfc['inhg'].isin([2]).astype(int)
dfc['ivh_2'] = dfc['inhg'].isin([3]).astype(int)
dfc['ivh_3'] = dfc['inhg'].isin([4]).astype(int)
dfc['ivh_4'] = dfc['inhg'].isin([5]).astype(int)
print(dfc[['inhg', 'inhg_1', 'inhg_2+', 'inhg_3+'
           , 'ivh_0', 'ivh_1', 'ivh_2', 'ivh_3', 'ivh_4']]
     )
dfc.drop('inhg', axis=1, inplace=True)

## 'bdp'
dfc['bdp_'] = dfc['bdp'].isin([2, 3, 4]).astype(int)
dfc['bdp_Moderate+'] = dfc['bdp'].isin([3, 4]).astype(int)
dfc.drop('bdp', axis=1, inplace=True)
dfc.rename(columns={'bdp_': 'bdp'}, inplace=True)
print(dfc[['bdp', 'bdp_Moderate+']])

## 'gagew', 'gaged'
dfc['ga'] = dfc['gagew'] + (dfc['gaged'] / 7)
dfc['ga'] = dfc['ga'].round(4)
print(dfc[['gagew', 'gaged', 'ga']])
dfc.drop(['gagew', 'gaged'], axis=1, inplace=True)

## 'mulg'
dfc['mulg_singleton'] = dfc['mulg'].isin([1]).astype(int)
dfc['mulg_multiple'] = dfc['mulg'].isin([2, 3, 4]).astype(int)
print(dfc[['mulg', 'mulg_singleton', 'mulg_multiple']])
dfc.drop('mulg', axis=1, inplace=True)

## 'dm'
dfc['dm_0'] = dfc['dm'].isin([1]).astype(int)
dfc['dm_1'] = dfc['dm'].isin([2, 3]).astype(int)
print(dfc[['dm', 'dm_0', 'dm_1']])
dfc.drop('dm', axis=1, inplace=True)

# 'delm'
dfc['delm_1'] = dfc['delm'].isin([1]).astype(int)
dfc['delm_2'] = dfc['delm'].isin([2]).astype(int)
print(dfc[['delm', 'delm_1', 'delm_2']])
dfc.drop('delm', axis=1, inplace=True)

## dth36dt : 출생일 + 교정(환산) 일수 = 교정 36주가 되는 날짜 계산
# dfc['dth36dt'] = dfc.apply(
#     lambda row: row['birthdt'] + pd.Timedelta((36 - row['ga']) * 7, unit='days')
#     , axis=1)
# print(dfc[['birthdt', 'ga', 'dth36dt']])

columns_to_process = ['prep', 'htn', 'amni', 'bpia'
                      , 'sftup', 'sftur', 'sftth', 'oxyt28', 'arre28', 'oxyt36', 'arre36'
                      , 'pvl', 'seps'
                      , 'ntety', 'ntetoy', 'iperr', 'iperroy'
#                      , 'pdad', 'pdadty', 'pdatr', 'acl'
#                      , 'bsffs1', 'bsffs2', 'bsffs3', 'fsffs1', 'fsffs2'
#                      , 'menifs'
#                      , 'mcou', 'fcou'    # >> 정확한 값이 아님.
                     ]

for col in columns_to_process:
    if col in dfc.columns:
        # 고유값을 기반으로 이진 컬럼 생성
        unique_values = dfc[col].dropna().unique()
        for value in unique_values:
            dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
        # 생성된 컬럼 이름 출력
        cols = [new_col for new_col in dfc.columns if new_col.startswith(col)]
        print(f"Generated columns for '{col}': {cols}")
        # 원래 칼럼 삭제
        dfc.drop(columns=[col], inplace=True)

dfc



# # 'chor' : 1, 'Unknown'을 기준으로 Binary 화
# dfc['chor'] = dfc['chor'].replace({1:0, 2:1, 3: 'Unknown'})
# if 'chor' in dfc.columns:
#     # chor_1: 값이 1인 경우 1, 그 외는 0
#     dfc['chor_1'] = (dfc['chor'] == 1).astype(int)
#     # chor_unknown: 값이 'Unknown'인 경우 1, 그 외는 0
#     dfc['chor_Unknown'] = (dfc['chor'] == 'Unknown').astype(int)
# print(dfc[['chor', 'chor_1', 'chor_Unknown']])
# dfc.drop(columns=['chor'], inplace=True)

Value 'Unknown' not found in column 'ph'. Skipping creation of ph_Unknown.
Value '3' found in column 'chor'. Created 'chor_Unknown' column.
Value '3' found in column 'ster'. Created 'ster_Unknown' column.
Value '3' found in column 'atbyn'. Created 'atbyn_Unknown' column.
Value '3' found in column 'resu'. Created 'resu_Unknown' column.
Value '3' found in column 'prom'. Created 'prom_Unknown' column.
Value '3' found in column 'ntet'. Created 'ntet_Unknown' column.
       pmirnsg  pmirnsg_0  pmirnsg_1+
0          0.0          1           0
1          2.0          0           1
2          0.0          1           0
3          0.0          1           0
4          1.0          0           1
...        ...        ...         ...
20408      0.0          1           0
20409      2.0          0           1
20410      0.0          1           0
20411      0.0          1           0
20412      0.0          1           0

[20352 rows x 3 columns]
       efyn  efyn_1
0         2       1
1         2       1
2         2       1
3         1       0
4         2       1
...     ...     ...
20408     2       1
20409     2       1
20410     2       1
20411     2       1
20412     2       1

[20352 rows x 2 columns]
       inhg  inhg_1  inhg_2+  inhg_3+  ivh_0  ivh_1  ivh_2  ivh_3  ivh_4
0         2       1        0        0      0      1      0      0      0
1         2       1        0        0      0      1      0      0      0
2         2       1        0        0      0      1      0      0      0
3         3       1        1        0      0      0      1      0      0
4         2       1        0        0      0      1      0      0      0
...     ...     ...      ...      ...    ...    ...    ...    ...    ...
20408     2       1        0        0      0      1      0      0      0
20409     5       1        1        1      0      0      0      0      1
20410     2       1        0        0      0      1      0      0      0
20411     1       0        0        0      1      0      0      0      0
20412     1       0        0        0      1      0      0      0      0

[20352 rows x 9 columns]
       bdp  bdp_Moderate+
0        0              0
1        1              1
2        0              0
3        0              0
4        1              0
...    ...            ...
20408    0              0
20409    1              0
20410    1              1
20411    0              0
20412    0              0

[20352 rows x 2 columns]
       gagew  gaged       ga
0         30      4  30.5714
1         26      0  26.0000
2         29      2  29.2857
3         29      2  29.2857
4         27      2  27.2857
...      ...    ...      ...
20408     29      4  29.5714
20409     25      5  25.7143
20410     31      3  31.4286
20411     31      1  31.1429
20412     31      1  31.1429

[20352 rows x 3 columns]
       mulg  mulg_singleton  mulg_multiple
0         1               1              0
1         1               1              0
2         2               0              1
3         2               0              1
4         1               1              0
...     ...             ...            ...
20408     1               1              0
20409     1               1              0
20410     1               1              0
20411     2               0              1
20412     2               0              1

[20352 rows x 3 columns]
       dm  dm_0  dm_1
0       1     1     0
1       1     1     0
2       1     1     0
3       1     1     0
4       1     1     0
...    ..   ...   ...
20408   1     1     0
20409   1     1     0
20410   1     1     0
20411   2     0     1
20412   2     0     1

[20352 rows x 3 columns]
       delm  delm_1  delm_2
0         2       0       1
1         2       0       1
2         2       0       1
3         2       0       1
4         2       0       1
...     ...     ...     ...
20408     1       1       0
20409     2       0       1
20410     1       1       0
20411     2       0       1
20412     2       0       1

[20352 rows x 3 columns]
Generated columns for 'prep': ['prep', 'prep_1', 'prep_2']
Generated columns for 'htn': ['htn', 'htn_2', 'htn_1', 'htn_3']
Generated columns for 'amni': ['amni', 'amni_1', 'amni_2', 'amni_4', 'amni_3']
Generated columns for 'bpia': ['bpia', 'bpia_1', 'bpia_2', 'bpia_3']
Generated columns for 'oxyt28': ['oxyt28', 'oxyt28_1', 'oxyt28_3', 'oxyt28_2', 'oxyt28_4']
Generated columns for 'arre28': ['arre28', 'arre28_0', 'arre28_6', 'arre28_7']
Generated columns for 'oxyt36': ['oxyt36', 'oxyt36_1', 'oxyt36_2', 'oxyt36_3']
Generated columns for 'arre36': ['arre36', 'arre36_0', 'arre36_6', 'arre36_7']
Generated columns for 'pvl': ['pvl', 'pvl_1', 'pvl_3', 'pvl_2']
Generated columns for 'seps': ['seps', 'seps_1', 'seps_2', 'seps_3']
Generated columns for 'ntety': ['ntety', 'ntety_1', 'ntety_2', 'ntety_3', 'ntety_4']
Generated columns for 'ntetoy': ['ntetoy', 'ntetoy_2', 'ntetoy_3', 'ntetoy_1']
Generated columns for 'iperr': ['iperr', 'iperroy', 'iperrdt', 'iperr_1', 'iperr_2', 'iperr_3', 'iperr_4']
Generated columns for 'iperroy': ['iperroy', 'iperroy_1', 'iperroy_4', 'iperroy_3', 'iperroy_2']

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37432\2756643273.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dfc[f'{col}_{int(value)}'] = (dfc[col] == value).astype(int)

,sex_sys_val,birthdt,bir1,bir2,bir3,bir4,bird,admd,apgs1,apgs5,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,0.0,0.0,0.0,0.0,2013-12-18,2013-12-18,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,0.0,0.0,0.0,0.0,2013-11-15,2013-11-15,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,1.0,0.0,0.0,0.0,2013-11-15,2013-11-15,5.0,6.0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,0.0,1.0,0.0,0.0,2013-11-15,2013-11-15,6.0,7.0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,0.0,0.0,0.0,0.0,2013-11-11,2013-11-11,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,0.0,0.0,0.0,0.0,2022-11-28,2022-11-28,5.0,8.0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,0.0,0.0,0.0,0.0,2022-12-27,2022-12-27,4.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,0.0,0.0,0.0,0.0,2022-12-01,2022-12-01,5.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,0.0,1.0,0.0,0.0,2022-11-30,2022-11-30,3.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,1.0,0.0,0.0,0.0,2022-11-30,2022-11-30,4.0,6.0,...,0,0,1,0,0,0,1,0,0,0

In [28]:
analyse_dataframe(dfc)

                      NaN Counts  NaN Ratios (%)  Unique Values Count
sex_sys_val                    0        0.000000                    2
birthdt                        0        0.000000                 3591
bir1                           0        0.000000                    2
bir2                           0        0.000000                    2
bir3                           0        0.000000                    2
bir4                           0        0.000000                    2
bird                           0        0.000000                 3591
admd                           0        0.000000                 3592
apgs1                        121        0.594536                   11
apgs5                        117        0.574882                   11
bwei                           0        0.000000                  902
mage                           0        0.000000                   40
gran                           0        0.000000                   16
parn                           0        0.000000                   10
bhei                        1137        5.586675                  186
bheiuk                         0        0.000000                    2
bhead                       1230        6.043632                  147
bheaduk                        0        0.000000                    2
btem                         631        3.100432                   72
btemuk                         0        0.000000                    2
bbph                        4597       22.587461                  114
bbphuk                         0        0.000000                    2
bbbe                           0        0.000000                  327
bbbeuk                         0        0.000000                    2
sftun                          0        0.000000                    9
date362                    18196       89.406447                  503
date36                      5024       24.685535                 3205
death36                        0        0.000000                    2
iarvppd                        0        0.000000                  225
niarvrpd                       0        0.000000                  167
aoxyuppd                       0        0.000000                  113
niarvhfnc                      0        0.000000                  111
pdaddt                     14194       69.742531                 2800
pdaddth                    14655       72.007665                   25
menidt                     20253       99.513561                   98
invfpod                        0        0.000000                  222
ntetdt                     19385       95.248624                  802
ntetdty                    19837       97.469536                  473
iperrdt                    19995       98.245873                  326
pmirnsgnd                      0        0.000000                    2
efydt                       2527       12.416470                 3615
stday                          0        0.000000                  313
birtm                          0        0.000000                 1439
pda_non-treatment              0        0.000000                    2
pda_unknown                    0        0.000000                    2
PDA_TRD                        0        0.000000                    2
PPHN                           0        0.000000                    2
PDA_7d_NTET                    0        0.000000                    2
PDA_7d_IPERR                   0        0.000000                    2
7d_PDA                         0        0.000000                    2
PDA_7d_IPERRorNTET             0        0.000000                    2
death_label                    0        0.000000                    2
death_dt                   17761       87.269064                 1790
SEPS_bef_NTET                  0        0.000000                    2
SEPS_aft_NTET                  0        0.000000                    2
SEPS_bef_IPERR                 0        0.000000                    2
SEPS_aft_IPERR                 0        0.000000                    2
SEPS_bef_IPERRorNTET           0        0.000000                    2
SEPS_aft_IPERRorNTET           0        0.000000                    2
NTET_day                   19385       95.248624                   79
IPERR_day                  19997       98.255700                   55
EFYN_day                    2527       12.416470                  169
death_CR                       0        0.000000                    2
death_NL                       0        0.000000                    2
death_Inf                      0        0.000000                    2
death_GI                       0        0.000000                    2
death_CA                       0        0.000000                    2
death_Otr                      0        0.000000                    2
ph_1                           0        0.000000                    2
lbp_1                          0        0.000000                    2
lbp_0                          0        0.000000                    2
chor_1                         0        0.000000                    2
chor_0                         0        0.000000                    2
chor_Unknown                   0        0.000000                    2
ster_1                         0        0.000000                    2
ster_0                         0        0.000000                    2
ster_Unknown                   0        0.000000                    2
atbyn_1                        0        0.000000                    2
atbyn_0                        0        0.000000                    2
atbyn_Unknown                  0        0.000000                    2
resu_1                         0        0.000000                    2
resu_0                         0        0.000000                    2
resu_Unknown                   0        0.000000                    2
als_1                          0        0.000000                    2
als_0                          0        0.000000                    2
mph_1                          0        0.000000                    2
mph_0                          0        0.000000                    2
sft_1                          0        0.000000                    2
sft_0                          0        0.000000                    2
strdu_1                        0        0.000000                    2
strdu_0                        0        0.000000                    2
nese_1                         0        0.000000                    2
nese_0                         0        0.000000                    2
ibif_1                         0        0.000000                    2
ibif_0                         0        0.000000                    2
meni_1                         0        0.000000                    2
meni_0                         0        0.000000                    2
prom_1                         0        0.000000                    2
prom_0                         0        0.000000                    2
prom_Unknown                   0        0.000000                    2
ntet_1                         0        0.000000                    2
ntet_0                         0        0.000000                    2
ntet_Unknown                   0        0.000000                    2
eythtran_1                     0        0.000000                    2
eythtran_0                     0        0.000000                    2
pmirnsg_0                      0        0.000000                    2
pmirnsg_1+                     0        0.000000                    2
efyn                           0        0.000000                    2
inhg_0                         0        0.000000                    2
inhg_1                         0        0.000000                    2
inhg_2+                        0        0.000000                    2
inhg_3+                        0        0.000000                    2
ivh_0                          0        0.000000                    2
ivh_1                          0        0.000000                    2
ivh_2                          0        0.000000                    2
ivh_3                          0        0.000000                    2
ivh_4                          0        0.000000                    2
bdp                            0        0.000000                    2
bdp_Moderate+                  0        0.000000                    2
ga                             0        0.000000                  122
mulg_singleton                 0        0.000000                    2
mulg_multiple                  0        0.000000                    2
dm_0                           0        0.000000                    2
dm_1                           0        0.000000                    2
delm_1                         0        0.000000                    2
delm_2                         0        0.000000                    2
prep_1                         0        0.000000                    2
prep_2                         0        0.000000                    2
htn_2                          0        0.000000                    2
htn_1                          0        0.000000                    2
htn_3                          0        0.000000                    2
amni_1                         0        0.000000                    2
amni_2                         0        0.000000                    2
amni_4                         0        0.000000                    2
amni_3                         0        0.000000                    2
bpia_1                         0        0.000000                    2
bpia_2                         0        0.000000                    2
bpia_3                         0        0.000000                    2
oxyt28_1                       0        0.000000                    2
oxyt28_3                       0        0.000000                    2
oxyt28_2                       0        0.000000                    2
oxyt28_4                       0        0.000000                    2
arre28_0                       0        0.000000                    2
arre28_6                       0        0.000000                    2
arre28_7                       0        0.000000                    2
oxyt36_1                       0        0.000000                    2
oxyt36_2                       0        0.000000                    2
oxyt36_3                       0        0.000000                    2
arre36_0                       0        0.000000                    2
arre36_6                       0        0.000000                    2
arre36_7                       0        0.000000                    2
pvl_1                          0        0.000000                    2
pvl_3                          0        0.000000                    2
pvl_2                          0        0.000000                    2
seps_1                         0        0.000000                    2
seps_2                         0        0.000000                    2
seps_3                         0        0.000000                    2
ntety_1                        0        0.000000                    2
ntety_2                        0        0.000000                    2
ntety_3                        0        0.000000                    2
ntety_4                        0        0.000000                    2
ntetoy_2                       0        0.000000                    2
ntetoy_3                       0        0.000000                    2
ntetoy_1                       0        0.000000                    2
iperr_1                        0        0.000000                    2
iperr_2                        0        0.000000                    2
iperr_3                        0        0.000000                    2
iperr_4                        0        0.000000                    2
iperroy_1                      0        0.000000                    2
iperroy_4                      0        0.000000                    2
iperroy_3                      0        0.000000                    2
iperroy_2                      0        0.000000                    2

In [31]:
df = dfc.copy()

print(len(df.columns), '\n')

# 1) drop_cols
drop_cols = [
    'ga',
    'bir1', 'bir2', 'bir3', 'bir4',
    'death36'
]

datetime_cols = [
    'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt', 'pdaddth', 'pdaddt',
    'birthdt', 'admd', 'birtm', 'bird', 'efydt', 'death_dt', 'iperrdt'
]
drop_cols += datetime_cols

rsndth_cols = ['death_CR', 'death_NL', 'death_Inf', 'death_GI', 'death_CA', 'death_Otr']
drop_cols += rsndth_cols

drop_cols = [c for c in drop_cols if c in df.columns]

print('len(drop_cols): ', len(drop_cols))
print("drop_cols:", drop_cols)

# 2) target_keys -> tgt_cols
target_keys = [
    'ntet_', 'ntety_', 'ntetoy_',
    'SEPS_bef_NTET', 'SEPS_aft_NTET',
    'NTET_day', 'PDA_7d_NTET',
    'invfpod',
    'iperr_', 'iperroy_',
    'SEPS_bef_IPERR', 'SEPS_aft_IPERR',
    'IPERR_day', 'PDA_7d_IPERR', 'PDA_7d_IPERRorNTET',
    'SEPS_bef_IPERRorNTET', 'SEPS_aft_IPERRorNTET',
    '7d_PDA',
    'bdp', 'bdp_Moderate+', 'strdu_',
    'inhg_', 'pvl_', 'nese_',
    'seps_3',
    'pmirnsg_', 'pmirnsgnd',
    'stday',
    'oxyt36_', 'arre36_',
    'bwei',
    'btem', 'bhei', 'bhead',
    'ivh_'
]

tgt_cols = [
    col for col in df.columns
    if col in target_keys or any(col.startswith(prefix) for prefix in target_keys)
]

print('len(tgt_cols): ', len(tgt_cols))
print("tgt_cols:", tgt_cols)

# 3) clustering 포함 여부 계산
excluded_by_rule = set(drop_cols)
excluded_by_target = set(tgt_cols)
excluded_outcome = {'death_label'} if 'death_label' in df.columns else set()

clustering_cols = [
    col for col in df.columns
    if col not in excluded_by_rule
    and col not in excluded_by_target
    and col not in excluded_outcome
]

print('len(clustering_cols): ', len(clustering_cols))
print("clustering_cols:", clustering_cols)

# 4) Full imputation table 생성 (모든 변수 포함)
rows = []

for col in df.columns:
    s = df[col]
    nonmiss = s.dropna()
    nunique = nonmiss.nunique()

    # 값 요약: 범주 수가 적은 경우만 표시
    value_summary = ""
    if nunique <= 10:
        vc = nonmiss.value_counts(dropna=False).sort_index()
        value_summary = ", ".join([f"{k}: {v}" for k, v in vc.items()])

    if col in clustering_cols:
        used_for_clustering = 'Yes'
        reason = 'Included'
    elif col in excluded_outcome:
        used_for_clustering = 'No'
        reason = 'Outcome excluded'
    elif col in excluded_by_target:
        used_for_clustering = 'No'
        reason = 'Target/derived excluded'
    elif col in excluded_by_rule:
        used_for_clustering = 'No'
        reason = 'Dropped by predefined rule'
    else:
        used_for_clustering = 'No'
        reason = 'Not in final feature set'

    rows.append({
        'Variable': col,
        'Missing_n': int(s.isna().sum()),
        'Missing_pct': float(s.isna().mean() * 100),
        'Nonmissing_n': int(s.notna().sum()),
        'dtype': str(s.dtype),
        'Unique_nonmissing_n': int(nunique),
        'Value_summary': value_summary,
        'Used_for_clustering': used_for_clustering,
        'Clustering_flag_reason': reason
    })

full_imputation_table = pd.DataFrame(rows)

# 보기 좋게 정렬
full_imputation_table = full_imputation_table.sort_values(
    by=['Used_for_clustering', 'Missing_pct', 'Missing_n', 'Variable'],
    ascending=[False, False, False, True]
).reset_index(drop=True)

print(full_imputation_table.shape)
full_imputation_table

172

len(drop_cols):  26
drop_cols: ['ga', 'bir1', 'bir2', 'bir3', 'bir4', 'death36', 'ntetdt', 'ntetdty', 'date362', 'date36', 'menidt', 'pdaddth', 'pdaddt', 'birthdt', 'admd', 'birtm', 'bird', 'efydt', 'death_dt', 'iperrdt', 'death_CR', 'death_NL', 'death_Inf', 'death_GI', 'death_CA', 'death_Otr']
len(tgt_cols):  67
tgt_cols: ['bwei', 'bhei', 'bheiuk', 'bhead', 'bheaduk', 'btem', 'btemuk', 'invfpod', 'pmirnsgnd', 'stday', 'PDA_7d_NTET', 'PDA_7d_IPERR', '7d_PDA', 'PDA_7d_IPERRorNTET', 'SEPS_bef_NTET', 'SEPS_aft_NTET', 'SEPS_bef_IPERR', 'SEPS_aft_IPERR', 'SEPS_bef_IPERRorNTET', 'SEPS_aft_IPERRorNTET', 'NTET_day', 'IPERR_day', 'strdu_1', 'strdu_0', 'nese_1', 'nese_0', 'ntet_1', 'ntet_0', 'ntet_Unknown', 'pmirnsg_0', 'pmirnsg_1+', 'inhg_0', 'inhg_1', 'inhg_2+', 'inhg_3+', 'ivh_0', 'ivh_1', 'ivh_2', 'ivh_3', 'ivh_4', 'bdp', 'bdp_Moderate+', 'oxyt36_1', 'oxyt36_2', 'oxyt36_3', 'arre36_0', 'arre36_6', 'arre36_7', 'pvl_1', 'pvl_3', 'pvl_2', 'seps_3', 'ntety_1', 'ntety_2', 'ntety_3', 'ntety_4', 'ntetoy_2', 'ntetoy_3', 'ntetoy_1', 'iperr_1', 'iperr_2', 'iperr_3', 'iperr_4', 'iperroy_1', 'iperroy_4', 'iperroy_3', 'iperroy_2']
len(clustering_cols):  78
clustering_cols: ['sex_sys_val', 'apgs1', 'apgs5', 'mage', 'gran', 'parn', 'bbph', 'bbphuk', 'bbbe', 'bbbeuk', 'sftun', 'iarvppd', 'niarvrpd', 'aoxyuppd', 'niarvhfnc', 'pda_non-treatment', 'pda_unknown', 'PDA_TRD', 'PPHN', 'EFYN_day', 'ph_1', 'lbp_1', 'lbp_0', 'chor_1', 'chor_0', 'chor_Unknown', 'ster_1', 'ster_0', 'ster_Unknown', 'atbyn_1', 'atbyn_0', 'atbyn_Unknown', 'resu_1', 'resu_0', 'resu_Unknown', 'als_1', 'als_0', 'mph_1', 'mph_0', 'sft_1', 'sft_0', 'ibif_1', 'ibif_0', 'meni_1', 'meni_0', 'prom_1', 'prom_0', 'prom_Unknown', 'eythtran_1', 'eythtran_0', 'efyn', 'mulg_singleton', 'mulg_multiple', 'dm_0', 'dm_1', 'delm_1', 'delm_2', 'prep_1', 'prep_2', 'htn_2', 'htn_1', 'htn_3', 'amni_1', 'amni_2', 'amni_4', 'amni_3', 'bpia_1', 'bpia_2', 'bpia_3', 'oxyt28_1', 'oxyt28_3', 'oxyt28_2', 'oxyt28_4', 'arre28_0', 'arre28_6', 'arre28_7', 'seps_1', 'seps_2']
(172, 9)

,Variable,Missing_n,Missing_pct,Nonmissing_n,dtype,Unique_nonmissing_n,Value_summary,Used_for_clustering,Clustering_flag_reason
0,bbph,4597,22.587461,15755,float64,114,,Yes,Included
1,EFYN_day,2527,12.416470,17825,float64,169,,Yes,Included
2,apgs1,121,0.594536,20231,float64,11,,Yes,Included
3,apgs5,117,0.574882,20235,float64,11,,Yes,Included
4,PDA_TRD,0,0.000000,20352,int32,2,"0: 13642, 1: 6710",Yes,Included
...,...,...,...,...,...,...,...,...,...
167,pvl_3,0,0.000000,20352,int32,2,"0: 19618, 1: 734",No,Target/derived excluded
168,seps_3,0,0.000000,20352,int32,2,"0: 20270, 1: 82",No,Target/derived excluded
169,stday,0,0.000000,20352,int64,313,,No,Target/derived excluded
170,strdu_0,0,0.000000,20352,int32,2,"0: 4702, 1: 15650",No,Target/derived excluded
171,strdu_1,0,0.000000,20352,int32,2,"0: 15650, 1: 4702",No,Target/derived excluded

In [32]:
# SAVE :: Full missing table

full_imputation_table.to_csv(
    'full_imputation_table_with_clustering_flag.csv',
    index=True,
    encoding='utf-8-sig'
)

In [ ]:
# 1. Original method (Mean Imp)
dfc_1 = dfc.copy
mean_cols = ['apgs1', 'apgs5', 'btem', 'bbph', 'bhead', 'bhei']
dfc[mean_cols] = knn_df[mean_cols].fillna(knn_df[mean_cols].mean())

In [68]:
analyse_dataframe(dfc)

                   NaN Counts  NaN Ratios (%)  Unique Values Count
sex_sys_val                 0        0.000000                    2
bir1                        0        0.000000                    2
bir2                        0        0.000000                    2
bir3                        0        0.000000                    2
bir4                        0        0.000000                    2
birdh                       0        0.000000                   24
birdm                       0        0.000000                   60
apgs1                     121        0.594536                   11
apguk1                  20231       99.405464                    1
apgs5                     117        0.574882                   11
apguk5                  20235       99.425118                    1
mage                        0        0.000000                   40
gran                        0        0.000000                   16
parn                        0        0.000000                   10
metc                    20209       99.297366                   43
fetc                    20110       98.810928                   50
fetc2                   20312       99.803459                   20
bhtcut                  18368       90.251572                    6
bhdcut                  18375       90.285967                    6
bbph                     4597       22.587461                  114
bbphuk                      0        0.000000                    2
sign                     4715       23.167256                    2
bbbe                        0        0.000000                  327
bbbeuk                      0        0.000000                    2
phudstdt                18428       90.546384                 1472
sftfudt                  4915       24.149961                 3500
sftuh                    5614       27.584513                   24
sftum                    5688       27.948113                   60
sftun                       0        0.000000                    9
sftthdt                 20350       99.990173                    2
strduot                 20282       99.656053                   18
death36                     0        0.000000                    2
iarvppd                     0        0.000000                  225
niarvrpd                    0        0.000000                  167
aoxyuppd                    0        0.000000                  113
niarvhfnc                   0        0.000000                  111
pdatr                       0        0.000000                    6
pdad                        0        0.000000                    3
acl                     10654       52.348664                    3
ibifcmt                 20106       98.791274                  149
bsf1                    16850       82.792846                    1
bsfdt1                  16850       82.792846                 2175
fdcdt                       0        0.000000                 3633
dcd                         0        0.000000                    4
pda_non-treatment           0        0.000000                    2
pda_med-only                0        0.000000                    2
pda_op-only                 0        0.000000                    2
pda_med+op                  0        0.000000                    2
pda_unknown                 0        0.000000                    2
PDA_TRD                     0        0.000000                    2
ph_1                        0        0.000000                    2
lbp_1                       0        0.000000                    2
lbp_0                       0        0.000000                    2
chor_1                      0        0.000000                    2
chor_0                      0        0.000000                    2
chor_Unknown                0        0.000000                    2
ster_1                      0        0.000000                    2
ster_0                      0        0.000000                    2
ster_Unknown                0        0.000000                    2
atbyn_1                     0        0.000000                    2
atbyn_0                     0        0.000000                    2
atbyn_Unknown               0        0.000000                    2
resu_1                      0        0.000000                    2
resu_0                      0        0.000000                    2
resu_Unknown                0        0.000000                    2
als_1                       0        0.000000                    2
als_0                       0        0.000000                    2
mph_1                       0        0.000000                    2
mph_0                       0        0.000000                    2
sft_1                       0        0.000000                    2
sft_0                       0        0.000000                    2
ibif_1                      0        0.000000                    2
ibif_0                      0        0.000000                    2
meni_1                      0        0.000000                    2
meni_0                      0        0.000000                    2
prom_1                      0        0.000000                    2
prom_0                      0        0.000000                    2
prom_Unknown                0        0.000000                    2
eythtran_1                  0        0.000000                    2
eythtran_0                  0        0.000000                    2
efyn                        0        0.000000                    2
ivh_0                       0        0.000000                    2
ivh_1                       0        0.000000                    2
ivh_2                       0        0.000000                    2
ivh_3                       0        0.000000                    2
ivh_4                       0        0.000000                    2
mulg_singleton              0        0.000000                    2
mulg_multiple               0        0.000000                    2
dm_0                        0        0.000000                    2
dm_1                        0        0.000000                    2
delm_1                      0        0.000000                    2
delm_2                      0        0.000000                    2
prep_1                      0        0.000000                    2
prep_2                      0        0.000000                    2
htn_2                       0        0.000000                    2
htn_1                       0        0.000000                    2
htn_3                       0        0.000000                    2
amni_1                      0        0.000000                    2
amni_2                      0        0.000000                    2
amni_4                      0        0.000000                    2
amni_3                      0        0.000000                    2
bpia_1                      0        0.000000                    2
bpia_2                      0        0.000000                    2
bpia_3                      0        0.000000                    2
oxyt28_1                    0        0.000000                    2
oxyt28_3                    0        0.000000                    2
oxyt28_2                    0        0.000000                    2
oxyt28_4                    0        0.000000                    2
arre28_0                    0        0.000000                    2
arre28_6                    0        0.000000                    2
arre28_7                    0        0.000000                    2
seps_1                      0        0.000000                    2
seps_2                      0        0.000000                    2

In [33]:
for column in dfc.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {dfc[column].dtype}")
    print(f"유니크한 값:")
    print(dfc[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 0]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
['2013-12-18 00:00:00', '2013-11-15 00:00:00', '2013-11-11 00:00:00',
 '2013-10-24 00:00:00', '2013-09-11 00:00:00', '2013-10-08 00:00:00',
 '2013-09-15 00:00:00', '2013-10-07 00:00:00', '2013-09-25 00:00:00',
 '2013-10-04 00:00:00',
 ...
 '2022-08-29 00:00:00', '2022-03-21 00:00:00', '2022-01-27 00:00:00',
 '2022-05-02 00:00:00', '2022-02-23 00:00:00', '2022-11-13 00:00:00',
 '2022-12-06 00:00:00', '2022-05-05 00:00:00', '2022-07-09 00:00:00',
 '2022-06-19 00:00:00']
Length: 3591, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: bir1
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bir2
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bir3
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bir4
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.  5.  6.  3.  7.  1.  9.  8.  2. nan  0. 10.]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.  6.  7.  8.  4.  9.  1.  3. 10.  2. nan  0.]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.  34.3 36.  42.  38.5 32.  40.5 34.  38.  41.  35.5 35.  29.5 40.
 31.  41.5 37.  36.5 39.5 30.  24.5 33.  30.5 36.2 33.5 25.5  nan 38.8
 37.8 34.7 37.1 27.  34.5 39.2 42.5 35.2 35.6 40.7 37.5 28.6 43.  28.
 29.  26.  31.5 32.5 31.8 43.5 37.2 28.5 27.5 38.4 36.3 35.1 40.8 33.6
 32.7 45.  23.  32.8 39.3 32.3 41.2 44.  25.  38.2 36.4 28.2 36.8 34.2
 39.4 41.3 33.7 35.8 31.4 48.  30.8 42.2 41.4 37.6 38.3 29.7 33.8 30.4
 36.6 46.  37.3 41.7 22.  42.8 40.3 38.1 31.2 25.7 24.  38.7 23.5 41.1
 34.8 39.8 27.8 32.1 35.3 31.7 40.2 30.2 37.7 40.6 26.5 45.5 34.4 28.8
 39.7 44.5 46.5 44.3 47.  35.4 42.3 27.1 33.2 22.2 30.6 34.6 47.7 37.4
 26.1 33.3 31.9 41.8 36.1 31.3 40.9 30.3 34.1 38.6 19.5 20.  29.2 32.4
 28.3 27.2 29.3 40.4 36.7 37.9 27.3 35.7 44.8 39.6 32.6 32.2 41.9 33.4
 42.6 38.9 25.3 34.9 29.4 49.  42.4 43.6 21.  32.9 39.9 29.8 21.5 33.9
 36.9 31.6 29.9 30.7 41.6 24.2 29.1 22.5 20.3 43.2 39.1 33.1 23.3 42.9
 42.7 26.6 42.1 40.1 43.8]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.  23.  28.5 26.5 29.5 28.3 24.5 30.  25.  29.  24.  27.5 30.5 27.
 25.5 31.  23.5 36.  22.5 32.  22.  21.  26.  19.  21.5 22.3 25.7 20.5
  nan 27.3 29.1 23.3 28.4 25.6 29.2 25.4 22.6 25.3 28.2 26.8 27.2 20.
 27.4 30.3 24.2 23.2 20.9 29.3 18.5 24.7 25.8 23.9 26.1 24.8 22.2 21.3
 23.1 24.3 31.5 20.7 26.2 19.5 23.6 21.6 27.7 26.6 27.6 26.4 34.2 31.3
 22.8 20.2 35.5 28.8 25.2 29.4 19.8 27.8 26.3 23.8 21.8 23.7 28.6 29.7
 28.7 26.7 28.1 30.2 24.6 20.3 23.4 27.1 24.4 33.5 22.7 27.9 21.4 29.8
 24.1 20.6 19.7 28.9 32.5 22.9 21.7 24.9 29.9 25.1 18.  33.  21.2 20.8
 22.4 25.9 17.5 38.  21.9 30.4 18.7 30.1 34.  31.2 20.1 26.9 29.6 19.3
 19.4 18.3 17.  30.7 20.4 19.9 32.7 19.2 19.6 22.1 18.6 21.1 34.5 16.
 30.6 35.  14.5 31.6 32.6 37.2 18.8 30.8]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4 36.5 36.6 37.  35.6 36.8 36.7 36.2 34.7 35.3 36.1 36.  36.3 35.4
 35.9 35.7 35.  35.5 38.   nan 35.8 34.8 35.2 35.1 34.5 37.1 34.  36.9
 37.6 33.  37.2 33.8 34.3 34.4 37.4 37.5 34.9 34.6 34.2 34.1 33.4 37.3
 33.5 33.1 33.6 33.2 32.7 33.7 33.9 32.3 37.9 37.8 37.7 32.1 38.2 33.3
 32.4 32.5 32.6 32.9 32.2 38.4 31.9 38.1 32.  38.8 32.8 31.3 38.3 38.7
 38.5 38.6 31. ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35 7.28 7.42 7.49 7.36 7.3  7.21 7.1  7.44 7.31 7.46 7.33 7.24 7.18
 7.4  7.48 7.29 7.53 7.34 7.23 7.25 7.2  7.06 7.02 7.04 7.11 7.41 7.43
  nan 7.26 7.32 7.39 7.19 7.27 7.09 7.13 6.82 6.98 7.16 7.38 6.88 7.08
 7.22 6.97 7.45 7.37 7.17 7.05 7.52 7.14 7.01 7.5  7.07 7.47 7.03 7.15
 6.9  6.99 7.12 7.57 6.7  6.64 6.8  7.   6.87 7.55 6.74 7.51 6.66 6.89
 6.96 6.86 6.84 6.95 7.54 6.92 6.76 6.5  7.58 6.54 6.91 6.93 6.71 6.94
 6.77 7.65 6.83 7.59 6.75 6.85 6.81 7.56 7.72 6.65 6.56 6.63 7.63 6.57
 6.67 6.55 7.68 6.73 7.69 7.6  6.79 7.66 6.68 6.69 7.62 6.17 6.61 6.51
 6.78 6.59 6.72]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: date362
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
[                'NaT', '2021-12-21 00:00:00', '2022-01-03 00:00:00',
 '2022-01-06 00:00:00', '2022-01-26 00:00:00', '2022-01-14 00:00:00',
 '2022-01-29 00:00:00', '2021-12-13 00:00:00', '2021-12-24 00:00:00',
 '2021-04-30 00:00:00',
 ...
 '2022-03-15 00:00:00', '2022-09-21 00:00:00', '2022-11-15 00:00:00',
 '2023-02-11 00:00:00', '2023-02-23 00:00:00', '2023-02-20 00:00:00',
 '2023-03-04 00:00:00', '2022-09-30 00:00:00', '2023-02-01 00:00:00',
 '2022-09-26 00:00:00']
Length: 504, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: date36
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
['2014-01-25 00:00:00', '2014-01-24 00:00:00', '2014-01-01 00:00:00',
 '2014-01-11 00:00:00', '2013-11-10 00:00:00', '2013-10-09 00:00:00',
 '2013-12-15 00:00:00', '2013-10-15 00:00:00', '2013-11-15 00:00:00',
 '2013-11-17 00:00:00',
 ...
 '2021-11-15 00:00:00', '2021-04-12 00:00:00', '2021-05-12 00:00:00',
 '2021-08-11 00:00:00', '2022-01-04 00:00:00', '2021-12-03 00:00:00',
 '2021-11-22 00:00:00', '2022-01-22 00:00:00', '2021-09-05 00:00:00',
 '2022-10-12 00:00:00']
Length: 3206, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: death36
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: iarvppd
데이터 타입: int64
유니크한 값:
[ 11  45   4  13  10   2  78  38  15  41  68   1   0  50  58   3   5   6
  12  47  25  76 119  73   7  33  39  19  48  24  37  21  65   8  16  36
  90   9  54 120  53  35  27  59  18  43  62  22  77  44  26 220  30  29
  55  14 110  51  23  64  34 115  61  40  81  17  52  46  71  42  28  87
  32 111 134  95  20  66 109 351  70  60  72  93  86  31  74  56  82 215
  69  85 103 124 127 145  63 102 141 113 100 172  88 147  57 105 142  80
  49  96  79 229 114  67 354  89 138 247 150  75 365 148 143  99  97 154
  84 107  92 175 187 106 133 101 108 235 228 112 122 139 166 204 155  98
 104 121 299 144  91 310 324 221 218 131 165 261 240 159 285 222 162 183
 130 132 126 213 193 210 205 326 158 314 136 225 342  83  94 196 177 156
 137 160 168 152 226 153 198 280 163 178 149 190 151 118 135 184 169 289
 232 290 334 246 117 252 359 116 358 363 179 123 216 125 214 173 180 181
 167 315 347 248 146 192 161 186 291]
----------------------------------------
칼럼 이름: niarvrpd
데이터 타입: int64
유니크한 값:
[  2  21   9   5  19   4   1   6   7  12   0  14  10   3  18  16   8  24
  15  20  26  50  34  28  56  22  32  36  13  27  40  45  38  30  29  39
  11  31  17 100  33  90  23  53  37  94  66  25  98  42  63  65  48  58
 202  59  35  47  41  52  57  49  44  51  54  43  69  62  78  81  46  71
  88  60  68  67  83 103  64  55  61 111  74  72  80  79  89 249 117  95
  70  77  97  87  93 160  92 104 167  73  84  82  75  76  99 127 298  86
 118 131 302 154 151 145 115 112 192 101 212 134 128 133 124 125  91 139
 105 181 132  85 114 140 143 123 164 102 108 144 183 107 186 182 120  96
 153 207 225 136 155 169 180 159 116 106 113 141 162 137 135 109 110 147
 146 264 126 122 165]
----------------------------------------
칼럼 이름: aoxyuppd
데이터 타입: float64
유니크한 값:
[  5.  10.   8.   4.   7.  14.   6.  12.  16.  21.  24.   3.  35.  19.
  11.   9.  13.  25.  15.  54.  20.   0.   2.   1.  40.  17.  18.  28.
  31.  32.  48.  42.  29.  36.  26.  52.  37.  23.  34.  22.  41.  49.
  58.  45.  61.  27.  33.  39.  30.  96.  56.  50.  43.  57.  51.  90.
  63.  55.  70.  38.  46.  53.  65.  94.  76.  59.  66.  72.  75.  71.
  44.  78.  47.  81. 204. 109. 146.  64.  74. 101.  77.  73.  62.  80.
  60.  69.  88.  67. 135.  86.  68.  87.  79. 110. 132. 103.  92. 158.
  93. 178.  89.  84. 119.  95. 113.  83. 111. 118. 129. 133. 104. 102.
  85.]
----------------------------------------
칼럼 이름: niarvhfnc
데이터 타입: float64
유니크한 값:
[  0.  14.   9.  24.  19.  13.   5.  35.  52.  25.  18.  12.  59.  16.
  17.  23.  11.  33.  41.  10.   8.   6.  22.  21.   2.  34.  47.  27.
  46.   3.  53.   7.  15.  28.  37.  58.  38.  29.  40.  43.  31.  20.
  49.  54.  26.  91.  30.  39.  32.  44.   4.  45.  57.  36.  65.  66.
  42. 160.  86.  84.   1.  83.  60.  67.  56. 120.  55.  50.  77.  63.
  71.  76.  81.  69.  70.  51.  48. 126. 207. 107. 103. 132.  61. 100.
  62.  68.  97.  95.  78.  79.  72. 124.  89.  64. 112. 122. 104.  99.
 101. 106. 108.  74.  92.  87. 139. 121.  85.  93.  73. 133.  94.]
----------------------------------------
칼럼 이름: pdaddt
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
['2013-12-20 00:00:00',                 'NaT', '2013-11-18 00:00:00',
 '2013-11-14 00:00:00', '2013-09-13 00:00:00', '2013-10-08 00:00:00',
 '2013-09-17 00:00:00', '2013-09-27 00:00:00', '2013-06-12 00:00:00',
 '2013-06-05 00:00:00',
 ...
 '2022-07-11 00:00:00', '2022-06-29 00:00:00', '2022-08-07 00:00:00',
 '2022-08-16 00:00:00', '2022-12-25 00:00:00', '2022-12-30 00:00:00',
 '2022-05-29 00:00:00', '2022-10-03 00:00:00', '2022-04-06 00:00:00',
 '2022-12-01 00:00:00']
Length: 2801, dtype: datetime64[ns]
----------------------------------------
칼럼 이름: pdaddth
데이터 타입: object
유니크한 값:
['15:00' None '12:00' '11:00' '16:00' '23:00' '20:00' '21:00' '17:00'
 '10:00' '13:00' '09:00' '14:00' '18:00' '19:00' '22:00' '06:00' '08:00'
 '04:00' '00:00' '03:00' '02:00' '01:00' '07:00' '05:00' '24:00']
----------------------------------------
칼럼 이름: menidt
데이터 타입: datetime64[ns]
유니크한 값:
<DatetimeArray>
[                'NaT', '2013-11-29 00:00:00', '2013-04-14 00:00:00',
 '2013-08-02 00:00:00', '2014-03-14 00:00:00', '2014-06-03 00:00:00',
 '2014-11-15 00:00:00', '2014-05-28 00:00:00', '2014-11-25 00:00:00',
 '2014-09-15 00:00:00', '2015-02-12 00:00:00', '2014-04-26 00:00:00',
 '2014-03-30 00:00:00', '2014-06-04 00:00:00', '2014-07-30 00:00:00',
 '2014-04-03 00:00:00', '2014-09-20 00:00:00', '2014-08-02 00:00:00',
 '2014-12-29 00:00:00', '2015-01-01 00:00:00', '2014-02-07 00:00:00',

In [44]:
dfc

,sex_sys_val,birthdt,bir1,bir2,bir3,bir4,bird,admd,apgs1,apgs5,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,0.0,0.0,0.0,0.0,2013-12-18,2013-12-18,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,0.0,0.0,0.0,0.0,2013-11-15,2013-11-15,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,1.0,0.0,0.0,0.0,2013-11-15,2013-11-15,5.0,6.0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,0.0,1.0,0.0,0.0,2013-11-15,2013-11-15,6.0,7.0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,0.0,0.0,0.0,0.0,2013-11-11,2013-11-11,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,0.0,0.0,0.0,0.0,2022-11-28,2022-11-28,5.0,8.0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,0.0,0.0,0.0,0.0,2022-12-27,2022-12-27,4.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,0.0,0.0,0.0,0.0,2022-12-01,2022-12-01,5.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,0.0,1.0,0.0,0.0,2022-11-30,2022-11-30,3.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,1.0,0.0,0.0,0.0,2022-11-30,2022-11-30,4.0,6.0,...,0,0,1,0,0,0,1,0,0,0

In [46]:
out_dir = os.path.join(f"{base}/PedRes_Revision/dataset")
os.makedirs(out_dir, exist_ok=True)

# imputation 대상 칼럼
mean_cols = ['apgs1', 'apgs5', 'btem', 'bbph', 'bhead', 'bhei']
imp_cols = [c for c in mean_cols if c in dfc.columns]

print("Imputation columns:", imp_cols)

# 1) Non-imputation 상태 저장
dfc_nonimp = dfc.copy()
dfc_nonimp.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_NonImp.csv'),
    encoding='utf-8-sig'
)

# 2) Original 방식: mean imputation
dfc1 = dfc.copy()
dfc1[imp_cols] = dfc1[imp_cols].fillna(dfc1[imp_cols].mean())
dfc1.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_Orig.csv'),
    encoding='utf-8-sig'
)

# 3) Median imputation
dfc2 = dfc.copy()
dfc2[imp_cols] = dfc2[imp_cols].fillna(dfc2[imp_cols].median())
dfc2.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MedImp.csv'),
    encoding='utf-8-sig'
)

# 확인
print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_NonImp.csv'))
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_Orig.csv'))
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MedImp.csv'))

print("\nRemaining NaNs after each save target:")
print("NonImp")
print(dfc_nonimp[imp_cols].isna().sum())
print("\nOrig (mean): NaN values")
print(dfc1[imp_cols].isna().sum())
print("\nMedImp (median): NaN values")
print(dfc2[imp_cols].isna().sum())

Imputation columns: ['apgs1', 'apgs5', 'btem', 'bbph', 'bhead', 'bhei']

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_NonImp.csv
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_Orig.csv
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_MedImp.csv

Remaining NaNs after each save target:
NonImp
apgs1     121
apgs5     117
btem      631
bbph     4597
bhead    1230
bhei     1137
dtype: int64

Orig (mean): NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

MedImp (median): NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

In [47]:
dfc

,sex_sys_val,birthdt,bir1,bir2,bir3,bir4,bird,admd,apgs1,apgs5,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,0.0,0.0,0.0,0.0,2013-12-18,2013-12-18,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,0.0,0.0,0.0,0.0,2013-11-15,2013-11-15,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,1.0,0.0,0.0,0.0,2013-11-15,2013-11-15,5.0,6.0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,0.0,1.0,0.0,0.0,2013-11-15,2013-11-15,6.0,7.0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,0.0,0.0,0.0,0.0,2013-11-11,2013-11-11,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,0.0,0.0,0.0,0.0,2022-11-28,2022-11-28,5.0,8.0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,0.0,0.0,0.0,0.0,2022-12-27,2022-12-27,4.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,0.0,0.0,0.0,0.0,2022-12-01,2022-12-01,5.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,0.0,1.0,0.0,0.0,2022-11-30,2022-11-30,3.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,1.0,0.0,0.0,0.0,2022-11-30,2022-11-30,4.0,6.0,...,0,0,1,0,0,0,1,0,0,0

In [52]:
## 4) MICE / Iterative imputation

# i=20
dfc3 = dfc.copy()

mice_imputer = IterativeImputer(
    random_state=64,
    max_iter=20,
    sample_posterior=False,
    initial_strategy='mean'
)

dfc3[imp_cols] = mice_imputer.fit_transform(dfc3[imp_cols])

dfc3.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MICEImp-I20.csv'),
    encoding='utf-8-sig'
)

print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MICEImp-I20.csv'))
print("\nMICE: NaN values")
print(dfc3[imp_cols].isna().sum())


# i=10
dfc3 = dfc.copy()

mice_imputer = IterativeImputer(
    random_state=64,
    max_iter=10,
    sample_posterior=False,
    initial_strategy='mean'
)

dfc3[imp_cols] = mice_imputer.fit_transform(dfc3[imp_cols])

dfc3.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MICEImp-I10.csv'),
    encoding='utf-8-sig'
)

print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_MICEImp-I10.csv'))
print("\nMICE: NaN values")
print(dfc3[imp_cols].isna().sum())

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_MICEImp-I20.csv

MICE: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

C:\Users\AIWM_W01\.conda\envs\Dev_AIWM\lib\site-packages\sklearn\impute\_iterative.py:801: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_MICEImp-I10.csv

MICE: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

In [54]:
## 5) KNN imputation

# K=5
dfc4 = dfc.copy()

knn_imputer = KNNImputer(
    n_neighbors=5,
    weights='distance'
)

dfc4[imp_cols] = knn_imputer.fit_transform(dfc4[imp_cols])

dfc4.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K5.csv'),
    encoding='utf-8-sig'
)

# 확인
print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K5.csv'))
print("\nKNN: NaN values")
print(dfc4[imp_cols].isna().sum())


# K=10
dfc4 = dfc.copy()

knn_imputer = KNNImputer(
    n_neighbors=10,
    weights='distance'
)

dfc4[imp_cols] = knn_imputer.fit_transform(dfc4[imp_cols])

dfc4.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K10.csv'),
    encoding='utf-8-sig'
)

# 확인
print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K10.csv'))
print("\nKNN: NaN values")
print(dfc4[imp_cols].isna().sum())

# Non-weights
# K=10
dfc4 = dfc.copy()

knn_imputer = KNNImputer(
    n_neighbors=10,
)

dfc4[imp_cols] = knn_imputer.fit_transform(dfc4[imp_cols])

dfc4.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K10NW.csv'),
    encoding='utf-8-sig'
)

# 확인
print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K10NW.csv'))
print("\nKNN: NaN values")
print(dfc4[imp_cols].isna().sum())

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_KNNImp-K5.csv

KNN: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_KNNImp-K10.csv

KNN: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_KNNImp-K10NW.csv

KNN: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

In [55]:
# K=20
dfc5 = dfc.copy()

knn_imputer = KNNImputer(
    n_neighbors=20,
    weights='distance'
)

dfc5[imp_cols] = knn_imputer.fit_transform(dfc5[imp_cols])

dfc5.to_csv(
    os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K20.csv'),
    encoding='utf-8-sig'
)

# 확인
print("\nSaved files:")
print(os.path.join(out_dir, 'knn_prep-fin_M08-Rev_KNNImp-K20.csv'))
print("\nKNN: NaN values")
print(dfc5[imp_cols].isna().sum())

Saved files:
C:\Dev_AIWM\jupyter\KNN/PedRes_Revision/dataset\knn_prep-fin_M08-Rev_KNNImp-K20.csv

KNN: NaN values
apgs1    0
apgs5    0
btem     0
bbph     0
bhead    0
bhei     0
dtype: int64

In [20]:
# dfc.to_csv(os.path.join(crt_path, "knn_prep-fin_M08-Rev.csv"), encoding='utf-8-sig')

In [43]:
dfc_nonimp

,sex_sys_val,birthdt,bir1,bir2,bir3,bir4,bird,admd,apgs1,apgs5,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,0.0,0.0,0.0,0.0,2013-12-18,2013-12-18,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,0.0,0.0,0.0,0.0,2013-11-15,2013-11-15,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,1.0,0.0,0.0,0.0,2013-11-15,2013-11-15,5.0,6.0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,0.0,1.0,0.0,0.0,2013-11-15,2013-11-15,6.0,7.0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,0.0,0.0,0.0,0.0,2013-11-11,2013-11-11,4.0,5.0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,0.0,0.0,0.0,0.0,2022-11-28,2022-11-28,5.0,8.0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,0.0,0.0,0.0,0.0,2022-12-27,2022-12-27,4.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,0.0,0.0,0.0,0.0,2022-12-01,2022-12-01,5.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,0.0,1.0,0.0,0.0,2022-11-30,2022-11-30,3.0,7.0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,1.0,0.0,0.0,0.0,2022-11-30,2022-11-30,4.0,6.0,...,0,0,1,0,0,0,1,0,0,0

In [22]:
# # 1) 생존자( death36 == 0 )는 조건 없이 모두 유지
dfc_alive = dfc[dfc['death_label'] == 0]
dfc_alive.drop(columns=['death36', 'bir1', 'bir2', 'bir3', 'bir4'], inplace=True)
print(dfc_alive)

# dfc_dead = dfc[dfc['death_label'] == 1]

# # 2) 사망자( death36 == 1 ) 중에서
# #    dth36dt > ntetdt OR dth36dt > iperrdt 인 경우만 유지
# total_death_label_1 = dfc['death_label'].eq(1).sum()
# print(f"Total individuals with death_label = 1: {total_death_label_1}")
# before_filtering = len(dfc)
# dfc_dead = dfc[
#     (dfc['death_label'] == 1) &
#     ((dfc['death_dt'] > dfc['ntetdt']) | (dfc['death_dt'] > dfc['iperrdt']))
# ]
# after_filtering = len(dfc_dead)
# removed_count = total_death_label_1 - after_filtering
# print(f"Remaining individuals after filtering: {after_filtering}")
# print(f"Removed individuals: {removed_count}")

# # 3) 두 데이터프레임을 합쳐 최종 데이터프레임 생성
# dfc_f = pd.concat([dfc_alive, dfc_dead], ignore_index=True)

# dfc_f.drop(columns=['death36', 'bir1', 'bir2', 'bir3', 'bir4'], inplace=True)
# dfc_f

dfc.drop(columns=['death36', 'bir1', 'bir2', 'bir3', 'bir4'], inplace=True)
dfc

       sex_sys_val     birthdt        bird        admd  apgs1  apgs5  bwei  \
0                1  2013-12-18  2013-12-18  2013-12-18    4.0    5.0  1350
1                1  2013-11-15  2013-11-15  2013-11-15    4.0    5.0   790
2                1  2013-11-15  2013-11-15  2013-11-15    5.0    6.0  1400
3                1  2013-11-15  2013-11-15  2013-11-15    6.0    7.0  1340
4                1  2013-11-11  2013-11-11  2013-11-11    4.0    5.0  1240
...            ...         ...         ...         ...    ...    ...   ...
20408            1  2022-11-28  2022-11-28  2022-11-28    5.0    8.0  1350
20409            1  2022-12-27  2022-12-27  2022-12-27    4.0    7.0   860
20410            0  2022-12-01  2022-12-01  2022-12-01    5.0    7.0  1910
20411            1  2022-11-30  2022-11-30  2022-11-30    3.0    7.0  1660
20412            1  2022-11-30  2022-11-30  2022-11-30    4.0    6.0  1740

       mage  gran  parn  ...  ntetoy_3  ntetoy_1  iperr_1  iperr_2  iperr_3  \
0        29     1     0  ...         0         0        1        0        0
1        35     1     0  ...         0         0        1        0        0
2        26     1     0  ...         0         0        1        0        0
3        26     1     0  ...         0         0        1        0        0
4        36     4     1  ...         0         0        1        0        0
...     ...   ...   ...  ...       ...       ...      ...      ...      ...
20408    23     1     0  ...         0         0        1        0        0
20409    38     3     1  ...         0         0        1        0        0
20410    30     2     0  ...         0         0        1        0        0
20411    34     1     0  ...         0         0        1        0        0
20412    34     1     0  ...         0         0        1        0        0

       iperr_4  iperroy_1  iperroy_4  iperroy_3  iperroy_2
0            0          1          0          0          0
1            0          1          0          0          0
2            0          1          0          0          0
3            0          1          0          0          0
4            0          1          0          0          0
...        ...        ...        ...        ...        ...
20408        0          1          0          0          0
20409        0          1          0          0          0
20410        0          1          0          0          0
20411        0          1          0          0          0
20412        0          1          0          0          0

[17761 rows x 167 columns]

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27716\248818792.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_alive.drop(columns=['death36', 'bir1', 'bir2', 'bir3', 'bir4'], inplace=True)

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,2013-12-18,2013-12-18,4.0,5.0,1350,29,1,0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,2013-11-15,2013-11-15,4.0,5.0,790,35,1,0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,2013-11-15,2013-11-15,5.0,6.0,1400,26,1,0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,2013-11-15,2013-11-15,6.0,7.0,1340,26,1,0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,2013-11-11,2013-11-11,4.0,5.0,1240,36,4,1,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,2022-11-28,2022-11-28,5.0,8.0,1350,23,1,0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,2022-12-27,2022-12-27,4.0,7.0,860,38,3,1,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,2022-12-01,2022-12-01,5.0,7.0,1910,30,2,0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,2022-11-30,2022-11-30,3.0,7.0,1660,34,1,0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,2022-11-30,2022-11-30,4.0,6.0,1740,34,1,0,...,0,0,1,0,0,0,1,0,0,0

In [23]:
# # 생후 7일 이내 사망 제외
# mask = (dfc_f['death_dt'] - dfc_f['birthdt']).dt.days <= 7

# removed_count = mask.sum()
# dfc_f = dfc_f[~mask].reset_index(drop=True)
# print(f'Removed n: {removed_count}')

# dfc_f

In [24]:
dfc_alive.to_csv(os.path.join(crt_path, "knn_prep-fin_M09-alive.csv"), encoding='utf-8-sig')
dfc.to_csv(os.path.join(crt_path, "knn_prep-fin_M09.csv"), index=True, encoding='utf-8-sig')

# # With birthdt+7d deathdt data
# dfc_f.to_csv(os.path.join(crt_path, "knn_prep-fin_M04o.csv"), encoding='utf-8-sig')

# # With birthdt+7d deathdt data
# dfc_f.to_csv(os.path.join(crt_path, "knn_prep-fin_M04x.csv"), encoding='utf-8-sig')

In [25]:
dfc

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,2013-12-18,2013-12-18,4.0,5.0,1350,29,1,0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,2013-11-15,2013-11-15,4.0,5.0,790,35,1,0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,2013-11-15,2013-11-15,5.0,6.0,1400,26,1,0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,2013-11-15,2013-11-15,6.0,7.0,1340,26,1,0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,2013-11-11,2013-11-11,4.0,5.0,1240,36,4,1,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,2022-11-28,2022-11-28,5.0,8.0,1350,23,1,0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,2022-12-27,2022-12-27,4.0,7.0,860,38,3,1,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,2022-12-01,2022-12-01,5.0,7.0,1910,30,2,0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,2022-11-30,2022-11-30,3.0,7.0,1660,34,1,0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,2022-11-30,2022-11-30,4.0,6.0,1740,34,1,0,...,0,0,1,0,0,0,1,0,0,0

In [26]:
dfc_alive

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,2013-12-18,2013-12-18,4.0,5.0,1350,29,1,0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,2013-11-15,2013-11-15,4.0,5.0,790,35,1,0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,2013-11-15,2013-11-15,5.0,6.0,1400,26,1,0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,2013-11-15,2013-11-15,6.0,7.0,1340,26,1,0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,2013-11-11,2013-11-11,4.0,5.0,1240,36,4,1,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,2022-11-28,2022-11-28,2022-11-28,5.0,8.0,1350,23,1,0,...,0,0,1,0,0,0,1,0,0,0
20409,1,2022-12-27,2022-12-27,2022-12-27,4.0,7.0,860,38,3,1,...,0,0,1,0,0,0,1,0,0,0
20410,0,2022-12-01,2022-12-01,2022-12-01,5.0,7.0,1910,30,2,0,...,0,0,1,0,0,0,1,0,0,0
20411,1,2022-11-30,2022-11-30,2022-11-30,3.0,7.0,1660,34,1,0,...,0,0,1,0,0,0,1,0,0,0
20412,1,2022-11-30,2022-11-30,2022-11-30,4.0,6.0,1740,34,1,0,...,0,0,1,0,0,0,1,0,0,0

In [25]:
for column in dfc.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {dfc[column].dtype}")
    print(f"유니크한 값:")
    print(dfc[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 0]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: object
유니크한 값:
[datetime.date(2013, 12, 18) datetime.date(2013, 11, 15)
 datetime.date(2013, 11, 11) ... datetime.date(2022, 5, 5)
 datetime.date(2022, 7, 9) datetime.date(2022, 6, 19)]
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.          5.          6.          3.          7.          1.
  9.          8.          2.          4.75271096  0.         10.        ]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.          6.          7.          8.          4.          9.
  1.          3.         10.          2.          6.92736054  0.        ]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.        34.3       36.        42.        38.5       32.
 40.5       34.        38.        41.        35.5       35.
 29.5       40.        31.        41.5       37.        36.5
 39.5       30.        24.5       33.        30.5       36.2
 33.5       25.5       36.5344407 38.8       37.8       34.7
 37.1       27.        34.5       39.2       42.5       35.2
 35.6       40.7       37.5       28.6       43.        28.
 29.        26.        31.5       32.5       31.8       43.5
 37.2       28.5       27.5       38.4       36.3       35.1
 40.8       33.6       32.7       45.        23.        32.8
 39.3       32.3       41.2       44.        25.        38.2
 36.4       28.2       36.8       34.2       39.4       41.3
 33.7       35.8       31.4       48.        30.8       42.2
 41.4       37.6       38.3       29.7       33.8       30.4
 36.6       46.        37.3       41.7       22.        42.8
 40.3       38.1       31.2       25.7       24.        38.7
 23.5       41.1       34.8       39.8       27.8       32.1
 35.3       31.7       40.2       30.2       37.7       40.6
 26.5       45.5       34.4       28.8       39.7       44.5
 46.5       44.3       47.        35.4       42.3       27.1
 33.2       22.2       30.6       34.6       47.7       37.4
 26.1       33.3       31.9       41.8       36.1       31.3
 40.9       30.3       34.1       38.6       19.5       20.
 29.2       32.4       28.3       27.2       29.3       40.4
 36.7       37.9       27.3       35.7       44.8       39.6
 32.6       32.2       41.9       33.4       42.6       38.9
 25.3       34.9       29.4       49.        42.4       43.6
 21.        32.9       39.9       29.8       21.5       33.9
 36.9       31.6       29.9       30.7       41.6       24.2
 29.1       22.5       20.3       43.2       39.1       33.1
 23.3       42.9       42.7       26.6       42.1       40.1
 43.8      ]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.         23.         28.5        26.5        29.5        28.3
 24.5        30.         25.         29.         24.         27.5
 30.5        27.         25.5        31.         23.5        36.
 22.5        32.         22.         21.         26.         19.
 21.5        22.3        25.7        20.5        25.97613707 27.3
 29.1        23.3        28.4        25.6        29.2        25.4
 22.6        25.3        28.2        26.8        27.2        20.
 27.4        30.3        24.2        23.2        20.9        29.3
 18.5        24.7        25.8        23.9        26.1        24.8
 22.2        21.3        23.1        24.3        31.5        20.7
 26.2        19.5        23.6        21.6        27.7        26.6
 27.6        26.4        34.2        31.3        22.8        20.2
 35.5        28.8        25.2        29.4        19.8        27.8
 26.3        23.8        21.8        23.7        28.6        29.7
 28.7        26.7        28.1        30.2        24.6        20.3
 23.4        27.1        24.4        33.5        22.7        27.9
 21.4        29.8        24.1        20.6        19.7        28.9
 32.5        22.9        21.7        24.9        29.9        25.1
 18.         33.         21.2        20.8        22.4        25.9
 17.5        38.         21.9        30.4        18.7        30.1
 34.         31.2        20.1        26.9        29.6        19.3
 19.4        18.3        17.         30.7        20.4        19.9
 32.7        19.2        19.6        22.1        18.6        21.1
 34.5        16.         30.6        35.         14.5        31.6
 32.6        37.2        18.8        30.8       ]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4        36.5        36.6        37.         35.6        36.8
 36.7        36.2        34.7        35.3        36.1        36.
 36.3        35.4        35.9        35.7        35.         35.5
 38.         36.20092068 35.8        34.8        35.2        35.1
 34.5        37.1        34.         36.9        37.6        33.
 37.2        33.8        34.3        34.4        37.4        37.5
 34.9        34.6        34.2        34.1        33.4        37.3
 33.5        33.1        33.6        33.2        32.7        33.7
 33.9        32.3        37.9        37.8        37.7        32.1
 38.2        33.3        32.4        32.5        32.6        32.9
 32.2        38.4        31.9        38.1        32.         38.8
 32.8        31.3        38.3        38.7        38.5        38.6
 31.        ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35       7.28       7.42       7.49       7.36       7.3
 7.21       7.1        7.44       7.31       7.46       7.33
 7.24       7.18       7.4        7.48       7.29       7.53
 7.34       7.23       7.25       7.2        7.06       7.02
 7.04       7.11       7.41       7.43       7.26155799 7.26
 7.32       7.39       7.19       7.27       7.09       7.13
 6.82       6.98       7.16       7.38       6.88       7.08
 7.22       6.97       7.45       7.37       7.17       7.05
 7.52       7.14       7.01       7.5        7.07       7.47
 7.03       7.15       6.9        6.99       7.12       7.57
 6.7        6.64       6.8        7.         6.87       7.55
 6.74       7.51       6.66       6.89       6.96       6.86
 6.84       6.95       7.54       6.92       6.76       6.5
 7.58       6.54       6.91       6.93       6.71       6.94
 6.77       7.65       6.83       7.59       6.75       6.85
 6.81       7.56       7.72       6.65       6.56       6.63
 7.63       6.57       6.67       6.55       7.68       6.73
 7.69       7.6        6.79       7.66       6.68       6.69
 7.62       6.17       6.61       6.51       6.78       6.59
 6.72      ]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: date362
데이터 타입: object
유니크한 값:
[NaT datetime.date(2021, 12, 21) datetime.date(2022, 1, 3)
 datetime.date(2022, 1, 6) datetime.date(2022, 1, 26)
 datetime.date(2022, 1, 14) datetime.date(2022, 1, 29)
 datetime.date(2021, 12, 13) datetime.date(2021, 12, 24)
 datetime.date(2021, 4, 30) datetime.date(2021, 7, 6)
 datetime.date(2022, 1, 20) datetime.date(2021, 5, 29)
 datetime.date(2021, 6, 6) datetime.date(2021, 7, 7)
 datetime.date(2022, 1, 9) datetime.date(2022, 1, 11)
 datetime.date(2021, 12, 31) datetime.date(2021, 12, 9)
 datetime.date(2021, 12, 14) datetime.date(2021, 12, 20)
 datetime.date(2022, 1, 12) datetime.date(2021, 12, 28)
 datetime.date(2022, 1, 27) datetime.date(2022, 2, 15)
 datetime.date(2022, 1, 31) datetime.date(2022, 2, 5)
 datetime.date(2022, 1, 17) datetime.date(2021, 1, 10)
 datetime.date(2021, 2, 10) datetime.date(2021, 6, 17)
 datetime.date(2021, 6, 16) datetime.date(2021, 5, 31)
 datetime.date(2021, 6, 2) datetime.date(2021, 8, 25)
 datetime.date(2021, 8, 10) datetime.date(2021, 7, 23)
 datetime.date(2021, 10, 2) datetime.date(2021, 9, 27)
 datetime.date(2021, 10, 25) datetime.date(2021, 11, 17)
 datetime.date(2021, 11, 22) datetime.date(2022, 2, 1)
 datetime.date(2021, 11, 25) datetime.date(2022, 1, 28)
 datetime.date(2021, 12, 8) datetime.date(2022, 2, 4)
 datetime.date(2021, 11, 29) datetime.date(2021, 12, 29)
 datetime.date(2021, 12, 17) datetime.date(2022, 2, 9)
 datetime.date(2022, 3, 8) datetime.date(2022, 2, 16)
 datetime.date(2022, 2, 18) datetime.date(2022, 2, 11)
 datetime.date(2022, 3, 19) datetime.date(2021, 6, 30)
 datetime.date(2021, 12, 7) datetime.date(2021, 12, 25)
 datetime.date(2021, 11, 28) datetime.date(2021, 11, 12)
 datetime.date(2022, 2, 26) datetime.date(2022, 1, 13)
 datetime.date(2022, 1, 18) datetime.date(2022, 2, 12)
 datetime.date(2022, 3, 22) datetime.date(2022, 2, 19)
 datetime.date(2022, 2, 23) datetime.date(2021, 5, 5)
 datetime.date(2021, 4, 5) datetime.date(2021, 3, 24)
 datetime.date(2021, 5, 12) datetime.date(2021, 7, 8)
 datetime.date(2021, 6, 5) datetime.date(2021, 7, 31)
 datetime.date(2021, 8, 7) datetime.date(2021, 8, 21)
 datetime.date(2021, 10, 8) datetime.date(2021, 12, 2)
 datetime.date(2021, 9, 17) datetime.date(2021, 7, 4)
 datetime.date(2021, 10, 22) datetime.date(2021, 11, 2)
 datetime.date(2022, 1, 7) datetime.date(2021, 11, 15)
 datetime.date(2022, 2, 8) datetime.date(2021, 9, 3)
 datetime.date(2021, 11, 13) datetime.date(2021, 12, 5)
 datetime.date(2022, 1, 4) datetime.date(2021, 4, 21)
 datetime.date(2021, 6, 12) datetime.date(2021, 6, 27)
 datetime.date(2021, 7, 30) datetime.date(2021, 9, 10)
 datetime.date(2021, 10, 12) datetime.date(2021, 10, 23)
 datetime.date(2022, 2, 17) datetime.date(2021, 5, 14)
 datetime.date(2021, 3, 14) datetime.date(2021, 3, 20)
 datetime.date(2021, 3, 27) datetime.date(2021, 4, 17)
 datetime.date(2021, 3, 31) datetime.date(2021, 6, 13)
 datetime.date(2021, 6, 26) datetime.date(2021, 7, 9)
 datetime.date(2021, 8, 20) datetime.date(2021, 8, 3)
 datetime.date(2021, 10, 6) datetime.date(2021, 9, 15)
 datetime.date(2021, 9, 11) datetime.date(2022, 2, 22)
 datetime.date(2022, 1, 21) datetime.date(2022, 2, 6)
 datetime.date(2021, 12, 27) datetime.date(2022, 1, 19)
 datetime.date(2021, 12, 10) datetime.date(2021, 12, 1)
 datetime.date(2022, 1, 24) datetime.date(2022, 2, 3)
 datetime.date(2021, 12, 18) datetime.date(2021, 12, 11)
 datetime.date(2021, 12, 23) datetime.date(2022, 2, 24)
 datetime.date(2022, 1, 15) datetime.date(2022, 3, 7)

In [26]:
drop_cols = []
datetime_cols = ['ntetdt', 'ntetdty', 'date362', 'date36', 'menidt', 'pdaddth', 'pdaddt'
                 , 'birthdt', 'admd', 'birtm', 'bird', 'efydt', 'death_dt', 'iperrdt'
                ]
drop_cols += datetime_cols

rsndth_cols = ['death_CR', 'death_NL', 'death_Inf', 'death_GI', 'death_CA', 'death_Otr']
drop_cols += rsndth_cols
# dfc_f = dfc_f.drop(columns=list(drop_cols))

tgt_cols = [col for col in dfc.columns if col in ['ntet', 'ntety', 'ntetoy'
                                                    , 'SEPS_bef_NTET', 'SEPS_aft_NTET'
                                                    , 'NTET_day', 'PDA_7d_NTET'
                                                    , 'invfpod'
                                                    , 'iperr', 'iperroy'
                                                    , 'SEPS_bef_IPERR', 'SEPS_aft_IPERR'
                                                    , 'IPERR_day', 'PDA_7d_IPERR'
                                                    , 'PDA_7d_IPERRorNTET'
                                                    , 'SEPS_bef_IPERRorNTET', 'SEPS_aft_IPERRorNTET'
                                                   ]
            or any(col.startswith(prefix) for prefix in ['ntet', 'ntety', 'ntetoy'
                                                         , 'SEPS_bef_NTET', 'SEPS_aft_NTET'
                                                         , 'NTET_day', 'PDA_7d_NTET'
                                                         , 'invfpod'
                                                         , 'iperr', 'iperroy'
                                                         , 'SEPS_bef_IPERR', 'SEPS_aft_IPERR'
                                                         , 'IPERR_day', 'PDA_7d_IPERR'
                                                         , 'PDA_7d_IPERRorNTET'
                                                         , 'SEPS_bef_IPERRorNTET', 'SEPS_aft_IPERRorNTET'
                                                        ])
           ]
data = dfc.drop(columns=['death_label'] + list(drop_cols)
#                + list(tgt_cols)
#                + list(drop_cols)
#                + list(datetime_cols)
              )

data

,sex_sys_val,apgs1,apgs5,bwei,mage,gran,parn,bhei,bheiuk,bhead,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,4.0,5.0,1350,29,1,0,39.0,0.0,28.0,...,0,0,1,0,0,0,1,0,0,0
1,1,4.0,5.0,790,35,1,0,34.3,0.0,23.0,...,0,0,1,0,0,0,1,0,0,0
2,1,5.0,6.0,1400,26,1,0,39.0,0.0,28.5,...,0,0,1,0,0,0,1,0,0,0
3,1,6.0,7.0,1340,26,1,0,36.0,0.0,28.0,...,0,0,1,0,0,0,1,0,0,0
4,1,4.0,5.0,1240,36,4,1,42.0,0.0,26.5,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20408,1,5.0,8.0,1350,23,1,0,37.5,0.0,27.5,...,0,0,1,0,0,0,1,0,0,0
20409,1,4.0,7.0,860,38,3,1,33.5,0.0,23.5,...,0,0,1,0,0,0,1,0,0,0
20410,0,5.0,7.0,1910,30,2,0,42.5,0.0,29.0,...,0,0,1,0,0,0,1,0,0,0
20411,1,3.0,7.0,1660,34,1,0,41.5,0.0,28.5,...,0,0,1,0,0,0,1,0,0,0
20412,1,4.0,6.0,1740,34,1,0,43.5,0.0,29.0,...,0,0,1,0,0,0,1,0,0,0

In [29]:
for column in data.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {data[column].dtype}")
    print(f"유니크한 값:")
    print(data[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 0]
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.          5.          6.          3.          7.          1.
  9.          8.          2.          4.75271096  0.         10.        ]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.          6.          7.          8.          4.          9.
  1.          3.         10.          2.          6.92736054  0.        ]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.        34.3       36.        42.        38.5       32.
 40.5       34.        38.        41.        35.5       35.
 29.5       40.        31.        41.5       37.        36.5
 39.5       30.        24.5       33.        30.5       36.2
 33.5       25.5       36.5344407 38.8       37.8       34.7
 37.1       27.        34.5       39.2       42.5       35.2
 35.6       40.7       37.5       28.6       43.        28.
 29.        26.        31.5       32.5       31.8       43.5
 37.2       28.5       27.5       38.4       36.3       35.1
 40.8       33.6       32.7       45.        23.        32.8
 39.3       32.3       41.2       44.        25.        38.2
 36.4       28.2       36.8       34.2       39.4       41.3
 33.7       35.8       31.4       48.        30.8       42.2
 41.4       37.6       38.3       29.7       33.8       30.4
 36.6       46.        37.3       41.7       22.        42.8
 40.3       38.1       31.2       25.7       24.        38.7
 23.5       41.1       34.8       39.8       27.8       32.1
 35.3       31.7       40.2       30.2       37.7       40.6
 26.5       45.5       34.4       28.8       39.7       44.5
 46.5       44.3       47.        35.4       42.3       27.1
 33.2       22.2       30.6       34.6       47.7       37.4
 26.1       33.3       31.9       41.8       36.1       31.3
 40.9       30.3       34.1       38.6       19.5       20.
 29.2       32.4       28.3       27.2       29.3       40.4
 36.7       37.9       27.3       35.7       44.8       39.6
 32.6       32.2       41.9       33.4       42.6       38.9
 25.3       34.9       29.4       49.        42.4       43.6
 21.        32.9       39.9       29.8       21.5       33.9
 36.9       31.6       29.9       30.7       41.6       24.2
 29.1       22.5       20.3       43.2       39.1       33.1
 23.3       42.9       42.7       26.6       42.1       40.1
 43.8      ]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.         23.         28.5        26.5        29.5        28.3
 24.5        30.         25.         29.         24.         27.5
 30.5        27.         25.5        31.         23.5        36.
 22.5        32.         22.         21.         26.         19.
 21.5        22.3        25.7        20.5        25.97613707 27.3
 29.1        23.3        28.4        25.6        29.2        25.4
 22.6        25.3        28.2        26.8        27.2        20.
 27.4        30.3        24.2        23.2        20.9        29.3
 18.5        24.7        25.8        23.9        26.1        24.8
 22.2        21.3        23.1        24.3        31.5        20.7
 26.2        19.5        23.6        21.6        27.7        26.6
 27.6        26.4        34.2        31.3        22.8        20.2
 35.5        28.8        25.2        29.4        19.8        27.8
 26.3        23.8        21.8        23.7        28.6        29.7
 28.7        26.7        28.1        30.2        24.6        20.3
 23.4        27.1        24.4        33.5        22.7        27.9
 21.4        29.8        24.1        20.6        19.7        28.9
 32.5        22.9        21.7        24.9        29.9        25.1
 18.         33.         21.2        20.8        22.4        25.9
 17.5        38.         21.9        30.4        18.7        30.1
 34.         31.2        20.1        26.9        29.6        19.3
 19.4        18.3        17.         30.7        20.4        19.9
 32.7        19.2        19.6        22.1        18.6        21.1
 34.5        16.         30.6        35.         14.5        31.6
 32.6        37.2        18.8        30.8       ]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4        36.5        36.6        37.         35.6        36.8
 36.7        36.2        34.7        35.3        36.1        36.
 36.3        35.4        35.9        35.7        35.         35.5
 38.         36.20092068 35.8        34.8        35.2        35.1
 34.5        37.1        34.         36.9        37.6        33.
 37.2        33.8        34.3        34.4        37.4        37.5
 34.9        34.6        34.2        34.1        33.4        37.3
 33.5        33.1        33.6        33.2        32.7        33.7
 33.9        32.3        37.9        37.8        37.7        32.1
 38.2        33.3        32.4        32.5        32.6        32.9
 32.2        38.4        31.9        38.1        32.         38.8
 32.8        31.3        38.3        38.7        38.5        38.6
 31.        ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35       7.28       7.42       7.49       7.36       7.3
 7.21       7.1        7.44       7.31       7.46       7.33
 7.24       7.18       7.4        7.48       7.29       7.53
 7.34       7.23       7.25       7.2        7.06       7.02
 7.04       7.11       7.41       7.43       7.26155799 7.26
 7.32       7.39       7.19       7.27       7.09       7.13
 6.82       6.98       7.16       7.38       6.88       7.08
 7.22       6.97       7.45       7.37       7.17       7.05
 7.52       7.14       7.01       7.5        7.07       7.47
 7.03       7.15       6.9        6.99       7.12       7.57
 6.7        6.64       6.8        7.         6.87       7.55
 6.74       7.51       6.66       6.89       6.96       6.86
 6.84       6.95       7.54       6.92       6.76       6.5
 7.58       6.54       6.91       6.93       6.71       6.94
 6.77       7.65       6.83       7.59       6.75       6.85
 6.81       7.56       7.72       6.65       6.56       6.63
 7.63       6.57       6.67       6.55       7.68       6.73
 7.69       7.6        6.79       7.66       6.68       6.69
 7.62       6.17       6.61       6.51       6.78       6.59
 6.72      ]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: iarvppd
데이터 타입: int64
유니크한 값:
[ 11  45   4  13  10   2  78  38  15  41  68   1   0  50  58   3   5   6
  12  47  25  76 119  73   7  33  39  19  48  24  37  21  65   8  16  36
  90   9  54 120  53  35  27  59  18  43  62  22  77  44  26 220  30  29
  55  14 110  51  23  64  34 115  61  40  81  17  52  46  71  42  28  87
  32 111 134  95  20  66 109 351  70  60  72  93  86  31  74  56  82 215
  69  85 103 124 127 145  63 102 141 113 100 172  88 147  57 105 142  80
  49  96  79 229 114  67 354  89 138 247 150  75 365 148 143  99  97 154
  84 107  92 175 187 106 133 101 108 235 228 112 122 139 166 204 155  98
 104 121 299 144  91 310 324 221 218 131 165 261 240 159 285 222 162 183
 130 132 126 213 193 210 205 326 158 314 136 225 342  83  94 196 177 156
 137 160 168 152 226 153 198 280 163 178 149 190 151 118 135 184 169 289
 232 290 334 246 117 252 359 116 358 363 179 123 216 125 214 173 180 181
 167 315 347 248 146 192 161 186 291]
----------------------------------------
칼럼 이름: niarvrpd
데이터 타입: int64
유니크한 값:
[  2  21   9   5  19   4   1   6   7  12   0  14  10   3  18  16   8  24
  15  20  26  50  34  28  56  22  32  36  13  27  40  45  38  30  29  39
  11  31  17 100  33  90  23  53  37  94  66  25  98  42  63  65  48  58
 202  59  35  47  41  52  57  49  44  51  54  43  69  62  78  81  46  71
  88  60  68  67  83 103  64  55  61 111  74  72  80  79  89 249 117  95
  70  77  97  87  93 160  92 104 167  73  84  82  75  76  99 127 298  86
 118 131 302 154 151 145 115 112 192 101 212 134 128 133 124 125  91 139
 105 181 132  85 114 140 143 123 164 102 108 144 183 107 186 182 120  96
 153 207 225 136 155 169 180 159 116 106 113 141 162 137 135 109 110 147
 146 264 126 122 165]
----------------------------------------
칼럼 이름: aoxyuppd
데이터 타입: float64
유니크한 값:
[  5.  10.   8.   4.   7.  14.   6.  12.  16.  21.  24.   3.  35.  19.
  11.   9.  13.  25.  15.  54.  20.   0.   2.   1.  40.  17.  18.  28.
  31.  32.  48.  42.  29.  36.  26.  52.  37.  23.  34.  22.  41.  49.
  58.  45.  61.  27.  33.  39.  30.  96.  56.  50.  43.  57.  51.  90.
  63.  55.  70.  38.  46.  53.  65.  94.  76.  59.  66.  72.  75.  71.
  44.  78.  47.  81. 204. 109. 146.  64.  74. 101.  77.  73.  62.  80.
  60.  69.  88.  67. 135.  86.  68.  87.  79. 110. 132. 103.  92. 158.
  93. 178.  89.  84. 119.  95. 113.  83. 111. 118. 129. 133. 104. 102.
  85.]
----------------------------------------
칼럼 이름: niarvhfnc
데이터 타입: float64
유니크한 값:
[  0.  14.   9.  24.  19.  13.   5.  35.  52.  25.  18.  12.  59.  16.
  17.  23.  11.  33.  41.  10.   8.   6.  22.  21.   2.  34.  47.  27.
  46.   3.  53.   7.  15.  28.  37.  58.  38.  29.  40.  43.  31.  20.
  49.  54.  26.  91.  30.  39.  32.  44.   4.  45.  57.  36.  65.  66.
  42. 160.  86.  84.   1.  83.  60.  67.  56. 120.  55.  50.  77.  63.
  71.  76.  81.  69.  70.  51.  48. 126. 207. 107. 103. 132.  61. 100.
  62.  68.  97.  95.  78.  79.  72. 124.  89.  64. 112. 122. 104.  99.
 101. 106. 108.  74.  92.  87. 139. 121.  85.  93.  73. 133.  94.]
----------------------------------------
칼럼 이름: invfpod
데이터 타입: int64
유니크한 값:
[ 10  32  30  69  34   3  12  35  22  16  51  24   7   0   5  45  19   8
  13  14  31  18  15  61  41  21  42  39  40  54   9  27  20  48  60  23
  65   2  90  17  78  11  52 120  49  72  47  46  63  28  38  50 223  57
  59  53  83  84   4  73  37  43 113  70  26  56  66 107  64  33  25  71
  82  58  74  88  29  76  87  62  79 138  85  80  36  77  86 103  55 104
   6  44 117 112 114  68  98  81 152 149  92 129  67 168 238  91   1 213
 101 106 141  93 135 100 161 122 123 124 202 209 126  95 111  96  75 119
 165 178 158 150 105 153 154 169 224 125 115 280 109 108 139 170 151 176
 136 204  97 144  99 143 127 197 210 116 121 102  94 324 110 230 221 137
 190 133 146 147 130 226 216 157 271  89 131 235 140 128 164 183 350 145
 281 156 132 162 134 287 160 181 155 192 166 174 214 118 227 163 199 212
 175 282 142 159 288 254 243 182 193 220 191 201 198 189 184 173 148 180
 194 167 333 240 177 179]
----------------------------------------
칼럼 이름: pmirnsgnd
데이터 타입: int32
유니크한 값:
[0 1]
----------------------------------------

In [27]:
analyse_dataframe(data)

             NaN Counts  NaN Ratios (%)  Unique Values Count
sex_sys_val           0             0.0                    2
apgs1                 0             0.0                   12
apgs5                 0             0.0                   12
bwei                  0             0.0                  902
mage                  0             0.0                   40
...                 ...             ...                  ...
iperr_4               0             0.0                    2
iperroy_1             0             0.0                    2
iperroy_4             0             0.0                    2
iperroy_3             0             0.0                    2
iperroy_2             0             0.0                    2

[146 rows x 3 columns]

In [ ]:
## np.nan or '0' Findings

In [31]:
dfc = pd.read_csv(os.path.join(crt_path, "knn_prep-fin_M06.csv"))
dfc.drop(columns = 'Unnamed: 0', inplace = True)
dfc

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_22928\1968373916.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  dfc = pd.read_csv(os.path.join(crt_path, "knn_prep-fin_M06.csv"))

,sex_sys_val,birthdt,bird,admd,apgs1,apgs5,bwei,mage,gran,parn,...,ntetoy_3,ntetoy_1,iperr_1,iperr_2,iperr_3,iperr_4,iperroy_1,iperroy_4,iperroy_3,iperroy_2
0,1,2013-12-18,2013-12-18,2013-12-18,4.0,5.0,1350,29,1,0,...,0,0,1,0,0,0,1,0,0,0
1,1,2013-11-15,2013-11-15,2013-11-15,4.0,5.0,790,35,1,0,...,0,0,1,0,0,0,1,0,0,0
2,1,2013-11-15,2013-11-15,2013-11-15,5.0,6.0,1400,26,1,0,...,0,0,1,0,0,0,1,0,0,0
3,1,2013-11-15,2013-11-15,2013-11-15,6.0,7.0,1340,26,1,0,...,0,0,1,0,0,0,1,0,0,0
4,1,2013-11-11,2013-11-11,2013-11-11,4.0,5.0,1240,36,4,1,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20347,1,2022-11-28,2022-11-28,2022-11-28,5.0,8.0,1350,23,1,0,...,0,0,1,0,0,0,1,0,0,0
20348,1,2022-12-27,2022-12-27,2022-12-27,4.0,7.0,860,38,3,1,...,0,0,1,0,0,0,1,0,0,0
20349,0,2022-12-01,2022-12-01,2022-12-01,5.0,7.0,1910,30,2,0,...,0,0,1,0,0,0,1,0,0,0
20350,1,2022-11-30,2022-11-30,2022-11-30,3.0,7.0,1660,34,1,0,...,0,0,1,0,0,0,1,0,0,0
20351,1,2022-11-30,2022-11-30,2022-11-30,4.0,6.0,1740,34,1,0,...,0,0,1,0,0,0,1,0,0,0

In [32]:
for column in dfc.columns:
    print(f"칼럼 이름: {column}")
    print(f"데이터 타입: {dfc[column].dtype}")
    print(f"유니크한 값:")
    print(dfc[column].unique())
    print("-" * 40)

칼럼 이름: sex_sys_val
데이터 타입: int64
유니크한 값:
[1 0]
----------------------------------------
칼럼 이름: birthdt
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: bird
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: admd
데이터 타입: object
유니크한 값:
['2013-12-18' '2013-11-15' '2013-11-11' ... '2022-05-05' '2022-07-09'
 '2022-06-19']
----------------------------------------
칼럼 이름: apgs1
데이터 타입: float64
유니크한 값:
[ 4.          5.          6.          3.          7.          1.
  9.          8.          2.          4.75271096  0.         10.        ]
----------------------------------------
칼럼 이름: apgs5
데이터 타입: float64
유니크한 값:
[ 5.          6.          7.          8.          4.          9.
  1.          3.         10.          2.          6.92736054  0.        ]
----------------------------------------
칼럼 이름: bwei
데이터 타입: int64
유니크한 값:
[1350  790 1400 1340 1240  810 1300 1380  990 1180 1475 1450 1485  960
  910  730 1370 1205 1440 1390 1480 1290 1210 1455 1200 1360 1470 1015
  860  865 1130 1090  920 1260 1220 1320  980  660  600 1270  940 1080
 1190 1490 1040  930  670 1160  480 1330 1250 1460 1310  473  840  850
 1140  610  950 1070 1060  720  680  770 1170  710 1061 1002 1120 1020
  922 1037 1031  765  438 1243  880 1306 1472  708 1376  924  970 1150
 1245 1065 1100 1445  890  780  640  731 1452  756  714  719 1047 1312
  726 1013  483 1420 1498 1124  550 1206  782  936 1074 1128 1408 1484
 1410  740 1110  760  470  870 1230  800  690  590 1378  900 1010 1286
 1248 1194 1356  750  530 1342 1430 1354 1050 1280  515  510  855 1325
  955  995  645  650  830  580  570  430  540  820  875  460  490  520
 1000  400  700 1030  630  560  620 1255  320  440  500 1355 1495  380
  816  846  932 1165 1375  805  533  420  705  775  915  849  615  885
 1211 1244  839 1405 1466 1098 1025 1104 1365 1185  965 1315 1285  575
  585  735 1295  935 1335  925  633 1113  776 1352 1048  755  953  819
 1372 1387 1457 1146 1225 1252  886  897  946  512  519  657  717  736
 1006 1014 1017 1476 1085  951 1436  801  777  988  967  879 1486  458
 1276 1151  732 1439 1195  835 1499  370 1453  929 1444  934 1363  964
  337 1066 1407  598 1028 1235  652  966  675  794  814  592 1398 1036
 1446 1496 1294 1024 1435  795  789  535  815  703  300 1305  330 1482
  410 1454 1345 1095 1145  655  878  545 1395  450  310  905  495  825
 1005  671 1409 1441  595 1045  853  945 1334  833 1075 1115 1275 1415
 1385  745 1402 1142 1176 1442 1247 1425  704 1382 1035 1249 1093  405
 1041  574  493 1229  709 1344  831  894  567  416 1062 1122 1392 1026
 1234  565 1049 1327  857  658 1012 1181  812 1246  842 1136  649  974
  618 1388 1198  943  902  340  975  665 1175 1155 1298  701  639 1167
 1241  804 1261 1016 1326 1296 1491  496 1226 1196  762 1277 1412 1418
 1414 1364 1336 1464 1094 1386 1254  845 1278 1494 1288  754  501  494
 1215 1123 1465  350  635  390  433  555  985 1105 1055  685 1471  695
 1487 1463  505 1483 1406  725 1129 1362 1125 1156 1228 1202 1456  654
  949  972  764  739 1153  673 1272  917  753 1071  554  613 1309  698
  989  454  636 1059  558  772  506  696 1148  863 1201 1149 1052 1492
  507 1238  869 1329 1297  543 1267 1358 1119 1434 1438  724 1112  360
 1135 1426 1302  548  767  694 1279  707  911 1008  638 1314 1046 1056
 1469  434  991  672 1042 1265  702  914  475  715 1266 1116  898  579
 1368 1282  903  844  544  499 1332 1349  504  913  492  817 1203  752
  856  909  787  757  318  758  959 1213  566 1462  662  798  977 1019
 1253 1107 1043  895  587  596 1322  868  466 1383 1157 1328  918  307
 1134 1216 1224 1064  766  467  451 1389  616 1154  528 1227  749  557
 1068  674  485  551  605 1481  534  761  968  956  912 1428  901  346
  663  549  513 1419  907 1377  896  602  682  877  586  937 1318  848
  723 1089  948  996  926 1172  552 1373 1474  634 1177  854  711 1258
  759 1404 1478 1222  302  455  821 1421 1396 1489  785  531  328 1162
 1158 1007 1447 1347 1111  893  503  568 1178  889  793  887  978  818
  923 1034 1021 1022  376 1004 1204  332 1443 1416 1077 1171  609  465
 1304 1084 1374 1029  927  982 1058 1289  743 1221 1018  593 1139 1044
  524  984  392 1051  641  345  569  799  963 1381 1236 1351 1479 1208
  617  837 1431  921  365  604 1323  612  983 1161 1078  796 1001  546
 1393  526 1283 1338 1308  716  746  691 1319  763  611 1257 1346 1379
  619  806  788  938  572 1063  688  556  827 1114 1331  811  882 1103
  873  642 1324  668  497  608  564  421  647  973  588 1424 1497  338
  737 1144  684 1039 1493  677  713  824 1159 1038  601  621  741  998
 1009 1237 1458 1086 1449  941  931  516 1092  689 1366  783 1073 1281
  986 1088  325 1477  981  957  942  876  581  866  656 1292  733 1287
  692  452  469  631 1321  884  355 1214  625 1301  523  859 1117 1173
 1251 1164 1032 1670 1540 1660 1610 1740 1550 1520 1500 1650 1980 1920
 1620 1570 1580 1770 1810 1830 1630 1690 1950 1730 1468  872 1510 1880
 1780 1524 1759 1552 1860  482 1870 1712 1534 1264 1909  742  944 1926
 1545 1873 1718  539 1579  666  525  916 1273 1054 1850 1820 1800 1567
 1750 1560  797  624 1640 1523 1700 1027 1868 1760 1960 1530 1600 1625
 1174 1652 1764 1528 1218 1890 1790 1665 1535 1512 1900 1710 1590 1930
 1840 1910 1313 1432  401 1461 1773 1574 1680 1720 1835  928  447  374
  999 1316  559  429  532  502 1756 1990 1940 2000 1945 1765 1506 1586
 1538 1722 1549 1357 1970 1752 1657 1768  408  541 1003 1564  939 1391
 1934 1531 1076  511 1555 1505]
----------------------------------------
칼럼 이름: mage
데이터 타입: int64
유니크한 값:
[29 35 26 36 32 42 33 30 31 28 37 34 41 25 20 38 39 27 24 19 43 21 23 40
 22 44 47 45 18 16 46 15 13 49 17 48 14 10 51 50]
----------------------------------------
칼럼 이름: gran
데이터 타입: int64
유니크한 값:
[ 1  4  2  3  5  7  6 10  8  9 13 11 16 14 12 29]
----------------------------------------
칼럼 이름: parn
데이터 타입: int64
유니크한 값:
[0 1 2 3 4 9 5 8 6 7]
----------------------------------------
칼럼 이름: bhei
데이터 타입: float64
유니크한 값:
[39.        34.3       36.        42.        38.5       32.
 40.5       34.        38.        41.        35.5       35.
 29.5       40.        31.        41.5       37.        36.5
 39.5       30.        24.5       33.        30.5       36.2
 33.5       25.5       36.5344407 38.8       37.8       34.7
 37.1       27.        34.5       39.2       42.5       35.2
 35.6       40.7       37.5       28.6       43.        28.
 29.        26.        31.5       32.5       31.8       43.5
 37.2       28.5       27.5       38.4       36.3       35.1
 40.8       33.6       32.7       45.        23.        32.8
 39.3       32.3       41.2       44.        25.        38.2
 36.4       28.2       36.8       34.2       39.4       41.3
 33.7       35.8       31.4       48.        30.8       42.2
 41.4       37.6       38.3       29.7       33.8       30.4
 36.6       46.        37.3       41.7       22.        42.8
 40.3       38.1       31.2       25.7       24.        38.7
 23.5       41.1       34.8       39.8       27.8       32.1
 35.3       31.7       40.2       30.2       37.7       40.6
 26.5       45.5       34.4       28.8       39.7       44.5
 46.5       44.3       47.        35.4       42.3       27.1
 33.2       22.2       30.6       34.6       47.7       37.4
 26.1       33.3       31.9       41.8       36.1       31.3
 40.9       30.3       34.1       38.6       19.5       20.
 29.2       32.4       28.3       27.2       29.3       40.4
 36.7       37.9       27.3       35.7       44.8       39.6
 32.6       32.2       41.9       33.4       42.6       38.9
 25.3       34.9       29.4       49.        42.4       43.6
 21.        32.9       39.9       29.8       21.5       33.9
 36.9       31.6       29.9       30.7       41.6       24.2
 29.1       22.5       20.3       43.2       39.1       33.1
 23.3       42.9       42.7       26.6       42.1       40.1
 43.8      ]
----------------------------------------
칼럼 이름: bheiuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bhead
데이터 타입: float64
유니크한 값:
[28.         23.         28.5        26.5        29.5        28.3
 24.5        30.         25.         29.         24.         27.5
 30.5        27.         25.5        31.         23.5        36.
 22.5        32.         22.         21.         26.         19.
 21.5        22.3        25.7        20.5        25.97613707 27.3
 29.1        23.3        28.4        25.6        29.2        25.4
 22.6        25.3        28.2        26.8        27.2        20.
 27.4        30.3        24.2        23.2        20.9        29.3
 18.5        24.7        25.8        23.9        26.1        24.8
 22.2        21.3        23.1        24.3        31.5        20.7
 26.2        19.5        23.6        21.6        27.7        26.6
 27.6        26.4        34.2        31.3        22.8        20.2
 35.5        28.8        25.2        29.4        19.8        27.8
 26.3        23.8        21.8        23.7        28.6        29.7
 28.7        26.7        28.1        30.2        24.6        20.3
 23.4        27.1        24.4        33.5        22.7        27.9
 21.4        29.8        24.1        20.6        19.7        28.9
 32.5        22.9        21.7        24.9        29.9        25.1
 18.         33.         21.2        20.8        22.4        25.9
 17.5        38.         21.9        30.4        18.7        30.1
 34.         31.2        20.1        26.9        29.6        19.3
 19.4        18.3        17.         30.7        20.4        19.9
 32.7        19.2        19.6        22.1        18.6        21.1
 34.5        16.         30.6        35.         14.5        31.6
 32.6        37.2        18.8        30.8       ]
----------------------------------------
칼럼 이름: bheaduk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: btem
데이터 타입: float64
유니크한 값:
[36.4        36.5        36.6        37.         35.6        36.8
 36.7        36.2        34.7        35.3        36.1        36.
 36.3        35.4        35.9        35.7        35.         35.5
 38.         36.20092068 35.8        34.8        35.2        35.1
 34.5        37.1        34.         36.9        37.6        33.
 37.2        33.8        34.3        34.4        37.4        37.5
 34.9        34.6        34.2        34.1        33.4        37.3
 33.5        33.1        33.6        33.2        32.7        33.7
 33.9        32.3        37.9        37.8        37.7        32.1
 38.2        33.3        32.4        32.5        32.6        32.9
 32.2        38.4        31.9        38.1        32.         38.8
 32.8        31.3        38.3        38.7        38.5        38.6
 31.        ]
----------------------------------------
칼럼 이름: btemuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbph
데이터 타입: float64
유니크한 값:
[7.35       7.28       7.42       7.49       7.36       7.3
 7.21       7.1        7.44       7.31       7.46       7.33
 7.24       7.18       7.4        7.48       7.29       7.53
 7.34       7.23       7.25       7.2        7.06       7.02
 7.04       7.11       7.41       7.43       7.26155799 7.26
 7.32       7.39       7.19       7.27       7.09       7.13
 6.82       6.98       7.16       7.38       6.88       7.08
 7.22       6.97       7.45       7.37       7.17       7.05
 7.52       7.14       7.01       7.5        7.07       7.47
 7.03       7.15       6.9        6.99       7.12       7.57
 6.7        6.64       6.8        7.         6.87       7.55
 6.74       7.51       6.66       6.89       6.96       6.86
 6.84       6.95       7.54       6.92       6.76       6.5
 7.58       6.54       6.91       6.93       6.71       6.94
 6.77       7.65       6.83       7.59       6.75       6.85
 6.81       7.56       7.72       6.65       6.56       6.63
 7.63       6.57       6.67       6.55       7.68       6.73
 7.69       7.6        6.79       7.66       6.68       6.69
 7.62       6.17       6.61       6.51       6.78       6.59
 6.72      ]
----------------------------------------
칼럼 이름: bbphuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: bbbe
데이터 타입: float64
유니크한 값:
[ -5.3         -1.7          1.5         -3.9         -2.3
  -5.4         -9.2         -6.8          1.          -3.5
   1.8         -1.8         -4.4         -2.1         -7.2
 -10.          -0.2         -1.3         -1.2         -1.6
  -4.9         -3.7         -3.3         -4.6         -4.3
  -7.5        -11.4        -12.6         -2.          -5.2
   0.1        -13.          -9.1         -6.7         -2.8
  -2.9         -5.05779705 -15.2         -4.7         -3.
  -3.6         -5.1         -4.2         -8.          -0.8
  -5.9         -3.8         -4.1         -1.5         -6.2
 -10.1         -9.8         -6.          -6.1         -1.
  -3.1         -5.7         -7.1        -13.1         -9.
  -1.1        -11.8         -8.2         -3.2        -12.1
 -21.4         -9.7        -10.6        -20.         -15.6
  -9.5        -11.5         -6.4         -4.5        -17.
  -4.           2.           5.           1.1         -8.1
  -5.6        -17.4         -4.8        -10.2         -2.5
  -7.3          2.4        -12.9         -5.5         -8.8
 -12.4        -10.7         -9.3         -8.4        -10.3
  -3.4         -7.7         -1.9         -7.         -16.
  -5.          -0.           3.         -19.         -15.
 -18.         -11.          -2.4          0.6          0.2
 -11.9         -2.7         -2.6         -0.4          2.2
   1.9          4.          -9.9          0.8         -6.9
   2.1         -6.3         -2.2         -0.7        -14.
 -12.          -0.5         -5.8          0.7          1.2
 -14.3         -8.7        -12.7        -10.5        -11.7
  -0.3         -6.6         -7.4        -11.3          3.1
   4.4          2.3          0.5        -13.6         -6.5
  -8.3         -1.4        -14.1         -0.9        -18.3
  -8.6         -7.8         -0.6        -15.9         -9.6
 -18.7        -13.5        -13.4         -8.9        -11.6
  -0.1        -14.9        -19.1        -15.7         -7.9
  11.6          1.4        -10.8        -23.         -19.3
   0.9        -12.2         -8.5          5.5          3.6
   2.8          4.6          1.7          0.4          2.7
 -14.7        -10.4        -13.8        -10.9        -26.
 -16.6        -12.3         -9.4        -13.2          0.3
  -7.6        -16.7          2.6        -17.5          1.3
 -24.         -11.1          1.6          4.3          5.9
 -15.3        -20.5        -17.2          4.8        -17.8
 -20.8        -16.3        -15.5        -13.7        -18.9
 -19.4        -16.5          3.7        -16.4        -16.1
 -12.8          2.5         15.8          5.8          5.7
 -17.1        -23.4        -14.4        -19.9        -22.
 -21.         -13.3        -20.3          4.1        -21.2
 -11.2        -16.8        -15.8        -17.3        -21.1
 -15.1        -21.7        -21.5        -20.2        -14.5
   3.8        -22.9        -12.5        -13.9        -14.6
   3.3          6.7        -18.8          5.6          6.8
 -25.5        -20.1        -17.7        -14.2        -24.1
 -25.           4.2        -21.6        -19.2        -17.9
 -21.8        -18.2          3.4          7.1        -14.8
 -17.6        -25.1        -15.4        -22.2        -19.5
 -24.8        -23.6        -18.4         11.           2.9
 -22.5          3.9        -16.2        -23.9        -24.2
   4.5        -25.2        -20.6          3.5        -20.9
 -21.3          7.         -19.8         11.9          3.2
 -22.6        -16.9        -27.           8.8          9.2
   6.4        -18.1          8.6          5.3          7.5
  13.2         13.         -26.4          5.2        -24.9
 -19.7        -29.         -24.5        -28.           9.
   4.9        -22.8          7.9         24.6         15.
  29.          22.           8.         -26.9          6.1
 -18.6          8.1          5.4        -22.3        -20.4
   6.         -20.7       ]
----------------------------------------
칼럼 이름: bbbeuk
데이터 타입: float64
유니크한 값:
[0. 1.]
----------------------------------------
칼럼 이름: sftun
데이터 타입: float64
유니크한 값:
[2. 1. 0. 3. 4. 5. 6. 7. 9.]
----------------------------------------
칼럼 이름: date362
데이터 타입: object
유니크한 값:
[nan '2021-12-21' '2022-01-03' '2022-01-06' '2022-01-26' '2022-01-14'
 '2022-01-29' '2021-12-13' '2021-12-24' '2021-04-30' '2021-07-06'
 '2022-01-20' '2021-05-29' '2021-06-06' '2021-07-07' '2022-01-09'
 '2022-01-11' '2021-12-31' '2021-12-09' '2021-12-14' '2021-12-20'
 '2022-01-12' '2021-12-28' '2022-01-27' '2022-02-15' '2022-01-31'
 '2022-02-05' '2022-01-17' '2021-01-10' '2021-02-10' '2021-06-17'
 '2021-06-16' '2021-05-31' '2021-06-02' '2021-08-25' '2021-08-10'
 '2021-07-23' '2021-10-02' '2021-09-27' '2021-10-25' '2021-11-17'
 '2021-11-22' '2022-02-01' '2021-11-25' '2022-01-28' '2021-12-08'
 '2022-02-04' '2021-11-29' '2021-12-29' '2021-12-17' '2022-02-09'
 '2022-03-08' '2022-02-16' '2022-02-18' '2022-02-11' '2022-03-19'
 '2021-06-30' '2021-12-07' '2021-12-25' '2021-11-28' '2021-11-12'
 '2022-02-26' '2022-01-13' '2022-01-18' '2022-02-12' '2022-03-22'
 '2022-02-19' '2022-02-23' '2021-05-05' '2021-04-05' '2021-03-24'
 '2021-05-12' '2021-07-08' '2021-06-05' '2021-07-31' '2021-08-07'
 '2021-08-21' '2021-10-08' '2021-12-02' '2021-09-17' '2021-07-04'
 '2021-10-22' '2021-11-02' '2022-01-07' '2021-11-15' '2022-02-08'
 '2021-09-03' '2021-11-13' '2021-12-05' '2022-01-04' '2021-04-21'
 '2021-06-12' '2021-06-27' '2021-07-30' '2021-09-10' '2021-10-12'
 '2021-10-23' '2022-02-17' '2021-05-14' '2021-03-14' '2021-03-20'
 '2021-03-27' '2021-04-17' '2021-03-31' '2021-06-13' '2021-06-26'
 '2021-07-09' '2021-08-20' '2021-08-03' '2021-10-06' '2021-09-15'
 '2021-09-11' '2022-02-22' '2022-01-21' '2022-02-06' '2021-12-27'
 '2022-01-19' '2021-12-10' '2021-12-01' '2022-01-24' '2022-02-03'
 '2021-12-18' '2021-12-11' '2021-12-23' '2022-02-24' '2022-01-15'
 '2022-03-07' '2021-09-06' '2021-11-04' '2022-03-23' '2022-03-12'
 '2022-06-11' '2022-07-06' '2022-07-30' '2022-08-02' '2022-09-28'
 '2022-11-11' '2022-11-26' '2022-11-22' '2022-12-21' '2023-01-28'
 '2023-02-08' '2023-02-06' '2023-01-21' '2023-01-07' '2022-03-28'
 '2022-04-01' '2022-03-30' '2022-04-15' '2022-05-30' '2022-05-25'
 '2022-07-10' '2022-06-20' '2022-05-26' '2022-06-14' '2022-08-05'
 '2022-06-21' '2022-07-02' '2022-06-28' '2022-07-29' '2022-08-15'
 '2022-08-23' '2022-09-03' '2022-09-11' '2022-11-08' '2022-11-17'
 '2022-11-25' '2022-12-07' '2023-02-05' '2022-12-26' '2023-01-31'
 '2023-01-15' '2022-03-16' '2022-04-21' '2022-04-30' '2022-04-26'
 '2022-06-29' '2022-09-06' '2022-10-04' '2022-10-09' '2022-11-23'
 '2022-12-06' '2023-01-09' '2022-03-13' '2022-03-01' '2022-04-11'
 '2022-05-15' '2022-07-05' '2022-06-06' '2022-07-13' '2022-07-18'
 '2022-09-01' '2022-09-12' '2022-08-25' '2022-07-31' '2022-08-04'
 '2022-08-18' '2022-09-10' '2022-09-27' '2022-11-05' '2022-10-29'
 '2022-12-22' '2022-10-13' '2022-12-31' '2022-12-12' '2023-01-16'
 '2023-02-07' '2023-01-20' '2023-01-11' '2023-02-17' '2023-01-29'
 '2023-01-14' '2022-03-02' '2022-03-03' '2022-02-25' '2022-04-03'
 '2022-04-04' '2022-03-31' '2022-03-24' '2022-05-05' '2022-03-29'
 '2022-04-18' '2022-04-24' '2022-05-02' '2022-04-06' '2022-06-02'
 '2022-06-19' '2022-05-16' '2022-06-22' '2022-06-17' '2022-07-20'
 '2022-07-11' '2022-06-16' '2022-07-23' '2022-08-16' '2022-07-28'
 '2022-07-25' '2022-09-18' '2022-08-22' '2022-10-06' '2022-10-15'
 '2022-11-02' '2022-10-02' '2022-09-25' '2022-09-16' '2022-11-06'
 '2022-10-26' '2022-10-22' '2022-12-08' '2022-11-27' '2023-01-06'
 '2023-01-19' '2023-01-13' '2023-03-17' '2022-01-23' '2022-03-14'
 '2022-05-06' '2022-06-01' '2022-06-26' '2022-09-15' '2022-09-07'
 '2022-10-21' '2022-11-29' '2022-11-16' '2023-02-02' '2023-02-22'
 '2022-10-16' '2022-10-31' '2022-11-07' '2022-12-14' '2022-12-20'

In [33]:
summary = []

for col in dfc.columns:
    dtype = dfc[col].dtype
    total = len(dfc)
    
    # NaN 관련
    nan_count = dfc[col].isna().sum()
    nan_ratio = nan_count / total * 100
    
    # zero 관련
    zero_count = (dfc[col] == 0).sum() if np.issubdtype(dtype, np.number) else np.nan
    zero_ratio = (zero_count / total * 100) if np.issubdtype(dtype, np.number) else np.nan
    
    # binary 관련 (0,1로만 구성되어 있는지 여부)
    # 숫자형이면 고유값을 살펴보고, {0,1}의 부분집합인지 확인
    if np.issubdtype(dtype, np.number):
        unique_vals = dfc[col].dropna().unique()
        is_binary = set(unique_vals).issubset({0, 1})
    else:
        is_binary = False  # 숫자형이 아니면 binary로 간주하지 않음
    
    summary.append({
        'column': col,
        'dtype': dtype,
        'nan_count': nan_count,
        'nan_ratio(%)': round(nan_ratio, 2),
        'zero_count': zero_count,
        'zero_ratio(%)': round(zero_ratio, 2) if not pd.isna(zero_ratio) else np.nan,
        'binary_col': 'Binary' if is_binary else np.nan
    })

df_summary = pd.DataFrame(summary)

df_summary = pd.DataFrame(summary)
df_summary.to_csv(os.path.join(crt_path, "cols_summary_1.csv"), index=True)
df_summary

,column,dtype,nan_count,nan_ratio(%),zero_count,zero_ratio(%),binary_col
0,sex_sys_val,int64,0,0.0,10106.0,49.66,Binary
1,birthdt,object,0,0.0,NaN,NaN,NaN
2,bird,object,0,0.0,NaN,NaN,NaN
3,admd,object,0,0.0,NaN,NaN,NaN
4,apgs1,float64,0,0.0,214.0,1.05,NaN
...,...,...,...,...,...,...,...
151,iperr_4,int64,0,0.0,20345.0,99.97,Binary
152,iperroy_1,int64,0,0.0,455.0,2.24,Binary
153,iperroy_4,int64,0,0.0,20296.0,99.72,Binary
154,iperroy_3,int64,0,0.0,19986.0,98.20,Binary
155,iperroy_2,int64,0,0.0,20319.0,99.84,Binary